local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.ptBR = FDJ.ContentLocales.ptBR or {}

FDJ.ContentLocales.ptBR.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "Salão dos Thanes",
        ["location"] = "Sob Altaforja, Dun Morogh",
        ["description"] = "Alguém invadiu a cripta real dos anões sob Altaforja.",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "Cavernas Ígneas",
        ["location"] = "Fenda das Sombras, Orgrimmar",
        ["description"] = "Troggs e cultistas da Lâmina Ardente infestam as cavernas escaldantes sob Orgrimmar.",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "Ruínas de Lordaeron",
        ["location"] = "A cidade arruinada de Lordaeron",
        ["description"] = "As forças do Flagelo ainda assombram a antiga capital enquanto um necromante ganha poder entre as ruínas.",
    },
    ["The Deadmines"] = {
        ["name"] = "Minas Mortas",
        ["location"] = "Arroio da Lua, Cerro Oeste",
        ["description"] = "A Irmandade Défias está construindo um navio de guerra nas minas sob Arroio da Lua.",
    },
    ["Wailing Caverns"] = {
        ["name"] = "Caverna Ululante",
        ["location"] = "Sertões Setentrionais",
        ["description"] = "Sob os Sertões, druidas e Senhores da Presa vigiam Naralex adormecido enquanto criaturas corrompidas rondam a caverna.",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "Bastilha da Presa Negra",
        ["location"] = "Floresta de Pinhaprata",
        ["description"] = "O Arquimago Arugal e seus seguidores worgens ocupam a fortaleza acima da Aldeia Piro!",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "Profundezas Negras",
        ["location"] = "Costa de Zoram, Vale Gris",
        ["description"] = "Ruínas élficas inundadas na Costa de Zoram, ocupadas por nagas, murlocs e cultistas do Martelo do Crepúsculo a serviço de Aku’mai.",
    },
    ["The Stockade"] = {
        ["name"] = "O Cárcere",
        ["location"] = "Ventobravo",
        ["description"] = "Prisioneiros Défias tomaram o controle da prisão de Ventobravo.",
    },
}

FDJ.ContentLocales.ptBR.quests = {
    [386] = { ["name"] = "Aqui se faz, aqui se paga...", ["objective"] = "Mate Targorr, o Terrível, no Cárcere e leve a cabeça dele ao Guarda Berton." },
    [377] = { ["name"] = "Crime e Castigo", ["objective"] = "Mate Dextren Ward no Cárcere e leve a mão dele ao Conselheiro Millstipe." },
    [387] = { ["name"] = "Acabe com a Revolta", ["objective"] = "Mate 10 Prisioneiros Défias, 8 Condenados Défias e 8 Insurgentes Défias no Cárcere." },
    [388] = { ["name"] = "A Cor do Sangue", ["objective"] = "Colete 10 Bandanas de Lã Vermelha dos Défias no Cárcere." },
    [378] = { ["name"] = "A Fúria nas Profundezas", ["objective"] = "Mate Kam Deepfury no Cárcere e leve a cabeça dele a Motley Garmason." },
    [391] = { ["name"] = "Os Motins do Cárcere", ["objective"] = "Mate Bazil Thredd no Cárcere e leve a cabeça dele ao Carcereiro Thelwater." },
    [96395] = {
        ["name"] = "Um antigo rancor",
        ["objective"] = "Dê descanso ao espírito de Faldrim Anvilmar.",
    },
    [96403] = {
        ["name"] = "Heranças importantes",
        ["objective"] = "Colete 8 heranças anãs no Salão dos Thanes.",
    },
    [96394] = {
        ["name"] = "Os mortos inquietos",
        ["objective"] = "Mate 15 aparições enfurecidas e 10 almas atormentadas e, depois, dê descanso ao espírito de Anvilmar.",
    },
    [96393] = {
        ["name"] = "Incursão na antiga Altaforja",
        ["objective"] = "Entre no Salão dos Thanes e obtenha a cabeça de Durgen Dirgehammer.",
        ["note"] = "A cadeia começa com o Mapa Ferro Negro, obtido dos Espiões Ferro Negro em Dun Morogh.",
    },
    [98423] = {
        ["name"] = "O tratado de entendimento",
        ["objective"] = "Leve o tratado de entendimento a Magni Barbabronze em Altaforja.",
        ["note"] = "A tabuleta de pedra fica em um dos cofres do Relicário dos Reis, na sala final de Durgen Dirgehammer. Abra os cofres e interaja com a tabuleta antes de sair da masmorra.",
    },
    [1486] = {
        ["name"] = "Pelego de Anormal",
        ["objective"] = "Leve 20 Pelegos de Anormal a Nalpak.",
    },
    [1491] = {
        ["name"] = "Bebidas inteligentes",
        ["objective"] = "Leve 6 Essências Ululantes a Mebok Mizzyrix.",
    },
    [959] = {
        ["name"] = "Problemas nas docas",
        ["objective"] = "Recupere o Porto 99 Anos de Mad Magglish na Caverna Ululante.",
    },
    [1487] = {
        ["name"] = "Erradicação de anormais",
        ["objective"] = "Mate 7 Devastadores Anormais, 7 Víboras Anormais, 7 Rastejantes Anormais e 7 Presas do Terror Anormais.",
    },
    [6981] = {
        ["name"] = "O fragmento faiscante",
        ["objective"] = "Vá até Vila Catraca, encontre alguém que consiga identificar o Fragmento Faiscante e depois leve-o aonde for instruído.",
        ["note"] = "Esta missão não concede um item diretamente. A missão posterior, “Em Pesadelos”, oferece mais adiante:",
    },
    [914] = {
        ["name"] = "Líderes da Presa",
        ["objective"] = "Leve a Nara Juba Agreste as gemas de Kobrahn, Anacondra, Pythas e Serpentis.",
        ["note"] = "Requer a cadeia dos oásis dos Sertões. Conclua “Os Poços Esquecidos”, “O Oásis Estagnado” e “Seres Alterados” e depois fale com Hamuul Runatótem e Nara Juba Agreste antes que “Líderes da Presa” fique disponível.",
    },
    [962] = {
        ["name"] = "Serpentária",
        ["objective"] = "Colete 10 Serpentárias na Caverna Ululante.",
    },
    [95250] = {
        ["name"] = "Criaturas abomináveis",
        ["objective"] = "Obtenha a cabeça do Barão nas Ruínas de Lordaeron.",
    },
    [97288] = {
        ["name"] = "Tormento sem fim",
        ["objective"] = "Leve a cabeça abominável para a Cidade Baixa.",
        ["note"] = "A escolha de item é concedida na missão seguinte “Tormento sem fim”, na Cidade Baixa.",
    },
    [92401] = {
        ["name"] = "Um pedido apavorado",
        ["objective"] = "Investigue o desaparecimento de Edward Heartweaver nas Ruínas de Lordaeron.",
    },
    [95195] = {
        ["name"] = "Insígnia ensanguentada",
        ["objective"] = "Colete 10 Insígnias Ensanguentadas.",
    },
    [95189] = {
        ["name"] = "Brasão de Lordaeron",
        ["objective"] = "Leve o Brasão de Lordaeron para Ventobravo.",
        ["note"] = "Relatos da comunidade indicam que o brasão pode aparecer em diversos pontos da masmorra, incluindo andares superiores de torres, salas laterais ou criptas perto do Barão e a área de Bjork.",
    },
    [95204] = {
        ["name"] = "Brasão de Lordaeron",
        ["objective"] = "Leve o Brasão de Lordaeron para a Cidade Baixa.",
        ["note"] = "Relatos da comunidade indicam que o brasão pode aparecer em diversos pontos da masmorra, incluindo andares superiores de torres, salas laterais ou criptas perto do Barão e a área de Bjork.",
    },
    [92421] = {
        ["name"] = "Justiça da Luz",
        ["objective"] = "Colete 25 membros intactos nas Ruínas de Lordaeron.",
    },
    [92415] = {
        ["name"] = "Lembre-se de que eu te amo",
        ["objective"] = "Leve a Carta Manchada de Sangue à Matrona dos Órfãos Nightingale.",
        ["note"] = "Esta missão começa com o item “Carta Manchada de Sangue”.",
    },
    [95216] = {
        ["name"] = "A nova praga",
        ["objective"] = "Obtenha a Cepa Altamente Tóxica de Witherfang.",
    },
    [92422] = {
        ["name"] = "Ira de Rath’mael",
        ["objective"] = "Mate Rath’mael nas Ruínas de Lordaeron.",
    },
    [214] = {
        ["name"] = "Bandanas de seda vermelha",
        ["objective"] = "Colete 10 Bandanas de Seda Vermelha dos Défias nas Minas Mortas.",
        ["note"] = "Requer a etapa de escolta da Irmandade Défias.",
    },
    [168] = {
        ["name"] = "Coletando lembranças",
        ["objective"] = "Colete 4 Cartões do Sindicato dos Mineradores dos mineradores mortos-vivos nos túneis fora da instância.",
        ["note"] = "O túnel lateral com mortos-vivos fica antes do portal da instância.",
    },
    [92753] = {
        ["name"] = "Destruição nas Minas Mortas",
        ["objective"] = "Coloque os explosivos ao lado da forja nas Minas Mortas.",
    },
    [167] = {
        ["name"] = "Ah, irmão...",
        ["objective"] = "Obtenha o Distintivo de Thistlenettle do Supervisor Thistlenettle no túnel lateral com mortos-vivos.",
        ["note"] = "O supervisor fica nos túneis antes do portal da instância.",
    },
    [2040] = {
        ["name"] = "Ataque subterrâneo",
        ["objective"] = "Obtenha o Gnoam Sprecklesprocket do Retalhador de Sneed.",
        ["note"] = "Vem depois de “Fale com Shoni”.",
    },
    [166] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Derrote Edwin VanCleef e obtenha a cabeça dele.",
        ["note"] = "Última etapa de masmorra da cadeia “A Irmandade Défias”; conclua as etapas anteriores primeiro.",
    },
    [373] = {
        ["name"] = "A carta não enviada",
        ["objective"] = "Leve a carta ao arquiteto da cidade em Ventobravo.",
        ["note"] = "Inicia uma cadeia posterior que continua com Bazil Thredd.",
    },
    [971] = {
        ["name"] = "Conhecimento nas profundezas",
        ["objective"] = "Recupere o Manuscrito de Lorgalis nas Profundezas Negras.",
        ["note"] = "O Manuscrito de Lorgalis fica em um Baú de Ferro Danificado submerso na Lagoa de Ask’ar, no nicho ao norte logo depois da sala das tartarugas de Ghamoo-ra.",
    },
    [1275] = {
        ["name"] = "Pesquisando a corrupção",
        ["objective"] = "Colete 8 Troncos Cerebrais Corrompidos de criaturas nas Profundezas Negras.",
        ["note"] = "Vem depois de “A Corrupção Distante”.",
    },
    [1198] = {
        ["name"] = "Em busca de Thaelrid",
        ["objective"] = "Encontre o Guarda Argênteo Thaelrid nas Profundezas Negras.",
    },
    [1199] = {
        ["name"] = "Cai o Crepúsculo",
        ["objective"] = "Colete 10 Pingentes do Martelo do Crepúsculo de seus membros nas Profundezas Negras.",
    },
    [1200] = {
        ["name"] = "Vilania nas Profundezas Negras",
        ["objective"] = "Derrote o Lorde Crepuscular Kelris e obtenha a cabeça dele.",
    },
    [6564] = {
        ["name"] = "Lealdade aos Deuses Antigos",
        ["objective"] = "Leve a Nota Úmida a Je’neu Sancrea em Vale Gris.",
    },
    [6562] = {
        ["name"] = "Problemas nas profundezas",
        ["objective"] = "Fale com Je’neu Sancrea em Vale Gris.",
        ["note"] = "Etapa introdutória que leva a “A Essência de Aku’mai”.",
    },
    [6563] = {
        ["name"] = "A essência de Aku’mai",
        ["objective"] = "Colete 20 Safiras de Aku’mai nas Profundezas Negras.",
        ["note"] = "Vem depois de “Problemas nas profundezas”.",
    },
    [6565] = {
        ["name"] = "Lealdade aos Deuses Antigos",
        ["objective"] = "Derrote Lorgus Jett nas Profundezas Negras.",
        ["note"] = "Vem depois da versão de “Lealdade aos Deuses Antigos” que começa com a Nota Úmida.",
    },
    [6561] = {
        ["name"] = "Vilania nas Profundezas Negras",
        ["objective"] = "Derrote o Lorde Crepuscular Kelris e obtenha a cabeça dele.",
    },
    [6921] = {
        ["name"] = "Entre as ruínas",
        ["objective"] = "Obtenha o Núcleo Profundo da Pedra Profunda nas Profundezas Negras.",
        ["note"] = "A Pedra Profunda também está ligada ao encontro opcional com o Barão Aquanis.",
    },
    [5723] = {
        ["name"] = "Testando a força do inimigo",
        ["objective"] = "Mate 8 troggs das Cavernas Ígneas e 8 xamãs das Cavernas Ígneas dentro das Cavernas Ígneas.",
    },
    [5722] = {
        ["name"] = "Procurando a bolsa perdida",
        ["objective"] = "Encontre o cadáver de Maur Totem Sinistro dentro das Cavernas Ígneas e vasculhe-o.",
    },
    [5724] = {
        ["name"] = "Devolvendo a bolsa perdida",
        ["objective"] = "Leve a Bolsa Totem Sinistro a Rahauro em Penhasco do Trovão.",
    },
    [5728] = {
        ["name"] = "Inimigos ocultos",
        ["objective"] = "Mate Bazzalan e Jergosh, o Invocador, dentro das Cavernas Ígneas.",
        ["note"] = "Requer as etapas anteriores da cadeia “Inimigos ocultos” em Orgrimmar. A etapa seguinte oferece mais adiante:",
    },
    [5761] = {
        ["name"] = "Matando a fera",
        ["objective"] = "Mate Taragaman, o Famélico, e obtenha o coração dele.",
    },
    [5725] = {
        ["name"] = "O poder de destruir...",
        ["objective"] = "Colete “Feitiços das Sombras” e “Encantamentos do Caos” nas Cavernas Ígneas.",
    },
    [1098] = {
        ["name"] = "Sicários na Presa Negra",
        ["objective"] = "Encontre o Sicário Adamant e o Sicário Vincent na Bastilha da Presa Negra.",
    },
    [1740] = {
        ["name"] = "O Orbe de Soran’ruk",
        ["objective"] = "Encontre 3 Fragmentos de Soran’ruk e 1 Fragmento Grande de Soran’ruk e leve-os a Doan Karhan.",
        ["note"] = "Missão de classe de Bruxo. Os fragmentos vêm da Bastilha da Presa Negra e das Profundezas Negras.",
    },
    [1013] = {
        ["name"] = "O Livro de Ur",
        ["objective"] = "Leve o Livro de Ur da Bastilha da Presa Negra ao Guardião Bel’dugur.",
    },
    [1014] = {
        ["name"] = "Arugal deve morrer",
        ["objective"] = "Mate o Arquimago Arugal e leve a cabeça dele a Dalar Tecelã da Alvorada.",
        ["note"] = "Os dados atuais de Forever também indicam “Intelecto Arcano” como recompensa aprendida.",
    },
    [96391] = {
        ["name"] = "Mapa subterrâneo",
        ["objective"] = "Leve o Mapa Ferro Negro ao Vidente da Terra Farsen em Dun Morogh.",
        ["description"] = "O Mapa Ferro Negro inicia esta missão e leva diretamente a “Incursão na antiga Altaforja”.",
    },
    [865] = {
        ["name"] = "Chifres de raptor",
        ["objective"] = "Colete 5 Chifres de Raptor Intactos de raptors Foice do Sol e leve-os a Mebok Mizzyrix.",
        ["description"] = "Deve ser concluída antes que “Bebidas inteligentes” fique disponível.",
    },
    [870] = {
        ["name"] = "Os Poços Esquecidos",
        ["objective"] = "Investigue a água dos Poços Esquecidos a noroeste da Encruzilhada e depois faça seu relatório.",
        ["description"] = "Investigue a fissura sob os Poços Esquecidos.",
    },
    [877] = {
        ["name"] = "O Oásis Estagnado",
        ["objective"] = "Leve as Sementes Secas ao Oásis Estagnado, teste-as na fissura e depois volte para Tonga.",
        ["description"] = "Próxima investigação de oásis obrigatória depois de “Os Poços Esquecidos”.",
    },
    [880] = {
        ["name"] = "Seres alterados",
        ["objective"] = "Leve 8 Cascos de Estalador Alterado a Tonga Runatótem na Encruzilhada.",
        ["description"] = "Concluir “Seres alterados” libera “Hamuul Runatótem”.",
    },
    [1489] = {
        ["name"] = "Hamuul Runatótem",
        ["objective"] = "Fale com Hamuul Runatótem no Alto dos Anciãos, Penhasco do Trovão.",
        ["description"] = "Depois de “Seres alterados”, Tonga envia você até Hamuul.",
    },
    [1490] = {
        ["name"] = "Nara Juba Agreste",
        ["objective"] = "Fale com Nara Juba Agreste em Penhasco do Trovão.",
        ["description"] = "Nara Juba Agreste é o último pré-requisito antes de “Líderes da Presa”.",
    },
    [153] = {
        ["name"] = "Bandanas de couro vermelho",
        ["objective"] = "Leve 15 Bandanas de Couro Vermelho ao Batedor Galiaan em Morro da Sentinela.",
        ["description"] = "Deve ser concluída antes de “Bandanas de seda vermelha”.",
    },
    [65] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Fale com Wiley, o Negro, em Vila Plácida.",
        ["description"] = "Primeira etapa da cadeia obrigatória “A Irmandade Défias”.",
    },
    [132] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Leve o bilhete de Wiley de volta a Gryan Mantopedra em Cerro Oeste.",
        ["description"] = "Segunda etapa da cadeia “A Irmandade Défias”.",
    },
    [135] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Leve o bilhete de Wiley ao Mestre Mathias Shaw em Ventobravo.",
        ["description"] = "Shaw investiga a ligação entre os Défias e os Pedreiros.",
    },
    [141] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Leve o relatório de Shaw de volta a Gryan Mantopedra em Cerro Oeste.",
        ["description"] = "Leve a Gryan as descobertas de Shaw sobre Edwin VanCleef.",
    },
    [142] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Localize o Mensageiro Défias em Cerro Oeste e leve a mensagem dele a Gryan Mantopedra.",
        ["description"] = "O mensageiro patrulha as estradas entre Arroio da Lua, Pedreira da Costa do Ouro e Mina de Jango.",
        ["note"] = "O Mensageiro Défias patrulha as estradas entre Arroio da Lua, Pedreira da Costa do Ouro e Mina de Jango.",
    },
    [155] = {
        ["name"] = "A Irmandade Défias",
        ["objective"] = "Escolte o Traidor Défias até ele revelar o esconderijo dos Défias e depois volte a Gryan Mantopedra.",
        ["description"] = "Último pré-requisito antes da etapa de masmorra de “A Irmandade Défias”.",
    },
    [2041] = {
        ["name"] = "Fale com Shoni",
        ["objective"] = "Fale com Shoni, a Silenciosa, em Ventobravo.",
        ["description"] = "Leva diretamente a “Ataque subterrâneo”.",
    },
    [92742] = {
        ["name"] = "Testando os poços",
        ["objective"] = "Use o Kit de Amostra de Água de Poço nos poços da Fazenda Jansen e da Fazenda Molsen.",
        ["description"] = "Primeira missão da cadeia “Solo Tóxico”.",
    },
    [92744] = {
        ["name"] = "Guelras de murloc",
        ["objective"] = "Colete 7 Guelras de Murloc da Costa ao longo do litoral de Cerro Oeste.",
        ["description"] = "Segunda missão da cadeia “Solo Tóxico”.",
    },
    [92745] = {
        ["name"] = "O estado das minas",
        ["objective"] = "Mate 4 Escavadores Kobold na Mina de Jango e 6 Mineiros Patassuja na Pedreira da Costa do Ouro.",
        ["description"] = "Investigue se as minas de Cerro Oeste estão causando a contaminação.",
    },
    [92747] = {
        ["name"] = "Espionagem em Arroio da Lua",
        ["objective"] = "Colete 8 Suprimentos Industriais Suspeitos em Arroio da Lua.",
        ["description"] = "Os suprimentos ficam nas cavernas que levam à entrada das Minas Mortas.",
    },
    [92748] = {
        ["name"] = "Consulta sobre explosivos",
        ["objective"] = "Vá ao Distrito dos Anões de Ventobravo e encontre um engenheiro que possa ajudar com explosivos.",
        ["description"] = "Começa a parte de explosivos da cadeia “Solo Tóxico”.",
    },
    [92749] = {
        ["name"] = "Um plano com dinamite",
        ["objective"] = "Obtenha 10 Dinamites Brutas e volte para Sprite Jumpsprocket em Ventobravo.",
        ["description"] = "A Dinamite Bruta pode ser fabricada, negociada ou comprada na Casa de Leilões.",
        ["note"] = "A Dinamite Bruta pode ser fabricada, negociada ou comprada na Casa de Leilões.",
    },
    [92750] = {
        ["name"] = "Detonação à distância",
        ["objective"] = "Fale com a Inteligência de Ventobravo sobre um detonador remoto.",
        ["description"] = "Você precisa de um detonador remoto para a explosão planejada.",
    },
    [92751] = {
        ["name"] = "Detonação à distância",
        ["objective"] = "Leve o Kit de Detonador Remoto de volta a Sprite Jumpsprocket no Distrito dos Anões.",
        ["description"] = "Devolva o detonador ao engenheiro.",
    },
    [92752] = {
        ["name"] = "Consulta sobre explosivos",
        ["objective"] = "Volte para Alba Fairmoon na estalagem de Morro da Sentinela com os explosivos prontos.",
        ["description"] = "Preparação final antes de “Destruição nas Minas Mortas”.",
    },
    [92819] = {
        ["name"] = "Destruição nas Minas Mortas",
        ["objective"] = "Use o detonador.",
        ["description"] = "Etapa final da cadeia “Solo Tóxico”.",
    },
    [5726] = {
        ["name"] = "Inimigos ocultos",
        ["objective"] = "Leve a Thrall uma Insígnia de Tenente da Lâmina Ardente da Rocha da Caveira.",
        ["description"] = "Primeira etapa obrigatória de “Inimigos ocultos” para a cadeia das Cavernas Ígneas.",
    },
    [5727] = {
        ["name"] = "Inimigos ocultos",
        ["objective"] = "Fale com Neeru Lâmina de Fogo na Fenda das Sombras e depois volte para Thrall.",
        ["description"] = "Neeru fica na Fenda das Sombras perto da entrada das Cavernas Ígneas.",
    },
    [3765] = {
        ["name"] = "A Corrupção Distante",
        ["objective"] = "Vá até Gershala Sussurrante da Noite em Auberdine, Costa Negra.",
        ["description"] = "Missão introdutória da Aliança que deve ser concluída antes de “Pesquisando a corrupção”.",
    },
}

FDJ.ContentLocales.ptBR.bosses = {
    ["Trash Drops"] = "Saque de inimigos comuns",
    ["Lordaeron Captain"] = "Capitão de Lordaeron",
    -- Official client names (Wowhead Forever database, 2026-10-03).
    ["Faldrim Anvilmar"] = "Faldrim Sidermar",
    ["Plunder"] = "Pilhar",
    ["Durgen Dirgehammer"] = "Durgen Martelúgubre",
    ["Lord Cobrahn"] = "Lorde Cobrahn",
    ["Lady Anacondra"] = "Lady Sucurina",
    ["Kresh"] = "Cresh",
    ["Lord Pythas"] = "Lorde Pítias",
    ["Skum"] = "Skória",
    ["Lord Serpentis"] = "Lorde Serpentis",
    ["Verdan the Everliving"] = "Verdan, o Sempre-vivo",
    ["Mutanus the Devourer"] = "Mutanus, o Devorador",
    ["Deviate Faerie Dragon"] = "Dragoleta Anormal",
    ["The Baron"] = "O Barão",
    ["Witherfang"] = "Sugapresa",
    ["The Abandoned"] = "O Abandonado",
    ["Viktor the Vile"] = "Viktor, o Vil",
    ["Miner Johnson"] = "Minerador João",
    ["Sneed's Shredder"] = "Retalhador do Sneed",
    ["Mr. Smite"] = "Sr. Castiga",
    ["Captain Greenskin"] = "Capitão Peleverde",
    ["Cookie"] = "Cuca",
    ["Baron Aquanis"] = "Barão Aquanis",
    ["Old Serra'kis"] = "Velho Serra'kis",
    ["Twilight Lord Kelris"] = "Senhor do Crepúsculo Kelris",
    ["Oggleflint"] = "Pederneiro",
    ["Taragaman the Hungerer"] = "Taragaman, o Famélico",
    ["Jergosh the Invoker"] = "Jergosh, o Invocador",
    ["Fel Steed / Shadow Charger"] = "Corcel Vil / Corcel das Sombras",
    ["Razorclaw the Butcher"] = "Garraguda, o Açougueiro",
    ["Baron Silverlaine"] = "Barão Silverlaine",
    ["Commander Springvale"] = "Comandante Floraval",
    ["Odo the Blindwatcher"] = "Odo, o Vigia Cego",
    ["Deathsworn Captain"] = "Capitão Devoto da Morte",
    ["Arugal's Voidwalker"] = "Emissário do Caos de Arugal",
    ["Fenrus the Devourer"] = "Fenrus, o Devorador",
    ["Wolf Master Nandos"] = "Nandos, o Mestre de Lobos",
    ["Archmage Arugal"] = "Arquimago Arugal",
    ["Targorr the Dread"] = "Targorr, o Horror",
    ["Kam Deepfury"] = "Kam Fundafúria",
    ["Hamhock"] = "Ramoque",
    ["Dextren Ward"] = "Flávio Lúcio",
    ["Bazil Thredd"] = "Basílio Taborda",
    ["Bruegal Ironknuckle"] = "Bruegal Ferroque",
    ["Lyn the Ignored"] = "Lyn, o Ignorado",
    ["Grubbis"] = "Grúdio",
    ["Viscous Fallout"] = "Precipitação Radioativa Viscosa",
    ["Electrocutioner 6000"] = "Eletrocutor 6000",
    ["Crowd Pummeler 9-60"] = "Espanca-gente 9-60",
    ["Mekgineer Thermaplugg"] = "Mecangenheiro Termaplugue",
    ["Dark Iron Ambassador"] = "Embaixador Ferro Negro",
    ["Roogug"] = "Rugug",
    ["Aggem Thorncurse"] = "Aggem Pragacardo",
    ["Death Speaker Jargba"] = "Morta-voz Jargba",
    ["Overlord Ramtusk"] = "Lorde Supremo Marretusco",
    ["Agathelos the Raging"] = "Agathelos, o Furioso",
    ["Charlga Razorflank"] = "Charlga Talhaflanco",
    ["Blind Hunter"] = "Caçador Cego",
    ["Earthcaller Halmgar"] = "Arauto da Terra Halmgar",
    ["Interrogator Vishas"] = "Interrogador Vishas",
    ["Azshir the Sleepless"] = "Ashir, o Insone",
    ["Fallen Champion"] = "Campeão Caído",
    ["Ironspine"] = "Espinha de Ferro",
    ["Bloodmage Thalnos"] = "Mago Sangrento Thalnos",
}

FDJ.ContentLocales.ptBR.slotParts = {
    ["Chest"] = "Torso",
    ["Leather"] = "Couro",
    ["Wrist"] = "Pulsos",
    ["Cloth"] = "Tecido",
    ["Back"] = "Costas",
    ["Waist"] = "Cintura",
    ["Mail"] = "Malha",
    ["Hands"] = "Mãos",
    ["Feet"] = "Pés",
    ["Legs"] = "Pernas",
    ["Neck"] = "Pescoço",
    ["Finger"] = "Dedo",
    ["Trinket"] = "Berloque",
    ["Bag"] = "Bolsa",
    ["One-Hand"] = "Uma mão",
    ["Main Hand"] = "Mão principal",
    ["Off Hand"] = "Mão secundária",
    ["Two-Hand"] = "Duas mãos",
    ["Dagger"] = "Adaga",
    ["Sword"] = "Espada",
    ["Axe"] = "Machado",
    ["Mace"] = "Maça",
    ["Staff"] = "Cajado",
    ["Shield"] = "Escudo",
    ["Polearm"] = "Arma de haste",
    ["Ranged"] = "Longo alcance",
    ["Wand"] = "Varinha",
    ["Thrown"] = "Arremesso",
    ["Engineering"] = "Engenharia",
    ["Quest Item"] = "Item de missão",
    ["Head"] = "Cabeça",
    ["Shoulder"] = "Ombros",
    ["Bow"] = "Arco",
    ["Crossbow"] = "Besta",
    ["Fist Weapon"] = "Arma de punho",
    ["Leatherworking Recipe"] = "Receita de Couraria",
    ["Held In Off-hand"] = "Empunhado na mão secundária",
}

FDJ.ContentLocales.ptBR.replacements = {
    {"Farm Dark Iron Spies here for the Dark Iron Map", "Mate Espiões Ferro Negro aqui para obter o Mapa Ferro Negro"},
    {"Dark Iron Map drops from Dark Iron Spies around Ironband's Compound", "O Mapa Ferro Negro é obtido dos Espiões Ferro Negro ao redor do Acampamento de Vetaferro"},
    {"Alba Fairmoon is inside the Sentinel Hill inn", "Alba Fairmoon está dentro da estalagem de Morro da Sentinela"},
    {"Argos Nightwhisper is in The Park, beside the moonwell area.", "Argos Sussurrante da Noite está no Parque, ao lado da área do poço lunar."},
    {"Serpentbloom starts from Apothecary Zamah in the Pools of Vision beneath Spirit Rise", "Serpentária começa com a Boticária Zamah nos Poços da Visão, sob o Alto dos Espíritos"},
    {"Start Hidden Enemies here", "“Inimigos ocultos” começa aqui"},
    {"Start In Search of Thaelrid here", "“Em busca de Thaelrid” começa aqui"},
    {"Start Raptor Horns here", "“Chifres de raptor” começa aqui"},
    {"Start Red Leather Bandanas here", "“Bandanas de couro vermelho” começa aqui"},
    {"Start Speak with Shoni here", "“Fale com Shoni” começa aqui"},
    {"Start Testing the Wells here", "“Testando os poços” começa aqui"},
    {"Start The Defias Brotherhood here", "“A Irmandade Défias” começa aqui"},
    {"Start The Forgotten Pools here", "“Os Poços Esquecidos” começa aqui"},
    {"by the bridge / vault entrance in", "perto da ponte / entrada do cofre em"},
    {"near the dungeon entrance", "perto da entrada da masmorra"},
    {"after the first room", "depois da primeira sala"},
    {"inside the dungeon", "dentro da masmorra"},
    {"just inside Ruins of Lordaeron", "logo dentro das Ruínas de Lordaeron"},
    {"graveyard inside Ruins of Lordaeron", "cemitério dentro das Ruínas de Lordaeron"},
    {"%(%s*after Underground Map%s*%)", "(depois de “Mapa subterrâneo”)"},
    {"above the entrance to", "acima da entrada de"},
    {"left of the entrance", "à esquerda da entrada"},
    {"Follow the quest directions beginning in", "Siga as instruções da missão começando em"},
    {"Stone tablet inside a vault in the Reliquary of Kings", "Tabuleta de pedra dentro de um cofre no Relicário dos Reis"},
    {"Durgen Dirgehammer's room", "sala de Durgen Dirgehammer"},
    {"Maur Grimtotem's corpse", "cadáver de Maur Totem Sinistro"},
    {"dropped by Dark Iron Spies", "obtido dos Espiões Ferro Negro"},
    {"Blackfathom Tide Priestesses", "Sacerdotisas das Marés das Profundezas Negras"},
    {"taken from", "obtido de"},
    {"dropped by", "obtido de"},
    {"at Ironband's Compound", "no Acampamento de Vetaferro"},
    {"Ironband's Compound", "Acampamento de Vetaferro"},
    {"Dark Iron Spies", "Espiões Ferro Negro"},
    {"Northern Barrens", "Sertões Setentrionais"},
    {"The Barrens", "Sertões"},
    {"Cleft of Shadow", "Fenda das Sombras"},
    {"Valley of Wisdom", "Vale da Sabedoria"},
    {"Royal Quarter", "Bairro Real"},
    {"Elder Rise", "Alto dos Anciãos"},
    {"Dwarven District", "Distrito dos Anões"},
    {"Cathedral Square", "Praça da Catedral"},
    {"Old Town", "Cidade Velha"},
    {"Sentinel Hill tower", "torre de Morro da Sentinela"},
    {"Sentinel Hill inn", "estalagem de Morro da Sentinela"},
    {"Sentinel Hill", "Morro da Sentinela"},
    {"Stormwind City", "Ventobravo"},
    {"Stormwind", "Ventobravo"},
    {"Ironforge", "Altaforja"},
    {"Thunder Bluff", "Penhasco do Trovão"},
    {"Undercity", "Cidade Baixa"},
    {"Silverpine Forest", "Floresta de Pinhaprata"},
    {"The Sepulcher", "O Sepulcro"},
    {"Darkshore", "Costa Negra"},
    {"Ashenvale", "Vale Gris"},
    {"Stonetalon Mountains", "Cordilheira das Torres de Pedra"},
    {"Redridge Mountains", "Montanhas Cristarrubra"},
    {"Zoram Strand", "Costa de Zoram"},
    {"Zoram'gar Outpost", "Posto Avançado de Zoram’gar"},
    {"Moonbrook", "Arroio da Lua"},
    {"Ratchet", "Vila Catraca"},
    {"The Crossroads", "A Encruzilhada"},
    {"Craftsmen's Terrace", "Terraço dos Artesãos"},
    {"Forlorn Cavern", "Caverna Abandonada"},
    {"Skull Rock", "Rocha da Caveira"},
    {"Gold Coast Quarry", "Pedreira da Costa do Ouro"},
    {"Jangolode Mine", "Mina de Jango"},
    {"Lakeshire", "Vila Plácida"},
    {"The Park", "O Parque"},
    {"Pyrewood Village", "Aldeia Piro"},
    {"southeast of Brill", "a sudeste de Brill"},
    {"Pools of Vision", "Poços da Visão"},
    {"Sun Rock Retreat", "Retiro Rocha do Sol"},
    {"Tinker Town", "Gnomeregan"},
    {"Darnassus", "Darnassus"},
    {"Apothecarium", "Apotecário"},
    {"inside Blackfathom Deeps", "nas Profundezas Negras"},
    {"inside Shadowfang Keep", "na Bastilha da Presa Negra"},
    {"inside Ragefire Chasm", "nas Cavernas Ígneas"},
    {"inside Ruins of Lordaeron", "nas Ruínas de Lordaeron"},
    {"inside Hall of Thanes", "no Salão dos Thanes"},
    {"inside the Deadmines", "nas Minas Mortas"},
    {"Wailing Caverns", "Caverna Ululante"},
    {"Blackfathom Deeps", "Profundezas Negras"},
    {"Shadowfang Keep", "Bastilha da Presa Negra"},
    {"Ragefire Chasm", "Cavernas Ígneas"},
    {"Ruins of Lordaeron", "Ruínas de Lordaeron"},
    {"Hall of Thanes", "Salão dos Thanes"},
    {"The Deadmines", "Minas Mortas"},
    {"Deadmines", "Minas Mortas"},
    {"Item start:", "Item que inicia a missão:"},
    {"Use ", "Use "},
    {"Dropped by:", "Obtido de:"},
    {"Looted from", "Saqueado de"},
    {"Rare spawn.", "Aparecimento raro."},
    {"Quest Item", "Item de missão"},
    {"Trash Drops", "Saque de inimigos comuns"},
    {"Alliance", "Aliança"},
    {"Horde", "Horda"},
    {"Both", "Ambas"},
    {"Warlock", "Bruxo"},
    {"Mage", "Mago"},
    {"Priest", "Sacerdote"},
    {"Rogue", "Ladino"},
    {"Warrior", "Guerreiro"},
    {"Hunter", "Caçador"},
    {"Druid", "Druida"},
    {"Paladin", "Paladino"},
    {"Shaman", "Xamã"},
}
