local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.itIT = FDJ.ContentLocales.itIT or {}

FDJ.ContentLocales.itIT.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "Sala dei Thane",
        ["location"] = "Sotto Forgiardente, Dun Morogh",
        ["description"] = "Qualcuno si è introdotto nella cripta reale dei nani sotto Forgiardente.",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "Baratro di Fiamma Furente",
        ["location"] = "Fenditura dell’Ombra, Orgrimmar",
        ["description"] = "Trogg e cultisti della Lama Infuocata infestano le caverne roventi sotto Orgrimmar.",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "Rovine di Lordaeron",
        ["location"] = "La città in rovina di Lordaeron",
        ["description"] = "Le forze del Flagello infestano ancora l’antica capitale mentre un negromante accresce il proprio potere tra le rovine.",
    },
    ["The Deadmines"] = {
        ["name"] = "Miniere della Morte",
        ["location"] = "Riva del Lago, Marche Occidentali",
        ["description"] = "La Fratellanza dei Defias sta costruendo una nave da guerra nelle miniere sotto Riva del Lago.",
    },
    ["Wailing Caverns"] = {
        ["name"] = "Caverna dei Lamenti",
        ["location"] = "Savane Settentrionali",
        ["description"] = "Sotto le Savane, druidi e Signori della Zanna sorvegliano Naralex addormentato mentre creature corrotte vagano nelle caverne.",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "Forte di Zannascura",
        ["location"] = "Selva Pinargento",
        ["description"] = "L’Arcimago Arugal e i suoi seguaci worgen occupano il forte sopra Boscovespro.",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "Abissi di Fondocupo",
        ["location"] = "Lido di Zoram, Valtetra",
        ["description"] = "Una rovina degli elfi della notte sommersa sul Lido di Zoram, occupata da naga, murloc e cultisti del Martello del Crepuscolo al servizio di Aku’mai.",
    },
    ["The Stockade"] = {
        ["name"] = "Le Segrete",
        ["location"] = "Roccavento",
        ["description"] = "I prigionieri dei Defias hanno preso il controllo della prigione di Roccavento.",
    },
}

FDJ.ContentLocales.itIT.quests = {
    [386] = { ["name"] = "Chi la fa, l’aspetti...", ["objective"] = "Uccidi Targorr il Terribile nelle Segrete e porta la sua testa alla guardia Berton." },
    [377] = { ["name"] = "Delitto e castigo", ["objective"] = "Uccidi Dextren Ward nelle Segrete e porta la sua mano al consigliere Millstipe." },
    [387] = { ["name"] = "Sedare la rivolta", ["objective"] = "Uccidi 10 prigionieri Defias, 8 detenuti Defias e 8 insorti Defias nelle Segrete." },
    [388] = { ["name"] = "Il colore del sangue", ["objective"] = "Raccogli 10 bandane di lana rossa dai Defias nelle Segrete." },
    [378] = { ["name"] = "La furia nelle profondità", ["objective"] = "Uccidi Kam Deepfury nelle Segrete e porta la sua testa a Motley Garmason." },
    [391] = { ["name"] = "La rivolta delle Segrete", ["objective"] = "Uccidi Bazil Thredd nelle Segrete e porta la sua testa al guardiano Thelwater." },
    [96395] = {
        ["name"] = "Un antico rancore",
        ["objective"] = "Dona pace allo spirito di Faldrim Anvilmar.",
    },
    [96403] = {
        ["name"] = "Cimeli importanti",
        ["objective"] = "Raccogli 8 cimeli nanici nella Sala dei Thane.",
    },
    [96394] = {
        ["name"] = "I morti inquieti",
        ["objective"] = "Uccidi 15 apparizioni infuriate e 10 anime tormentate, poi dona pace allo spirito di Anvilmar.",
    },
    [96393] = {
        ["name"] = "Incursione nella Vecchia Forgiardente",
        ["objective"] = "Entra nella Sala dei Thane e recupera la testa di Durgen Dirgehammer.",
        ["note"] = "La catena inizia con la Mappa Ferroscuro, lasciata cadere dalle Spie Ferroscuro di Dun Morogh.",
    },
    [98423] = {
        ["name"] = "Il trattato d’intesa",
        ["objective"] = "Porta il trattato d’intesa a Magni Barbabronzea a Forgiardente.",
        ["note"] = "La tavoletta di pietra si trova in una delle camere del Reliquiario dei Re, nella stanza finale di Durgen Dirgehammer. Apri le camere e interagisci con la tavoletta prima di lasciare la spedizione.",
    },
    [1486] = {
        ["name"] = "Pelli devianti",
        ["objective"] = "Porta 20 pelli devianti a Nalpak.",
    },
    [1491] = {
        ["name"] = "Bevande intelligenti",
        ["objective"] = "Porta 6 Essenze Lamentose a Mebok Mizzyrix.",
    },
    [959] = {
        ["name"] = "Problemi al molo",
        ["objective"] = "Recupera il Porto Invecchiato 99 Anni di Mad Magglish nella Caverna dei Lamenti.",
    },
    [1487] = {
        ["name"] = "Eradicazione dei devianti",
        ["objective"] = "Uccidi 7 devastatori devianti, 7 vipere devianti, 7 striscianti devianti e 7 zanne del terrore devianti.",
    },
    [6981] = {
        ["name"] = "La scheggia luminosa",
        ["objective"] = "Raggiungi Porto Paranco, trova qualcuno in grado di identificare la scheggia luminosa e portala poi dove ti viene indicato.",
        ["note"] = "Questa missione non assegna direttamente un oggetto. La missione successiva, «Negli incubi», offre più avanti:",
    },
    [914] = {
        ["name"] = "I Signori della Zanna",
        ["objective"] = "Porta a Nara Crine Selvaggio le gemme di Kobrahn, Anacondra, Pythas e Serpentis.",
        ["note"] = "Richiede la catena delle oasi nelle Savane. Completa «Le pozze dimenticate», «L’oasi stagnante» ed «Esseri alterati», poi parla con Hamuul Totem Runico e Nara Crine Selvaggio prima che «I Signori della Zanna» diventi disponibile.",
    },
    [962] = {
        ["name"] = "Fiore di serpente",
        ["objective"] = "Raccogli 10 fiori di serpente nella Caverna dei Lamenti.",
    },
    [95250] = {
        ["name"] = "Creature abominevoli",
        ["objective"] = "Recupera la testa del Barone nelle Rovine di Lordaeron.",
    },
    [97288] = {
        ["name"] = "Tormento senza fine",
        ["objective"] = "Porta la testa abominevole a Sepulcra.",
        ["note"] = "La scelta dell’oggetto viene assegnata nella missione successiva «Tormento senza fine» a Sepulcra.",
    },
    [92401] = {
        ["name"] = "Una richiesta impaurita",
        ["objective"] = "Indaga sulla scomparsa di Edward Heartweaver nelle Rovine di Lordaeron.",
    },
    [95195] = {
        ["name"] = "Insegna insanguinata",
        ["objective"] = "Raccogli 10 insegne insanguinate.",
    },
    [95189] = {
        ["name"] = "Stemma di Lordaeron",
        ["objective"] = "Porta lo Stemma di Lordaeron a Roccavento.",
        ["note"] = "Le segnalazioni della community indicano che lo stemma può comparire in diversi punti della spedizione, inclusi i piani superiori delle torri, stanze laterali o cripte vicino al Barone e l’area di Bjork.",
    },
    [95204] = {
        ["name"] = "Stemma di Lordaeron",
        ["objective"] = "Porta lo Stemma di Lordaeron a Sepulcra.",
        ["note"] = "Le segnalazioni della community indicano che lo stemma può comparire in diversi punti della spedizione, inclusi i piani superiori delle torri, stanze laterali o cripte vicino al Barone e l’area di Bjork.",
    },
    [92421] = {
        ["name"] = "Giustizia della Luce",
        ["objective"] = "Raccogli 25 arti intatti nelle Rovine di Lordaeron.",
    },
    [92415] = {
        ["name"] = "Ricorda che ti amo",
        ["objective"] = "Porta la lettera macchiata di sangue alla Matrona degli Orfani Nightingale.",
        ["note"] = "Questa missione inizia con l’oggetto «Lettera macchiata di sangue».",
    },
    [95216] = {
        ["name"] = "La nuova piaga",
        ["objective"] = "Recupera il ceppo altamente tossico da Witherfang.",
    },
    [92422] = {
        ["name"] = "Ira di Rath’mael",
        ["objective"] = "Uccidi Rath’mael nelle Rovine di Lordaeron.",
    },
    [214] = {
        ["name"] = "Bandane di seta rossa",
        ["objective"] = "Raccogli 10 bandane di seta rossa dai Defias nelle Miniere della Morte.",
        ["note"] = "Richiede il passaggio di scorta della Fratellanza dei Defias.",
    },
    [168] = {
        ["name"] = "Raccogliere ricordi",
        ["objective"] = "Raccogli 4 tessere del Sindacato dei Minatori dai minatori non morti nei tunnel fuori dall’istanza.",
        ["note"] = "Il tunnel laterale dei non morti si trova prima del portale dell’istanza.",
    },
    [92753] = {
        ["name"] = "Distruzione nelle Miniere della Morte",
        ["objective"] = "Posiziona gli esplosivi accanto alla forgia nelle Miniere della Morte.",
    },
    [167] = {
        ["name"] = "Oh, fratello…",
        ["objective"] = "Recupera il distintivo di Thistlenettle dal Caposquadra Thistlenettle nel tunnel laterale dei non morti.",
        ["note"] = "Il caposquadra si trova nei tunnel prima del portale dell’istanza.",
    },
    [2040] = {
        ["name"] = "Assalto sotterraneo",
        ["objective"] = "Recupera il Gnoam Sprecklesprocket dal Trituratore di Sneed.",
        ["note"] = "Segue «Parla con Shoni».",
    },
    [166] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Sconfiggi Edwin VanCleef e recupera la sua testa.",
        ["note"] = "Ultimo passaggio in spedizione della catena «La Fratellanza dei Defias»; completa prima i passaggi precedenti.",
    },
    [373] = {
        ["name"] = "La lettera non spedita",
        ["objective"] = "Porta la lettera all’architetto cittadino di Roccavento.",
        ["note"] = "Avvia una catena successiva che prosegue con Bazil Thredd.",
    },
    [971] = {
        ["name"] = "Conoscenza negli abissi",
        ["objective"] = "Recupera il Manoscritto di Lorgalis negli Abissi di Fondocupo.",
        ["note"] = "Il Manoscritto di Lorgalis si trova in un forziere di ferro danneggiato sott’acqua nello Stagno di Ask’ar, nella nicchia settentrionale subito dopo la sala delle tartarughe di Ghamoo-ra.",
    },
    [1275] = {
        ["name"] = "Studiare la corruzione",
        ["objective"] = "Raccogli 8 tronchi cerebrali corrotti dalle creature negli Abissi di Fondocupo.",
        ["note"] = "Segue «La corruzione lontana».",
    },
    [1198] = {
        ["name"] = "Alla ricerca di Thaelrid",
        ["objective"] = "Trova la Guardia d’Argento Thaelrid negli Abissi di Fondocupo.",
    },
    [1199] = {
        ["name"] = "Cala il crepuscolo",
        ["objective"] = "Raccogli 10 pendenti del Martello del Crepuscolo dai suoi membri negli Abissi di Fondocupo.",
    },
    [1200] = {
        ["name"] = "Malvagità a Fondocupo",
        ["objective"] = "Sconfiggi il Signore del Crepuscolo Kelris e recupera la sua testa.",
    },
    [6564] = {
        ["name"] = "Fedeltà agli Dei Antichi",
        ["objective"] = "Porta la Nota Umida a Je’neu Sancrea a Valtetra.",
    },
    [6562] = {
        ["name"] = "Problemi negli abissi",
        ["objective"] = "Parla con Je’neu Sancrea a Valtetra.",
        ["note"] = "Passaggio introduttivo che porta a «L’essenza di Aku’mai».",
    },
    [6563] = {
        ["name"] = "L’essenza di Aku’mai",
        ["objective"] = "Raccogli 20 zaffiri di Aku’mai negli Abissi di Fondocupo.",
        ["note"] = "Segue «Problemi negli abissi».",
    },
    [6565] = {
        ["name"] = "Fedeltà agli Dei Antichi",
        ["objective"] = "Sconfiggi Lorgus Jett negli Abissi di Fondocupo.",
        ["note"] = "Segue la versione di «Fedeltà agli Dei Antichi» che inizia con la Nota Umida.",
    },
    [6561] = {
        ["name"] = "Malvagità a Fondocupo",
        ["objective"] = "Sconfiggi il Signore del Crepuscolo Kelris e recupera la sua testa.",
    },
    [6921] = {
        ["name"] = "Tra le rovine",
        ["objective"] = "Recupera il Nucleo Profondo dalla Pietra Profonda negli Abissi di Fondocupo.",
        ["note"] = "La Pietra Profonda è anche collegata all’incontro opzionale con il Barone Aquanis.",
    },
    [5723] = {
        ["name"] = "Mettere alla prova la forza del nemico",
        ["objective"] = "Uccidi 8 trogg del Baratro di Fiamma Furente e 8 sciamani del Baratro di Fiamma Furente nel Baratro di Fiamma Furente.",
    },
    [5722] = {
        ["name"] = "Alla ricerca della borsa perduta",
        ["objective"] = "Trova il cadavere di Maur Totem Truce nel Baratro di Fiamma Furente e perquisiscilo.",
    },
    [5724] = {
        ["name"] = "Restituire la borsa perduta",
        ["objective"] = "Porta la Borsa Totem Truce a Rahauro a Picco del Tuono.",
    },
    [5728] = {
        ["name"] = "Nemici nascosti",
        ["objective"] = "Uccidi Bazzalan e Jergosh l’Invocatore nel Baratro di Fiamma Furente.",
        ["note"] = "Richiede i passaggi precedenti della catena «Nemici nascosti» a Orgrimmar. Il passaggio successivo offre più avanti:",
    },
    [5761] = {
        ["name"] = "Uccidere la bestia",
        ["objective"] = "Uccidi Taragaman il Famelico e recupera il suo cuore.",
    },
    [5725] = {
        ["name"] = "Il potere di distruggere…",
        ["objective"] = "Raccogli «Incantesimi dell’Ombra» e «Invocazioni del Vuoto» nel Baratro di Fiamma Furente.",
    },
    [1098] = {
        ["name"] = "Inseguitori della Morte a Zannascura",
        ["objective"] = "Trova l’Inseguitore della Morte Adamant e l’Inseguitore della Morte Vincent nel Forte di Zannascura.",
    },
    [1740] = {
        ["name"] = "Il Globo di Soran’ruk",
        ["objective"] = "Trova 3 frammenti di Soran’ruk e 1 frammento grande di Soran’ruk e riportali a Doan Karhan.",
        ["note"] = "Missione di classe dello Stregone. I frammenti provengono dal Forte di Zannascura e dagli Abissi di Fondocupo.",
    },
    [1013] = {
        ["name"] = "Il Libro di Ur",
        ["objective"] = "Porta il Libro di Ur dal Forte di Zannascura al Custode Bel’dugur.",
    },
    [1014] = {
        ["name"] = "Arugal deve morire",
        ["objective"] = "Uccidi l’Arcimago Arugal e porta la sua testa a Dalar Tessialba.",
        ["note"] = "I dati Forever attuali indicano anche «Intelletto Arcano» come ricompensa appresa.",
    },
    [96391] = {
        ["name"] = "Mappa sotterranea",
        ["objective"] = "Porta la Mappa Ferroscuro a Earthseer Farsen a Dun Morogh.",
        ["description"] = "La Mappa Ferroscuro avvia questa missione e conduce direttamente a «Incursione nella Vecchia Forgiardente».",
    },
    [865] = {
        ["name"] = "Corna di raptor",
        ["objective"] = "Raccogli 5 corna di raptor intatte dai Falciatori Squamarossa e portale a Mebok Mizzyrix.",
        ["description"] = "Deve essere completata prima che «Bevande intelligenti» diventi disponibile.",
    },
    [870] = {
        ["name"] = "Le pozze dimenticate",
        ["objective"] = "Esamina l’acqua delle pozze dimenticate a nord-ovest del Crocevia e poi fai rapporto.",
        ["description"] = "Esamina la fenditura sotto le pozze dimenticate.",
    },
    [877] = {
        ["name"] = "L’oasi stagnante",
        ["objective"] = "Porta i semi secchi all’oasi stagnante, testali presso la fenditura e torna da Tonga.",
        ["description"] = "La successiva indagine obbligatoria sulle oasi dopo «Le pozze dimenticate».",
    },
    [880] = {
        ["name"] = "Esseri alterati",
        ["objective"] = "Porta 8 gusci di morsicatore alterato a Tonga Totem Runico al Crocevia.",
        ["description"] = "Completare «Esseri alterati» sblocca «Hamuul Totem Runico».",
    },
    [1489] = {
        ["name"] = "Hamuul Totem Runico",
        ["objective"] = "Parla con Hamuul Totem Runico sull’Altura degli Anziani a Picco del Tuono.",
        ["description"] = "Dopo «Esseri alterati», Tonga ti manda da Hamuul.",
    },
    [1490] = {
        ["name"] = "Nara Crine Selvaggio",
        ["objective"] = "Parla con Nara Crine Selvaggio a Picco del Tuono.",
        ["description"] = "Nara Crine Selvaggio è l’ultimo requisito prima de «I Signori della Zanna».",
    },
    [153] = {
        ["name"] = "Bandane di cuoio rosso",
        ["objective"] = "Porta 15 bandane di cuoio rosso all’Esploratore Galiaan a Colle Sentinella.",
        ["description"] = "Deve essere completata prima di «Bandane di seta rossa».",
    },
    [65] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Parla con Wiley il Nero a Borgolago.",
        ["description"] = "Primo passaggio della catena richiesta «La Fratellanza dei Defias».",
    },
    [132] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Riporta la nota di Wiley a Gryan Mantoforte nelle Marche Occidentali.",
        ["description"] = "Secondo passaggio della catena «La Fratellanza dei Defias».",
    },
    [135] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Porta la nota di Wiley al Maestro Mathias Shaw a Roccavento.",
        ["description"] = "Shaw indaga sul legame tra i Defias e gli Scalpellini.",
    },
    [141] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Riporta il rapporto di Shaw a Gryan Mantoforte nelle Marche Occidentali.",
        ["description"] = "Porta a Gryan le scoperte di Shaw su Edwin VanCleef.",
    },
    [142] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Trova il Messaggero Defias nelle Marche Occidentali e porta il suo messaggio a Gryan Mantoforte.",
        ["description"] = "Il messaggero pattuglia le strade tra Riva del Lago, la Cava della Costa d’Oro e la Miniera di Jango.",
        ["note"] = "Il Messaggero Defias pattuglia le strade tra Riva del Lago, la Cava della Costa d’Oro e la Miniera di Jango.",
    },
    [155] = {
        ["name"] = "La Fratellanza dei Defias",
        ["objective"] = "Scorta il Traditore Defias finché non rivela il nascondiglio dei Defias, poi torna da Gryan Mantoforte.",
        ["description"] = "Ultimo requisito prima del passaggio in spedizione de «La Fratellanza dei Defias».",
    },
    [2041] = {
        ["name"] = "Parla con Shoni",
        ["objective"] = "Parla con Shoni la Silenziosa a Roccavento.",
        ["description"] = "Conduce direttamente ad «Assalto sotterraneo».",
    },
    [92742] = {
        ["name"] = "Testare i pozzi",
        ["objective"] = "Usa il Kit per Campioni d’Acqua dei Pozzi ai pozzi della Fattoria Jansen e della Fattoria Molsen.",
        ["description"] = "Prima missione della catena «Terreno tossico».",
    },
    [92744] = {
        ["name"] = "Branchie di murloc",
        ["objective"] = "Raccogli 7 branchie di murloc Lungacosta lungo la costa delle Marche Occidentali.",
        ["description"] = "Seconda missione della catena «Terreno tossico».",
    },
    [92745] = {
        ["name"] = "Lo stato delle miniere",
        ["objective"] = "Uccidi 4 scavatori coboldi nella Miniera di Jango e 6 minatori Zampafiume nella Cava della Costa d’Oro.",
        ["description"] = "Indaga se le miniere delle Marche Occidentali stanno causando la contaminazione.",
    },
    [92747] = {
        ["name"] = "Spionaggio a Riva del Lago",
        ["objective"] = "Raccogli 8 rifornimenti industriali sospetti a Riva del Lago.",
        ["description"] = "I rifornimenti si trovano nelle caverne che conducono verso l’ingresso delle Miniere della Morte.",
    },
    [92748] = {
        ["name"] = "Consulenza esplosiva",
        ["objective"] = "Raggiungi il Distretto dei Nani di Roccavento e trova un ingegnere che possa aiutare con gli esplosivi.",
        ["description"] = "Avvia la parte degli esplosivi della catena «Terreno tossico».",
    },
    [92749] = {
        ["name"] = "Un piano con la dinamite",
        ["objective"] = "Recupera 10 Dinamiti Grezze e torna da Sprite Jumpsprocket a Roccavento.",
        ["description"] = "La Dinamite Grezza può essere fabbricata, scambiata o acquistata alla Casa d’Aste.",
        ["note"] = "La Dinamite Grezza può essere fabbricata, scambiata o acquistata alla Casa d’Aste.",
    },
    [92750] = {
        ["name"] = "Detonazione a distanza",
        ["objective"] = "Parla con l’Intelligence di Roccavento di un detonatore remoto.",
        ["description"] = "Serve un detonatore remoto per l’esplosione pianificata.",
    },
    [92751] = {
        ["name"] = "Detonazione a distanza",
        ["objective"] = "Riporta il kit del detonatore remoto a Sprite Jumpsprocket nel Distretto dei Nani.",
        ["description"] = "Riporta il detonatore all’ingegnere.",
    },
    [92752] = {
        ["name"] = "Consulenza esplosiva",
        ["objective"] = "Torna da Alba Fairmoon nella locanda di Colle Sentinella con gli esplosivi completati.",
        ["description"] = "Preparazione finale prima di «Distruzione nelle Miniere della Morte».",
    },
    [92819] = {
        ["name"] = "Distruzione nelle Miniere della Morte",
        ["objective"] = "Usa il detonatore.",
        ["description"] = "Ultimo passaggio della catena «Terreno tossico».",
    },
    [5726] = {
        ["name"] = "Nemici nascosti",
        ["objective"] = "Porta a Thrall un’Insegna da Tenente della Lama Infuocata da Roccia del Teschio.",
        ["description"] = "Primo passaggio richiesto di «Nemici nascosti» per la catena del Baratro di Fiamma Furente.",
    },
    [5727] = {
        ["name"] = "Nemici nascosti",
        ["objective"] = "Parla con Neeru Lamardente nella Fenditura dell’Ombra e poi torna da Thrall.",
        ["description"] = "Neeru si trova nella Fenditura dell’Ombra vicino all’ingresso del Baratro di Fiamma Furente.",
    },
    [3765] = {
        ["name"] = "La corruzione lontana",
        ["objective"] = "Raggiungi Gershala Sussurranotte ad Auberdine, Rivafosca.",
        ["description"] = "Missione introduttiva dell’Alleanza da completare prima di «Studiare la corruzione».",
    },
}

FDJ.ContentLocales.itIT.bosses = {
    ["Trash Drops"] = "Bottino trash",
    ["The Baron"] = "Il Barone",
    ["The Abandoned"] = "L’Abbandonato",
    ["Lordaeron Captain"] = "Capitano di Lordaeron",
}

FDJ.ContentLocales.itIT.slotParts = {
    ["Chest"] = "Torso",
    ["Leather"] = "Cuoio",
    ["Wrist"] = "Polsi",
    ["Cloth"] = "Stoffa",
    ["Back"] = "Schiena",
    ["Waist"] = "Vita",
    ["Mail"] = "Maglia",
    ["Hands"] = "Mani",
    ["Feet"] = "Piedi",
    ["Legs"] = "Gambe",
    ["Neck"] = "Collo",
    ["Finger"] = "Dito",
    ["Trinket"] = "Monile",
    ["Bag"] = "Borsa",
    ["One-Hand"] = "Una mano",
    ["Main Hand"] = "Mano primaria",
    ["Off Hand"] = "Mano secondaria",
    ["Two-Hand"] = "Due mani",
    ["Dagger"] = "Pugnale",
    ["Sword"] = "Spada",
    ["Axe"] = "Ascia",
    ["Mace"] = "Mazza",
    ["Staff"] = "Bastone",
    ["Shield"] = "Scudo",
    ["Polearm"] = "Arma ad asta",
    ["Ranged"] = "Distanza",
    ["Wand"] = "Bacchetta",
    ["Thrown"] = "Da lancio",
    ["Engineering"] = "Ingegneria",
    ["Quest Item"] = "Oggetto di missione",
    ["Head"] = "Testa",
    ["Shoulder"] = "Spalle",
    ["Bow"] = "Arco",
    ["Crossbow"] = "Balestra",
    ["Fist Weapon"] = "Arma da pugno",
    ["Leatherworking Recipe"] = "Ricetta di conciatura",
    ["Held In Off-hand"] = "Tenuto nella mano secondaria",
}

FDJ.ContentLocales.itIT.replacements = {
    {"Farm Dark Iron Spies here for the Dark Iron Map", "Uccidi qui le Spie Ferroscuro per ottenere la Mappa Ferroscuro"},
    {"Dark Iron Map drops from Dark Iron Spies around Ironband's Compound", "La Mappa Ferroscuro viene lasciata dalle Spie Ferroscuro intorno all’Accampamento di Ironband"},
    {"Alba Fairmoon is inside the Sentinel Hill inn", "Alba Fairmoon si trova nella locanda di Colle Sentinella"},
    {"Argos Nightwhisper is in The Park, beside the moonwell area.", "Argos Soffionotturno si trova nel Parco, vicino al Pozzo Lunare."},
    {"Serpentbloom starts from Apothecary Zamah in the Pools of Vision beneath Spirit Rise", "Fiore di Serpente inizia dall’Apotecaria Zamah alle Pozze delle Visioni, sotto l’Altura degli Spiriti"},
    {"Start Hidden Enemies here", "« Nemici nascosti » inizia qui"},
    {"Start In Search of Thaelrid here", "« Alla ricerca di Thaelrid » inizia qui"},
    {"Start Raptor Horns here", "« Corna di raptor » inizia qui"},
    {"Start Red Leather Bandanas here", "« Bandane di cuoio rosso » inizia qui"},
    {"Start Speak with Shoni here", "« Parla con Shoni » inizia qui"},
    {"Start Testing the Wells here", "« Prova dei pozzi » inizia qui"},
    {"Start The Defias Brotherhood here", "« La Fratellanza dei Defias » inizia qui"},
    {"Start The Forgotten Pools here", "« Le pozze dimenticate » inizia qui"},
    {"southeast of Brill", "a sud-est di Brill"},
    {"Pools of Vision", "Pozze delle Visioni"},
    {"Sun Rock Retreat", "Rifugio Roccia del Sole"},
    {"Tinker Town", "Forgiatübi"},
    {"Darnassus", "Darnassus"},
    {"Apothecarium", "Spezieria"},
    {"by the bridge / vault entrance in", "vicino al ponte / ingresso della cripta a"},
    {"near the dungeon entrance", "vicino all’ingresso della spedizione"},
    {"after the first room", "dopo la prima stanza"},
    {"inside the dungeon", "dentro la spedizione"},
    {"just inside Ruins of Lordaeron", "appena dentro le Rovine di Lordaeron"},
    {"graveyard inside Ruins of Lordaeron", "cimitero nelle Rovine di Lordaeron"},
    {"%(%s*after Underground Map%s*%)", "(dopo «Mappa sotterranea»)"},
    {"above the entrance to", "sopra l’ingresso di"},
    {"left of the entrance", "a sinistra dell’ingresso"},
    {"Follow the quest directions beginning in", "Segui le indicazioni della missione iniziando da"},
    {"Stone tablet inside a vault in the Reliquary of Kings", "Tavoletta di pietra in una camera del Reliquiario dei Re"},
    {"Durgen Dirgehammer's room", "stanza di Durgen Dirgehammer"},
    {"Maur Grimtotem's corpse", "cadavere di Maur Totem Truce"},
    {"dropped by Dark Iron Spies", "lasciato cadere dalle Spie Ferroscuro"},
    {"Blackfathom Tide Priestesses", "Sacerdotesse delle Maree di Fondocupo"},
    {"taken from", "preso da"},
    {"dropped by", "lasciato da"},
    {"at Ironband's Compound", "all’Accampamento di Ironband"},
    {"Ironband's Compound", "Accampamento di Ironband"},
    {"Dark Iron Spies", "Spie Ferroscuro"},
    {"Northern Barrens", "Savane Settentrionali"},
    {"The Barrens", "Savane"},
    {"Cleft of Shadow", "Fenditura dell’Ombra"},
    {"Valley of Wisdom", "Valle della Saggezza"},
    {"Royal Quarter", "Quartiere Reale"},
    {"Elder Rise", "Altura degli Anziani"},
    {"Dwarven District", "Distretto dei Nani"},
    {"Cathedral Square", "Piazza della Cattedrale"},
    {"Old Town", "Città Vecchia"},
    {"Sentinel Hill tower", "torre di Colle Sentinella"},
    {"Sentinel Hill inn", "locanda di Colle Sentinella"},
    {"Sentinel Hill", "Colle Sentinella"},
    {"Stormwind City", "Roccavento"},
    {"Stormwind", "Roccavento"},
    {"Ironforge", "Forgiardente"},
    {"Thunder Bluff", "Picco del Tuono"},
    {"Undercity", "Sepulcra"},
    {"Silverpine Forest", "Selva Pinargento"},
    {"The Sepulcher", "Il Sepolcro"},
    {"Darkshore", "Rivafosca"},
    {"Ashenvale", "Valtetra"},
    {"Stonetalon Mountains", "Vette di Petrartiglio"},
    {"Redridge Mountains", "Montagne Crestarossa"},
    {"Zoram Strand", "Lido di Zoram"},
    {"Zoram'gar Outpost", "Avamposto di Zoram’gar"},
    {"Moonbrook", "Riva del Lago"},
    {"Ratchet", "Porto Paranco"},
    {"The Crossroads", "Il Crocevia"},
    {"Craftsmen's Terrace", "Terrazza degli Artigiani"},
    {"Forlorn Cavern", "Caverna Abbandonata"},
    {"Skull Rock", "Roccia del Teschio"},
    {"Gold Coast Quarry", "Cava della Costa d’Oro"},
    {"Jangolode Mine", "Miniera di Jango"},
    {"Lakeshire", "Borgolago"},
    {"The Park", "Il Parco"},
    {"Pyrewood Village", "Boscovespro"},
    {"inside Blackfathom Deeps", "negli Abissi di Fondocupo"},
    {"inside Shadowfang Keep", "nel Forte di Zannascura"},
    {"inside Ragefire Chasm", "nel Baratro di Fiamma Furente"},
    {"inside Ruins of Lordaeron", "nelle Rovine di Lordaeron"},
    {"inside Hall of Thanes", "nella Sala dei Thane"},
    {"inside the Deadmines", "nelle Miniere della Morte"},
    {"Wailing Caverns", "Caverna dei Lamenti"},
    {"Blackfathom Deeps", "Abissi di Fondocupo"},
    {"Shadowfang Keep", "Forte di Zannascura"},
    {"Ragefire Chasm", "Baratro di Fiamma Furente"},
    {"Ruins of Lordaeron", "Rovine di Lordaeron"},
    {"Hall of Thanes", "Sala dei Thane"},
    {"The Deadmines", "Le Miniere della Morte"},
    {"Deadmines", "Miniere della Morte"},
    {"Item start:", "Oggetto iniziale:"},
    {"Use ", "Usa "},
    {"Dropped by:", "Lasciato da:"},
    {"Looted from", "Ottenuto da"},
    {"Rare spawn.", "Spawn raro."},
    {"Quest Item", "Oggetto di missione"},
    {"Trash Drops", "Bottino trash"},
    {"Alliance", "Alleanza"},
    {"Horde", "Orda"},
    {"Both", "Entrambe"},
    {"Warlock", "Stregone"},
    {"Mage", "Mago"},
    {"Priest", "Sacerdote"},
    {"Rogue", "Ladro"},
    {"Warrior", "Guerriero"},
    {"Hunter", "Cacciatore"},
    {"Druid", "Druido"},
    {"Paladin", "Paladino"},
    {"Shaman", "Sciamano"},
}
