local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS

-- Simplified Chinese content localization (dungeon names and descriptions,
-- item slots). Quests and boss names fall back to English until translated.
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.zhCN = FDJ.ContentLocales.zhCN or {}

FDJ.ContentLocales.zhCN.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "领主之厅",
        ["location"] = "铁炉堡地下，丹莫罗",
        ["description"] = "有人闯入了铁炉堡地下的矮人王室墓室。",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "怒焰裂谷",
        ["location"] = "暗影裂口，奥格瑞玛",
        ["description"] = "穴居人和燃刃教徒盘踞在奥格瑞玛地下炽热的洞穴中。",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "洛丹伦废墟",
        ["location"] = "被毁的洛丹伦城",
        ["description"] = "天灾军团仍在这座废弃的都城中游荡，而一名死灵法师正在城中积蓄力量。",
    },
    ["The Deadmines"] = {
        ["name"] = "死亡矿井",
        ["location"] = "月溪镇，西部荒野",
        ["description"] = "迪菲亚兄弟会正在月溪镇下方的矿井中建造一艘战舰。",
    },
    ["Wailing Caverns"] = {
        ["name"] = "哀嚎洞穴",
        ["location"] = "北贫瘠之地",
        ["description"] = "在贫瘠之地深处，尖牙德鲁伊守护着沉睡的纳拉雷克斯，扭曲的野兽在洞穴中游荡。",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "影牙城堡",
        ["location"] = "银松森林",
        ["description"] = "大法师阿鲁高和他的狼人追随者占据了这座城堡。",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "黑暗深渊",
        ["location"] = "佐拉姆海岸，灰谷",
        ["description"] = "佐拉姆海岸一座被淹没的暗夜精灵遗迹，被纳迦、鱼人和效忠阿库麦尔的暮光之锤教徒占据。",
    },
    ["The Stockade"] = {
        ["name"] = "暴风城监狱",
        ["location"] = "暴风城",
        ["description"] = "暴乱的迪菲亚囚犯占领了暴风城的监狱。",
    },
}

FDJ.ContentLocales.zhCN.slotParts = {
    ["Chest"] = "胸部", ["Leather"] = "皮甲", ["Wrist"] = "手腕", ["Cloth"] = "布甲",
    ["Back"] = "背部", ["Waist"] = "腰部", ["Mail"] = "锁甲", ["Hands"] = "手",
    ["Feet"] = "脚", ["Legs"] = "腿部", ["Neck"] = "颈部", ["Finger"] = "手指",
    ["Trinket"] = "饰品", ["Bag"] = "背包", ["One-Hand"] = "单手", ["Main Hand"] = "主手",
    ["Off Hand"] = "副手", ["Two-Hand"] = "双手", ["Dagger"] = "匕首", ["Sword"] = "剑",
    ["Axe"] = "斧", ["Mace"] = "锤", ["Staff"] = "法杖", ["Shield"] = "盾牌",
    ["Polearm"] = "长柄武器", ["Ranged"] = "远程", ["Wand"] = "魔杖", ["Thrown"] = "投掷武器",
    ["Engineering"] = "工程学", ["Quest Item"] = "任务物品", ["Head"] = "头部", ["Shoulder"] = "肩部",
    ["Bow"] = "弓", ["Crossbow"] = "弩", ["Fist Weapon"] = "拳套",
    ["Leatherworking Recipe"] = "制皮配方", ["Held In Off-hand"] = "副手物品",
}

FDJ.ContentLocales.zhCN.bosses = {
    -- Official client names (Wowhead Forever database, 2026-10-03).
    ["Faldrim Anvilmar"] = "法德林·安威玛尔",
    ["Plunder"] = "劫掠者",
    ["Durgen Dirgehammer"] = "杜根·挽锤",
    ["Lord Cobrahn"] = "考布莱恩",
    ["Lady Anacondra"] = "安娜科德拉",
    ["Kresh"] = "克雷什",
    ["Lord Pythas"] = "皮萨斯",
    ["Skum"] = "斯卡姆",
    ["Lord Serpentis"] = "瑟芬迪斯",
    ["Verdan the Everliving"] = "永生者沃尔丹",
    ["Mutanus the Devourer"] = "吞噬者穆坦努斯",
    ["Deviate Faerie Dragon"] = "变异精灵龙",
    ["The Baron"] = "男爵",
    ["Witherfang"] = "枯牙",
    ["The Abandoned"] = "被遗弃者",
    ["Bjork"] = "比约克",
    ["Rath'mael"] = "拉斯玛尔",
    ["Viktor the Vile"] = "邪恶的维克多",
    ["Rhahk'Zor"] = "拉克佐",
    ["Miner Johnson"] = "矿工约翰森",
    ["Sneed's Shredder"] = "斯尼德的伐木机",
    ["Sneed"] = "斯尼德",
    ["Gilnid"] = "基尔尼格",
    ["Mr. Smite"] = "重拳先生",
    ["Captain Greenskin"] = "绿皮队长",
    ["Edwin VanCleef"] = "艾德温·范克里夫",
    ["Cookie"] = "曲奇",
    ["Ghamoo-ra"] = "加摩拉",
    ["Lady Sarevess"] = "萨利维丝",
    ["Gelihast"] = "格里哈斯特",
    ["Lorgus Jett"] = "洛古斯·杰特",
    ["Baron Aquanis"] = "阿奎尼斯男爵",
    ["Old Serra'kis"] = "瑟拉吉斯",
    ["Twilight Lord Kelris"] = "梦游者克尔里斯",
    ["Aku'mai"] = "阿库麦尔",
    ["Oggleflint"] = "奥格弗林特",
    ["Taragaman the Hungerer"] = "饥饿者塔拉加曼",
    ["Jergosh the Invoker"] = "祈求者耶戈什",
    ["Bazzalan"] = "巴扎兰",
    ["Rethilgore"] = "雷希戈尔",
    ["Fel Steed / Shadow Charger"] = "地狱战马 / 暗影军马",
    ["Razorclaw the Butcher"] = "屠夫拉佐克劳",
    ["Baron Silverlaine"] = "席瓦莱恩男爵",
    ["Commander Springvale"] = "指挥官斯普林瓦尔",
    ["Odo the Blindwatcher"] = "盲眼守卫奥杜",
    ["Deathsworn Captain"] = "死亡之誓",
    ["Arugal's Voidwalker"] = "阿鲁高的虚空行者",
    ["Fenrus the Devourer"] = "吞噬者芬鲁斯",
    ["Wolf Master Nandos"] = "狼王南杜斯",
    ["Archmage Arugal"] = "大法师阿鲁高",
    ["Targorr the Dread"] = "可怕的塔格尔",
    ["Kam Deepfury"] = "卡姆·深怒",
    ["Hamhock"] = "哈姆霍克",
    ["Dextren Ward"] = "迪克斯特·瓦德",
    ["Bazil Thredd"] = "巴基尔·斯瑞德",
    ["Bruegal Ironknuckle"] = "布鲁高·铁拳",
    ["Grubbis"] = "格鲁比斯",
    ["Viscous Fallout"] = "粘性辐射尘",
    ["Electrocutioner 6000"] = "电刑器6000型",
    ["Crowd Pummeler 9-60"] = "群体打击者9-60",
    ["Mekgineer Thermaplugg"] = "麦克尼尔·瑟玛普拉格",
    ["Dark Iron Ambassador"] = "黑铁大师",
    ["Roogug"] = "鲁古格",
    ["Aggem Thorncurse"] = "阿格姆",
    ["Death Speaker Jargba"] = "亡语者贾格巴",
    ["Overlord Ramtusk"] = "主宰拉姆塔斯",
    ["Agathelos the Raging"] = "暴怒的阿迦赛罗斯",
    ["Charlga Razorflank"] = "卡尔加·刺肋",
    ["Blind Hunter"] = "盲眼猎手",
    ["Earthcaller Halmgar"] = "唤地者哈穆加",
    ["Interrogator Vishas"] = "审讯员韦沙斯",
    ["Azshir the Sleepless"] = "永醒的艾希尔",
    ["Fallen Champion"] = "死灵勇士",
    ["Ironspine"] = "铁脊死灵",
    ["Bloodmage Thalnos"] = "血法师萨尔诺斯",
}
