local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS

-- Korean content localization (dungeon names and descriptions). Quests,
-- bosses and route steps fall back to English until translated.
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.koKR = FDJ.ContentLocales.koKR or {}

FDJ.ContentLocales.koKR.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "영주의 전당",
        ["location"] = "아이언포지 지하, 던 모로",
        ["description"] = "누군가 아이언포지 지하의 드워프 왕실 묘실에 침입했습니다.",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "성난불길 협곡",
        ["location"] = "어둠의 틈, 오그리마",
        ["description"] = "트로그와 불타는 칼날 교단원들이 오그리마 지하의 불타는 동굴에 들끓고 있습니다.",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "로데론의 폐허",
        ["location"] = "폐허가 된 로데론 도시",
        ["description"] = "스컬지 군대가 여전히 폐허가 된 수도를 떠돌고, 도시 안에서는 한 강령술사가 힘을 키우고 있습니다.",
    },
    ["The Deadmines"] = {
        ["name"] = "죽음의 폐광",
        ["location"] = "서부 몰락지대",
        ["description"] = "데피아즈단이 폐광 깊은 곳에서 전투선을 건조하고 있습니다.",
    },
    ["Wailing Caverns"] = {
        ["name"] = "통곡의 동굴",
        ["location"] = "불모의 땅",
        ["description"] = "불모의 땅 깊은 곳에서 송곳니 드루이드들이 잠든 나라렉스를 지키고, 뒤틀린 짐승들이 동굴을 배회합니다.",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "그림자송곳니 성채",
        ["location"] = "은빛소나무 숲",
        ["description"] = "대마법사 아루갈과 그의 늑대인간 추종자들이 성채를 장악하고 있습니다.",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "검은심연 나락",
        ["location"] = "조람 해안, 잿빛 골짜기",
        ["description"] = "나가, 멀록, 그리고 아쿠마이를 섬기는 황혼의 망치단이 점령한 물에 잠긴 나이트 엘프 유적입니다.",
    },
    ["The Stockade"] = {
        ["name"] = "스톰윈드 지하감옥",
        ["location"] = "스톰윈드",
        ["description"] = "폭동을 일으킨 데피아즈 죄수들이 스톰윈드의 감옥을 장악했습니다.",
    },
}

FDJ.ContentLocales.koKR.slotParts = {
    ["Chest"] = "가슴", ["Leather"] = "가죽", ["Wrist"] = "손목", ["Cloth"] = "천",
    ["Back"] = "등", ["Waist"] = "허리", ["Mail"] = "사슬", ["Hands"] = "손",
    ["Feet"] = "발", ["Legs"] = "다리", ["Neck"] = "목", ["Finger"] = "손가락",
    ["Trinket"] = "장신구", ["Bag"] = "가방", ["One-Hand"] = "한손", ["Main Hand"] = "주장비",
    ["Off Hand"] = "보조장비", ["Two-Hand"] = "양손", ["Dagger"] = "단검", ["Sword"] = "도검",
    ["Axe"] = "도끼", ["Mace"] = "둔기", ["Staff"] = "지팡이", ["Shield"] = "방패",
    ["Polearm"] = "장창", ["Ranged"] = "원거리", ["Wand"] = "마법봉", ["Thrown"] = "투척 무기",
    ["Engineering"] = "기계공학", ["Quest Item"] = "퀘스트 아이템", ["Head"] = "머리", ["Shoulder"] = "어깨",
    ["Bow"] = "활", ["Crossbow"] = "석궁", ["Fist Weapon"] = "장착 무기",
    ["Leatherworking Recipe"] = "가죽세공 도안", ["Held In Off-hand"] = "보조장비 착용",
}

FDJ.ContentLocales.koKR.bosses = {
    -- Official client names (Wowhead Forever database, 2026-10-03).
    ["Faldrim Anvilmar"] = "팔드림 앤빌마",
    ["Plunder"] = "약탈골렘",
    ["Durgen Dirgehammer"] = "드루겐 더지해머",
    ["Lord Cobrahn"] = "군주 코브란",
    ["Lady Anacondra"] = "여군주 아나콘드라",
    ["Kresh"] = "크레쉬",
    ["Lord Pythas"] = "군주 피타스",
    ["Skum"] = "스컴",
    ["Lord Serpentis"] = "군주 서펜티스",
    ["Verdan the Everliving"] = "영생의 베르단",
    ["Mutanus the Devourer"] = "걸신들린 무타누스",
    ["Deviate Faerie Dragon"] = "돌연변이 요정용",
    ["The Baron"] = "남작",
    ["Witherfang"] = "쇠퇴송곳니",
    ["The Abandoned"] = "버려진 자",
    ["Bjork"] = "비요크",
    ["Rath'mael"] = "라스마엘",
    ["Viktor the Vile"] = "비열한 빅토르",
    ["Rhahk'Zor"] = "라크조르",
    ["Miner Johnson"] = "광부 존슨",
    ["Sneed's Shredder"] = "스니드의 벌목기",
    ["Sneed"] = "스니드",
    ["Gilnid"] = "길니드",
    ["Mr. Smite"] = "미스터 스마이트",
    ["Captain Greenskin"] = "선장 그린스킨",
    ["Edwin VanCleef"] = "에드윈 밴클리프",
    ["Cookie"] = "쿠키",
    ["Ghamoo-ra"] = "가무라",
    ["Lady Sarevess"] = "여왕 사레베스",
    ["Gelihast"] = "겔리하스트",
    ["Lorgus Jett"] = "로구스 제트",
    ["Baron Aquanis"] = "군주 아쿠아니스",
    ["Old Serra'kis"] = "늙은 세라키스",
    ["Twilight Lord Kelris"] = "황혼의 군주 켈리스",
    ["Aku'mai"] = "아쿠마이",
    ["Oggleflint"] = "오글플린트",
    ["Taragaman the Hungerer"] = "욕망의 타라가만",
    ["Jergosh the Invoker"] = "기원사 제로쉬",
    ["Bazzalan"] = "바잘란",
    ["Rethilgore"] = "레실고어",
    ["Fel Steed / Shadow Charger"] = "지옥마 / 암흑마",
    ["Razorclaw the Butcher"] = "도살자 칼날발톱",
    ["Baron Silverlaine"] = "남작 실버레인",
    ["Commander Springvale"] = "사령관 스프링베일",
    ["Odo the Blindwatcher"] = "눈먼감시자 오도",
    ["Deathsworn Captain"] = "죽음의 경비대장",
    ["Arugal's Voidwalker"] = "아루갈의 보이드워커",
    ["Fenrus the Devourer"] = "파멸의 펜루스",
    ["Wolf Master Nandos"] = "늑대왕 난도스",
    ["Archmage Arugal"] = "대마법사 아루갈",
    ["Targorr the Dread"] = "흉악범 타고르",
    ["Kam Deepfury"] = "캄 딥퓨리",
    ["Hamhock"] = "햄혹",
    ["Dextren Ward"] = "덱스트렌 워드",
    ["Bazil Thredd"] = "바질 스레드",
    ["Bruegal Ironknuckle"] = "브루갈 아이언너클",
    ["Grubbis"] = "그루비스",
    ["Viscous Fallout"] = "방사성 폐기물",
    ["Electrocutioner 6000"] = "기계화 문지기 6000",
    ["Crowd Pummeler 9-60"] = "고철 압축기 9-60",
    ["Mekgineer Thermaplugg"] = "멕기니어 텔마플러그",
    ["Dark Iron Ambassador"] = "검은무쇠단 사절",
    ["Roogug"] = "루구그",
    ["Aggem Thorncurse"] = "저주의가시 아겜",
    ["Death Speaker Jargba"] = "죽음의예언자 잘그바",
    ["Overlord Ramtusk"] = "대군주 램터스크",
    ["Agathelos the Raging"] = "흉포한 아가테로스",
    ["Charlga Razorflank"] = "서슬깃 차를가",
    ["Blind Hunter"] = "눈먼사냥꾼",
    ["Earthcaller Halmgar"] = "대지의주술사 함가르",
    ["Interrogator Vishas"] = "심문관 비샤스",
    ["Azshir the Sleepless"] = "잠들지 않는 아즈쉬르",
    ["Fallen Champion"] = "타락한 용사",
    ["Ironspine"] = "무쇠해골",
    ["Bloodmage Thalnos"] = "혈법사 탈노스",
}
