local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS

-- German content localization. Internal database keys stay English so saved
-- selections, themes and lookup tables remain stable; only display text changes.
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.deDE = FDJ.ContentLocales.deDE or {}

FDJ.ContentLocales.deDE.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "Halle der Thane",
        ["location"] = "Unter Eisenschmiede, Dun Morogh",
        ["description"] = "Jemand ist in die königliche zwergische Grabkammer unter Eisenschmiede eingedrungen.",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "Der Flammenschlund",
        ["location"] = "Kluft der Schatten, Orgrimmar",
        ["description"] = "Troggs und Kultisten der Brennenden Klinge verseuchen die glühenden Höhlen unter Orgrimmar.",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "Ruinen von Lordaeron",
        ["location"] = "Die zerstörte Stadt Lordaeron",
        ["description"] = "Streitkräfte der Geißel suchen die zerstörte Hauptstadt noch immer heim, während ein Nekromant innerhalb der Stadt an Macht gewinnt.",
    },
    ["The Deadmines"] = {
        ["name"] = "Die Todesminen",
        ["location"] = "Mondbruch, Westfall",
        ["description"] = "Die Bruderschaft der Defias baut in den Minen unter Mondbruch ein Kriegsschiff.",
    },
    ["Wailing Caverns"] = {
        ["name"] = "Die Höhlen des Wehklagens",
        ["location"] = "Nördliches Brachland",
        ["description"] = "Tief unter dem Brachland bewachen Druiden und Giftzahnlords den schlafenden Naralex, während verdrehte Bestien durch die Höhlen streifen.",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "Burg Schattenfang",
        ["location"] = "Silberwald",
        ["description"] = "Erzmagier Arugal und seine Worgenanhänger halten die Burg oberhalb von Lohenscheit.",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "Tiefschwarze Grotte",
        ["location"] = "Zoramstrand, Eschental",
        ["description"] = "Eine überflutete Nachtelfenruine am Zoramstrand, besetzt von Naga, Murlocs und Kultisten des Schattenhammers im Dienst von Aku'mai.",
    },
    ["The Stockade"] = {
        ["name"] = "Das Verlies",
        ["location"] = "Stormwind",
        ["description"] = "Stormwinds Gefängnis wurde von aufständischen Defias-Gefangenen übernommen.",
    },
}

FDJ.ContentLocales.deDE.quests = {
    [386] = { ["name"] = "Wie man in den Wald hineinruft...", ["objective"] = "Tötet Targorr den Schrecklichen im Verlies und bringt seinen Kopf zu Wache Berton." },
    [377] = { ["name"] = "Verbrechen und Strafe", ["objective"] = "Tötet Dextren Ward im Verlies und bringt seine Hand zu Ratsherr Millstipe." },
    [387] = { ["name"] = "Niederschlagung des Aufstandes", ["objective"] = "Tötet 10 Defiasgefangene, 8 Defiassträflinge und 8 Defiasaufständische im Verlies." },
    [388] = { ["name"] = "Die Farbe von Blut", ["objective"] = "Sammelt 10 rote Wollkopftücher von den Defias im Verlies." },
    [378] = { ["name"] = "Tief empfundener Zorn", ["objective"] = "Tötet Kam Tiefenzorn im Verlies und bringt seinen Kopf zu Motley Garmason." },
    [391] = { ["name"] = "Aufstand im Verlies", ["objective"] = "Tötet Bazil Thredd im Verlies und bringt seinen Kopf zu Warden Thelwater." },
    [96395] = {
        ["name"] = "Ein alter Groll",
        ["objective"] = "Bringt den Geist von Faldrim Anvilmar zur Ruhe.",
    },
    [96403] = {
        ["name"] = "Wichtige Erbstücke",
        ["objective"] = "Sammelt 8 zwergische Erbstücke in der Halle der Thane.",
    },
    [96394] = {
        ["name"] = "Die ruhelosen Toten",
        ["objective"] = "Tötet 15 wütende Erscheinungen und 10 gequälte Seelen und bringt anschließend Anvilmars Geist zur Ruhe.",
    },
    [96393] = {
        ["name"] = "Vorstoß ins alte Eisenschmiede",
        ["objective"] = "Betretet die Halle der Thane und beschafft Durgen Düsterhammers Kopf.",
        ["note"] = "Die Questreihe beginnt mit der Dunkeleisenkarte, die von Dunkeleisenspionen in Dun Morogh fallen gelassen wird.",
    },
    [98423] = {
        ["name"] = "Der Vertrag der Verständigung",
        ["objective"] = "Bringt den Vertrag der Verständigung zu Magni Bronzebart in Eisenschmiede.",
        ["note"] = "Die Steintafel befindet sich in einem der Gewölbe im Reliquiar der Könige, in Durgen Düsterhammers letztem Bossraum. Öffnet die Gewölbe und interagiert mit der Tafel, bevor ihr den Dungeon verlasst.",
    },
    [1486] = {
        ["name"] = "Deviatbälge",
        ["objective"] = "Bringt Nalpak 20 Deviatbälge.",
    },
    [1491] = {
        ["name"] = "Kluge Getränke",
        ["objective"] = "Bringt Mebok Mizzyrix 6 Portionen Wehklagende Essenz.",
    },
    [959] = {
        ["name"] = "Ärger an den Docks",
        ["objective"] = "Beschafft den 99 Jahre alten Portwein von Mad Magglish in den Höhlen des Wehklagens.",
    },
    [1487] = {
        ["name"] = "Ausrottung der Deviat",
        ["objective"] = "Tötet 7 Deviatverheerer, 7 Deviatvipern, 7 Deviatschlurfer und 7 Deviatschreckenszähne.",
    },
    [6981] = {
        ["name"] = "Der leuchtende Splitter",
        ["objective"] = "Reist nach Ratschet, findet jemanden, der den leuchtenden Splitter identifizieren kann, und bringt ihn anschließend wie angewiesen weiter.",
        ["note"] = "Die direkte Quest hat keine Gegenstandsbelohnung. Die Folgequest „In Alpträumen“ bietet später:",
    },
    [914] = {
        ["name"] = "Anführer des Giftzahns",
        ["objective"] = "Bringt Nara Wildmähne die Edelsteine von Kobrahn, Anacondra, Pythas und Serpentis.",
        ["note"] = "Benötigt die Oasen-Questreihe im Brachland. Schließt „Die vergessenen Teiche“, „Die stagnierende Oase“ und „Veränderte Wesen“ ab und sprecht danach mit Hamuul Runentotem und Nara Wildmähne, bevor „Anführer des Giftzahns“ verfügbar wird.",
    },
    [962] = {
        ["name"] = "Schlangenflaum",
        ["objective"] = "Sammelt 10 Schlangenflaum in den Höhlen des Wehklagens.",
    },
    [95250] = {
        ["name"] = "Abscheuliche Kreaturen",
        ["objective"] = "Beschafft den Kopf des Barons in den Ruinen von Lordaeron.",
    },
    [97288] = {
        ["name"] = "Endlose Qual",
        ["objective"] = "Bringt den abscheulichen Kopf nach Unterstadt.",
        ["note"] = "Die Gegenstandsauswahl wird bei der Folgequest „Endlose Qual“ in Unterstadt vergeben.",
    },
    [92401] = {
        ["name"] = "Eine verängstigte Bitte",
        ["objective"] = "Untersucht das Verschwinden von Edward Heartweaver in den Ruinen von Lordaeron.",
    },
    [95195] = {
        ["name"] = "Blutbefleckte Insignie",
        ["objective"] = "Sammelt 10 blutbefleckte Insignien.",
    },
    [95189] = {
        ["name"] = "Wappen von Lordaeron",
        ["objective"] = "Bringt das Wappen von Lordaeron nach Sturmwind.",
        ["note"] = "Berichten aus der Community zufolge kann das Wappen an mehreren Stellen im Dungeon erscheinen, darunter obere Turmetagen, Seiten- oder Gruftkammern beim Baron sowie der Bereich um Bjork.",
    },
    [95204] = {
        ["name"] = "Wappen von Lordaeron",
        ["objective"] = "Bringt das Wappen von Lordaeron nach Unterstadt.",
        ["note"] = "Berichten aus der Community zufolge kann das Wappen an mehreren Stellen im Dungeon erscheinen, darunter obere Turmetagen, Seiten- oder Gruftkammern beim Baron sowie der Bereich um Bjork.",
    },
    [92421] = {
        ["name"] = "Gerechtigkeit des Lichts",
        ["objective"] = "Sammelt 25 intakte Gliedmaßen in den Ruinen von Lordaeron.",
    },
    [92415] = {
        ["name"] = "Denk daran, dass ich dich liebe",
        ["objective"] = "Bringt den blutbefleckten Brief zu Waisenmatrone Nachtigall.",
        ["note"] = "Diese Quest startet durch den Gegenstand „Blutbefleckter Brief“.",
    },
    [95216] = {
        ["name"] = "Die neue Seuche",
        ["objective"] = "Beschafft den hochgiftigen Stamm von Witherfang.",
    },
    [92422] = {
        ["name"] = "Rath'maels Zorn",
        ["objective"] = "Tötet Rath'mael in den Ruinen von Lordaeron.",
    },
    [214] = {
        ["name"] = "Rote Seidenkopftücher",
        ["objective"] = "Sammelt 10 rote Seidenkopftücher von Defias in den Todesminen.",
        ["note"] = "Benötigt den Eskortschritt der Bruderschaft der Defias.",
    },
    [168] = {
        ["name"] = "Erinnerungen sammeln",
        ["objective"] = "Sammelt 4 Gewerkschaftsausweise der Minenarbeiter von untoten Minenarbeitern in den Tunneln außerhalb der Instanz.",
        ["note"] = "Der untote Seitentunnel liegt vor dem Instanzportal.",
    },
    [92753] = {
        ["name"] = "Zerstörung in den Todesminen",
        ["objective"] = "Platziert den Sprengstoff neben der Schmiede in den Todesminen.",
    },
    [167] = {
        ["name"] = "Oh Bruder...",
        ["objective"] = "Beschafft Distelnessels Abzeichen von Vorarbeiter Distelnessel im untoten Seitentunnel.",
        ["note"] = "Der Vorarbeiter befindet sich in den Tunneln vor dem Instanzportal.",
    },
    [2040] = {
        ["name"] = "Angriff aus dem Untergrund",
        ["objective"] = "Beschafft das Gnoam-Sprecklesprocket von Sneeds Schredder.",
        ["note"] = "Folgt auf „Sprecht mit Shoni“.",
    },
    [166] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Besiegt Edwin van Cleef und beschafft seinen Kopf.",
        ["note"] = "Letzter Dungeonschritt der Questreihe „Die Bruderschaft der Defias“; schließt zuerst die vorherigen Schritte ab.",
    },
    [373] = {
        ["name"] = "Der nicht abgeschickte Brief",
        ["objective"] = "Bringt den Brief zum Stadtarchitekten in Sturmwind.",
        ["note"] = "Startet eine Folgequestreihe, die mit Bazil Thredd weitergeht.",
    },
    [971] = {
        ["name"] = "Wissen in der Tiefe",
        ["objective"] = "Beschafft das Manuskript von Lorgalis aus der Tiefschwarzen Grotte.",
        ["note"] = "Das Manuskript von Lorgalis befindet sich in einer beschädigten Eisenkiste unter Wasser im Teich von Ask'ar, in der nördlichen Nische direkt hinter Ghamoo-ras Schildkrötenraum.",
    },
    [1275] = {
        ["name"] = "Die Verderbnis erforschen",
        ["objective"] = "Sammelt 8 verderbte Hirnstämme von Kreaturen in der Tiefschwarzen Grotte.",
        ["note"] = "Folgt auf „Die Verderbnis in der Ferne“.",
    },
    [1198] = {
        ["name"] = "Auf der Suche nach Thaelrid",
        ["objective"] = "Findet Argentumwache Thaelrid in der Tiefschwarzen Grotte.",
    },
    [1199] = {
        ["name"] = "Wenn das Zwielicht fällt",
        ["objective"] = "Sammelt 10 Schattenhammeranhänger von Mitgliedern des Schattenhammers in der Tiefschwarzen Grotte.",
    },
    [1200] = {
        ["name"] = "Schurkerei in der Tiefschwarzen Grotte",
        ["objective"] = "Besiegt Schattenlord Kelris und beschafft den Kopf von Kelris.",
    },
    [6564] = {
        ["name"] = "Treue zu den Alten Göttern",
        ["objective"] = "Bringt die feuchte Notiz zu Je'neu Sancrea im Eschental.",
    },
    [6562] = {
        ["name"] = "Ärger in der Tiefe",
        ["objective"] = "Sprecht mit Je'neu Sancrea im Eschental.",
        ["note"] = "Einführungsschritt, der zu „Die Essenz von Aku'mai“ führt.",
    },
    [6563] = {
        ["name"] = "Die Essenz von Aku'mai",
        ["objective"] = "Sammelt 20 Saphire von Aku'mai in der Tiefschwarzen Grotte.",
        ["note"] = "Folgt auf „Ärger in der Tiefe“.",
    },
    [6565] = {
        ["name"] = "Treue zu den Alten Göttern",
        ["objective"] = "Besiegt Lorgus Jett in der Tiefschwarzen Grotte.",
        ["note"] = "Folgt auf die Version von „Treue zu den Alten Göttern“, die mit der feuchten Notiz beginnt.",
    },
    [6561] = {
        ["name"] = "Schurkerei in der Tiefschwarzen Grotte",
        ["objective"] = "Besiegt Schattenlord Kelris und beschafft den Kopf von Kelris.",
    },
    [6921] = {
        ["name"] = "Inmitten der Ruinen",
        ["objective"] = "Beschafft den Tiefenkern vom Tiefenstein in der Tiefschwarzen Grotte.",
        ["note"] = "Der Tiefenstein ist auch mit der optionalen Begegnung Baron Aquanis verbunden.",
    },
    [5723] = {
        ["name"] = "Die Stärke des Feindes testen",
        ["objective"] = "Tötet 8 Flammenschlundtroggs und 8 Flammenschlundschamanen im Flammenschlund.",
    },
    [5722] = {
        ["name"] = "Suche nach der verlorenen Tasche",
        ["objective"] = "Findet Maur Grimmtotems Leichnam im Flammenschlund und durchsucht ihn nach etwas Interessantem.",
    },
    [5724] = {
        ["name"] = "Die verlorene Tasche zurückbringen",
        ["objective"] = "Bringt die Grimmtotemtasche zu Rahauro in Donnerfels.",
    },
    [5728] = {
        ["name"] = "Verborgene Feinde",
        ["objective"] = "Tötet Bazzalan und Jergosh den Herbeirufer im Flammenschlund.",
        ["note"] = "Benötigt die früheren Schritte der Questreihe „Verborgene Feinde“ in Orgrimmar. Der nächste Schritt bietet später:",
    },
    [5761] = {
        ["name"] = "Die Bestie erschlagen",
        ["objective"] = "Tötet Taragaman den Hungerleider und beschafft Taragamans Herz.",
    },
    [5725] = {
        ["name"] = "Die Macht der Zerstörung...",
        ["objective"] = "Sammelt „Zauber des Schattens“ und „Beschwörungen aus dem Nether“ im Flammenschlund.",
    },
    [1098] = {
        ["name"] = "Todespirscher in Burg Schattenfang",
        ["objective"] = "Findet Todespirscher Adamant und Todespirscher Vincent in Burg Schattenfang.",
    },
    [1740] = {
        ["name"] = "Die Kugel von Soran'ruk",
        ["objective"] = "Findet 3 Fragmente von Soran'ruk und 1 großes Fragment von Soran'ruk und bringt sie zu Doan Karhan zurück.",
        ["note"] = "Hexenmeister-Klassenquest. Die Fragmente stammen aus Burg Schattenfang und der Tiefschwarzen Grotte.",
    },
    [1013] = {
        ["name"] = "Das Buch von Ur",
        ["objective"] = "Bringt Hüter Bel'dugur das Buch von Ur aus Burg Schattenfang.",
    },
    [1014] = {
        ["name"] = "Arugal muss sterben",
        ["objective"] = "Tötet Erzmagier Arugal und bringt seinen Kopf zu Dalar Morgenweber.",
        ["note"] = "Die aktuellen Forever-Questdaten führen außerdem „Arkane Intelligenz“ als erlernte Belohnung auf.",
    },
    [96391] = {
        ["name"] = "Unterirdische Karte",
        ["objective"] = "Bringt die Dunkeleisenkarte zu Erdseher Farsen in Dun Morogh.",
        ["description"] = "Die Dunkeleisenkarte startet diese Quest und führt direkt zu „Vorstoß ins alte Eisenschmiede“.",
    },
    [865] = {
        ["name"] = "Raptorhörner",
        ["objective"] = "Sammelt 5 intakte Raptorhörner von Sonnenschuppen-Sichelklauen und bringt sie zu Mebok Mizzyrix.",
        ["description"] = "Muss abgeschlossen werden, bevor „Kluge Getränke“ verfügbar wird.",
    },
    [870] = {
        ["name"] = "Die vergessenen Teiche",
        ["objective"] = "Erkundet das Wasser der vergessenen Teiche nordwestlich des Wegekreuzes und erstattet anschließend Bericht.",
        ["description"] = "Untersucht die Spalte unter den vergessenen Teichen.",
    },
    [877] = {
        ["name"] = "Die stagnierende Oase",
        ["objective"] = "Bringt die getrockneten Samen zur stagnierenden Oase, testet sie an der Spalte und kehrt danach zu Tonga zurück.",
        ["description"] = "Die nächste erforderliche Oasenuntersuchung nach „Die vergessenen Teiche“.",
    },
    [880] = {
        ["name"] = "Veränderte Wesen",
        ["objective"] = "Bringt Tonga Runentotem am Wegekreuz 8 veränderte Schnappkieferschildkrötenpanzer.",
        ["description"] = "Der Abschluss von „Veränderte Wesen“ schaltet „Hamuul Runentotem“ frei.",
    },
    [1489] = {
        ["name"] = "Hamuul Runentotem",
        ["objective"] = "Sprecht mit Hamuul Runentotem auf der Anhöhe der Ältesten in Donnerfels.",
        ["description"] = "Tonga schickt euch nach „Veränderte Wesen“ zu Hamuul.",
    },
    [1490] = {
        ["name"] = "Nara Wildmähne",
        ["objective"] = "Sprecht mit Nara Wildmähne in Donnerfels.",
        ["description"] = "Nara Wildmähne ist die letzte Voraussetzung, bevor „Anführer des Giftzahns“ verfügbar wird.",
    },
    [153] = {
        ["name"] = "Rote Lederkopftücher",
        ["objective"] = "Bringt Späher Galiaan an der Späherkuppe 15 rote Lederkopftücher.",
        ["description"] = "Muss vor „Rote Seidenkopftücher“ abgeschlossen werden.",
    },
    [65] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Sprecht mit Wiley dem Schwarzen in Seenhain.",
        ["description"] = "Erster Schritt der benötigten Questreihe „Die Bruderschaft der Defias“.",
    },
    [132] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Bringt Wileys Notiz zu Gryan Starkmantel in Westfall zurück.",
        ["description"] = "Zweiter Schritt der Questreihe „Die Bruderschaft der Defias“.",
    },
    [135] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Bringt Wileys Notiz zu Meister Mathias Shaw in Sturmwind.",
        ["description"] = "Shaw untersucht die Verbindung zwischen den Defias und den Steinmetzen.",
    },
    [141] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Bringt Shaws Bericht zu Gryan Starkmantel in Westfall.",
        ["description"] = "Bringt Shaws Erkenntnisse über Edwin van Cleef zu Gryan zurück.",
    },
    [142] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Spürt den Boten der Defias in Westfall auf und bringt seine Nachricht zu Gryan Starkmantel.",
        ["description"] = "Der Bote patrouilliert auf den Straßen zwischen Mondbruch, dem Steinbruch an der Goldküste und Jangoschacht.",
        ["note"] = "Der Bote der Defias patrouilliert auf den Straßen zwischen Mondbruch, dem Steinbruch an der Goldküste und Jangoschacht.",
    },
    [155] = {
        ["name"] = "Die Bruderschaft der Defias",
        ["objective"] = "Eskortiert den Verräter der Defias, bis er das Versteck der Defias enthüllt, und kehrt anschließend zu Gryan Starkmantel zurück.",
        ["description"] = "Letzte Voraussetzung vor dem Dungeonschritt von „Die Bruderschaft der Defias“.",
    },
    [2041] = {
        ["name"] = "Sprecht mit Shoni",
        ["objective"] = "Sprecht mit Shoni der Stillen in Sturmwind.",
        ["description"] = "Führt direkt zu „Angriff aus dem Untergrund“.",
    },
    [92742] = {
        ["name"] = "Die Brunnen testen",
        ["objective"] = "Benutzt das Brunnenwasser-Probeset an den Brunnen des Jansen-Hofs und der Molsen-Farm.",
        ["description"] = "Erste Quest der Questreihe „Giftiger Boden“.",
    },
    [92744] = {
        ["name"] = "Murlockiemen",
        ["objective"] = "Sammelt 7 Kiemen von Küstenmurlocs entlang der Küste von Westfall.",
        ["description"] = "Zweite Quest der Questreihe „Giftiger Boden“.",
    },
    [92745] = {
        ["name"] = "Der Zustand der Minen",
        ["objective"] = "Tötet 4 Koboldgräber in Jangoschacht und 6 Flusspfotenminenarbeiter im Steinbruch an der Goldküste.",
        ["description"] = "Untersucht, ob die Minen von Westfall die Verunreinigung verursachen.",
    },
    [92747] = {
        ["name"] = "Spionage in Mondbruch",
        ["objective"] = "Sammelt 8 verdächtige Industrievorräte in Mondbruch.",
        ["description"] = "Die Vorräte befinden sich in den Höhlen auf dem Weg zum Eingang der Todesminen.",
    },
    [92748] = {
        ["name"] = "Sprengstoffberatung",
        ["objective"] = "Reist in den Zwergendistrikt von Sturmwind und findet einen Ingenieur, der mit Sprengstoff helfen kann.",
        ["description"] = "Beginnt den Sprengstoffabschnitt der Questreihe „Giftiger Boden“.",
    },
    [92749] = {
        ["name"] = "Ein Dynamitplan",
        ["objective"] = "Beschafft 10 grobes Dynamit und kehrt anschließend zu Sprite Jumpsprocket in Sturmwind zurück.",
        ["description"] = "Grobes Dynamit kann hergestellt, gehandelt oder im Auktionshaus gekauft werden.",
        ["note"] = "Grobes Dynamit kann hergestellt, gehandelt oder im Auktionshaus gekauft werden.",
    },
    [92750] = {
        ["name"] = "Fernzündung",
        ["objective"] = "Sprecht mit dem Sturmwinder Geheimdienst über einen Fernzünder.",
        ["description"] = "Für die geplante Explosion wird ein Fernzünder benötigt.",
    },
    [92751] = {
        ["name"] = "Fernzündung",
        ["objective"] = "Bringt das Fernzünder-Set zurück zu Sprite Jumpsprocket im Zwergendistrikt.",
        ["description"] = "Bringt den Fernzünder zum Ingenieur zurück.",
    },
    [92752] = {
        ["name"] = "Sprengstoffberatung",
        ["objective"] = "Kehrt mit dem fertigen Sprengstoff zu Alba Fairmoon im Gasthaus der Späherkuppe in Westfall zurück.",
        ["description"] = "Letzte Vorbereitung vor „Zerstörung in den Todesminen“.",
    },
    [92819] = {
        ["name"] = "Zerstörung in den Todesminen",
        ["objective"] = "Benutzt den Zünder.",
        ["description"] = "Letzter Schritt der Questreihe „Giftiger Boden“.",
    },
    [5726] = {
        ["name"] = "Verborgene Feinde",
        ["objective"] = "Bringt Thrall eine Leutnantsinsignie der Brennenden Klinge aus dem Totenkopffelsen.",
        ["description"] = "Erster erforderlicher Schritt von „Verborgene Feinde“ für die Flammenschlund-Questreihe.",
    },
    [5727] = {
        ["name"] = "Verborgene Feinde",
        ["objective"] = "Sprecht mit Neeru Feuerklinge in der Kluft der Schatten und kehrt danach zu Thrall zurück.",
        ["description"] = "Neeru befindet sich in der Kluft der Schatten nahe dem Eingang zum Flammenschlund.",
    },
    [3765] = {
        ["name"] = "Die Verderbnis in der Ferne",
        ["objective"] = "Reist zu Gershala Nachtraunen in Auberdine an der Dunkelküste.",
        ["description"] = "Allianz-Zubringerquest, die vor „Die Verderbnis erforschen“ abgeschlossen werden muss.",
    },
}

FDJ.ContentLocales.deDE.bosses = {
    ["Trash Drops"] = "Trashbeute",
    ["Lordaeron Captain"] = "Hauptmann von Lordaeron",
    -- Official client names (Wowhead Forever database, 2026-10-03).
    ["Plunder"] = "Schleppweg",
    ["Lord Cobrahn"] = "Lord Kobrahn",
    ["Verdan the Everliving"] = "Verdan der Ewiglebende",
    ["Mutanus the Devourer"] = "Mutanus der Verschlinger",
    ["Deviate Faerie Dragon"] = "Deviatfeendrache",
    ["The Baron"] = "Der Baron",
    ["Witherfang"] = "Welkzahn",
    ["The Abandoned"] = "Der Verlassene",
    ["Viktor the Vile"] = "Viktor der Üble",
    ["Miner Johnson"] = "Minenarbeiter Johnson",
    ["Sneed's Shredder"] = "Sneeds Schredder",
    ["Edwin VanCleef"] = "Edwin van Cleef",
    ["Twilight Lord Kelris"] = "Twilight-Lord Kelris",
    ["Oggleflint"] = "Flintauge",
    ["Taragaman the Hungerer"] = "Taragaman der Hungerleider",
    ["Jergosh the Invoker"] = "Jergosh der Herbeirufer",
    ["Fel Steed / Shadow Charger"] = "Teufelsross / Schattenstürmer",
    ["Razorclaw the Butcher"] = "Klingenklaue der Metzger",
    ["Commander Springvale"] = "Kommandant Springvale",
    ["Odo the Blindwatcher"] = "Odo der Blindseher",
    ["Deathsworn Captain"] = "Todeshöriger Captain",
    ["Arugal's Voidwalker"] = "Arugals Leerwandler",
    ["Fenrus the Devourer"] = "Fenrus der Verschlinger",
    ["Wolf Master Nandos"] = "Wolfmeister Nandos",
    ["Archmage Arugal"] = "Erzmagier Arugal",
    ["Targorr the Dread"] = "Targorr der Schreckliche",
    ["Bruegal Ironknuckle"] = "Bruegal Eisenfaust",
    ["Relic Guardian"] = "Reliktwächter",
    ["Lyn the Ignored"] = "Lyn der Ignorierte",
    ["Shade of the Archmage"] = "Schemen des Erzmagiers",
    ["Viscous Fallout"] = "Verflüssigte Ablagerung",
    ["Electrocutioner 6000"] = "Elektrokutionator 6000",
    ["Crowd Pummeler 9-60"] = "Meute-Verprügler 9-60",
    ["Mekgineer Thermaplugg"] = "Robogenieur Thermaplugg",
    ["Dark Iron Ambassador"] = "Botschafter der Dunkeleisenzwerge",
    ["Aggem Thorncurse"] = "Aggem Dornfluch",
    ["Death Speaker Jargba"] = "Todessprecher Jargba",
    ["Overlord Ramtusk"] = "Oberanführer Rammhauer",
    ["Agathelos the Raging"] = "Agathelos der Tobende",
    ["Blind Hunter"] = "Blinder Jäger",
    ["Earthcaller Halmgar"] = "Erdenrufer Halmgar",
    ["Interrogator Vishas"] = "Befrager Vishas",
    ["Azshir the Sleepless"] = "Azshir der Schlaflose",
    ["Fallen Champion"] = "Gestürzter Held",
    ["Ironspine"] = "Eisenrücken",
    ["Bloodmage Thalnos"] = "Blutmagier Thalnos",
}

FDJ.ContentLocales.deDE.slotParts = {
    ["Chest"] = "Brust",
    ["Leather"] = "Leder",
    ["Wrist"] = "Handgelenke",
    ["Cloth"] = "Stoff",
    ["Back"] = "Rücken",
    ["Waist"] = "Taille",
    ["Mail"] = "Kette",
    ["Hands"] = "Hände",
    ["Feet"] = "Füße",
    ["Legs"] = "Beine",
    ["Neck"] = "Hals",
    ["Finger"] = "Finger",
    ["Trinket"] = "Schmuck",
    ["Bag"] = "Tasche",
    ["One-Hand"] = "Einhändig",
    ["Main Hand"] = "Waffenhand",
    ["Off Hand"] = "Schildhand",
    ["Two-Hand"] = "Zweihändig",
    ["Dagger"] = "Dolch",
    ["Sword"] = "Schwert",
    ["Axe"] = "Axt",
    ["Mace"] = "Streitkolben",
    ["Staff"] = "Stab",
    ["Shield"] = "Schild",
    ["Polearm"] = "Stangenwaffe",
    ["Ranged"] = "Distanz",
    ["Wand"] = "Zauberstab",
    ["Thrown"] = "Wurfwaffe",
    ["Engineering"] = "Ingenieurskunst",
    ["Quest Item"] = "Questgegenstand",
    ["Head"] = "Kopf",
    ["Shoulder"] = "Schulter",
    ["Bow"] = "Bogen",
    ["Crossbow"] = "Armbrust",
    ["Fist Weapon"] = "Faustwaffe",
    ["Leatherworking Recipe"] = "Lederverarbeitungsrezept",
    ["Held In Off-hand"] = "In Schildhand getragen",
}

FDJ.ContentLocales.deDE.replacements = {
    {"Farm Dark Iron Spies here for the Dark Iron Map", "Farmt hier Dunkeleisenspione für die Dunkeleisenkarte"},
    {"Dark Iron Map drops from Dark Iron Spies around Ironband's Compound", "Die Dunkeleisenkarte wird von Dunkeleisenspionen rund um Eisenbands Lager fallen gelassen"},
    {"Alba Fairmoon is inside the Sentinel Hill inn", "Alba Fairmoon befindet sich in der Taverne am Späherkuppe"},
    {"Argos Nightwhisper is in The Park, beside the moonwell area.", "Argos Nachtflüsterer befindet sich im Park neben dem Mondbrunnen."},
    {"Serpentbloom starts from Apothecary Zamah in the Pools of Vision beneath Spirit Rise", "Schlangenflaum beginnt bei Apothekerin Zamah in den Teichen der Visionen unter der Anhöhe der Geister"},
    {"Start Hidden Enemies here", "Hier beginnt „Verborgene Feinde“"},
    {"Start In Search of Thaelrid here", "Hier beginnt „Auf der Suche nach Thaelrid“"},
    {"Start Raptor Horns here", "Hier beginnt „Raptorhörner“"},
    {"Start Red Leather Bandanas here", "Hier beginnt „Rote Lederkopftücher“"},
    {"Start Speak with Shoni here", "Hier beginnt „Sprecht mit Shoni“"},
    {"Start Testing the Wells here", "Hier beginnt „Die Brunnen testen“"},
    {"Start The Defias Brotherhood here", "Hier beginnt „Die Bruderschaft der Defias“"},
    {"Start The Forgotten Pools here", "Hier beginnt „Die vergessenen Teiche“"},
    {"southeast of Brill", "südöstlich von Brill"},
    {"Pools of Vision", "Teiche der Visionen"},
    {"Sun Rock Retreat", "Sonnenfels"},
    {"Tinker Town", "Tüftlerstadt"},
    {"Darnassus", "Darnassus"},
    {"Apothecarium", "Apothecarium"},
    -- Direction/location phrases used by Starts at / Turn in / map tooltips.
    {"by the bridge / vault entrance in", "an der Brücke / am Eingang zum Gewölbe in"},
    {"near the dungeon entrance", "nahe dem Dungeoneingang"},
    {"after the first room", "nach dem ersten Raum"},
    {"inside the dungeon", "im Dungeon"},
    {"just inside Ruins of Lordaeron", "direkt in den Ruinen von Lordaeron"},
    {"graveyard inside Ruins of Lordaeron", "Friedhof in den Ruinen von Lordaeron"},
    {"%(%s*after Underground Map%s*%)", "(nach „Unterirdische Karte“)"},
    {"above the entrance to", "oberhalb des Eingangs zu"},
    {"left of the entrance", "links vom Eingang"},
    {"Follow the quest directions beginning in", "Folgt den Questanweisungen, beginnend in"},
    {"Stone tablet inside a vault in the Reliquary of Kings", "Steintafel in einem Gewölbe im Reliquiar der Könige"},
    {"Durgen Dirgehammer's room", "Durgen Düsterhammers Raum"},
    {"Use the Extra%-Destructive Explosives quest%-start item%.", "Benutzt den Queststartgegenstand Extra-Destructive Explosives."},
    {"Use An Unsent Letter, looted from Edwin VanCleef%.", "Benutzt An Unsent Letter, erbeutet von Edwin VanCleef."},
    {"Use the Damp Note dropped by Blackfathom Tide Priestesses", "Benutzt die Damp Note, die von Blackfathom Tide Priestesses fallen gelassen wird"},
    {"Extra%-Destructive Explosives quest%-start item", "Queststartgegenstand Extra-Destructive Explosives"},
    {"Maur Grimtotem's corpse", "Maur Grimmtotems Leiche"},
    {"From the first major three%-way junction, take the right%-hand tunnel, follow it uphill toward the dead end, then enter the small side room on the left%. Interact with Maur's corpse there%.", "Nehmt an der ersten großen Dreiwegekreuzung den rechten Tunnel, folgt ihm bergauf bis zur Sackgasse und betretet dann den kleinen Seitenraum links. Interagiert dort mit Maur Grimmtotems Leiche."},
    {"dropped by Dark Iron Spies", "von Dunkeleisenspionen fallen gelassen"},
    {"Blackfathom Tide Priestesses", "Gezeitenpriesterinnen der Tiefschwarzen Grotte"},
    {"taken from", "genommen von"},
    {"dropped by", "fallen gelassen von"},
    {"at Ironband's Compound", "bei Eisenbands Lager"},
    {"Ironband's Compound", "Eisenbands Lager"},
    {"Dark Iron Spies", "Dunkeleisenspione"},
    {"Farm Dunkeleisenspione here for the Dark Iron Map", "Hier Dunkeleisenspione für die Dunkeleisenkarte besiegen"},
    {"Start Testing the Wells here", "Hier beginnt „Die Brunnen testen“"},
    {"Start Raptor Horns here", "Hier beginnt „Raptorhörner“"},
    {"Start The Forgotten Pools here", "Hier beginnt „Die vergessenen Teiche“"},
    {"Start Red Leather Bandanas here", "Hier beginnt „Rote Lederkopftücher“"},
    {"Start The Defias Brotherhood here", "Hier beginnt „Die Bruderschaft der Defias“"},
    {"Start Speak with Shoni here", "Hier beginnt „Sprecht mit Shoni“"},
    {"Start Hidden Enemies here", "Hier beginnt „Verborgene Feinde“"},
    {"Start In Search of Thaelrid here", "Hier beginnt „Auf der Suche nach Thaelrid“"},
    {"Serpentbloom starts from Apothecary Zamah in the Pools of Vision beneath Spirit Rise", "„Schlangenflaum“ beginnt bei Apothekerin Zamah in den Teichen der Visionen unter der Geisterhöhe"},
    {"Argos Nightwhisper is in The Park, beside the moonwell area%.", "Argos Nightwhisper befindet sich im Park neben dem Mondbrunnen."},
    {"is inside the Sentinel Hill inn", "befindet sich im Gasthaus an der Späherkuppe"},
    {"southeast of Brill", "südöstlich von Brill"},
    {"beside the moonwell area", "neben dem Mondbrunnen"},
    {"Pools of Vision", "Teiche der Visionen"},
    {"beneath Spirit Rise", "unter der Geisterhöhe"},
    {"Sun Rock Retreat", "Sonnenfels"},
    {"Tinker Town", "Tüftlerstadt"},
    {"City Hall", "Rathaus"},
    {"the Dwarven District", "den Zwergendistrikt"},
    {"the dungeon entrance", "dem Dungeoneingang"},
    -- Common NPC/title names that are otherwise hard-coded English.
    {"Ghostly Attendant", "Geisterhafter Diener"},
    {"Earthseer Farsen", "Erdenseher Farsen"},
    {"King Magni Bronzebeard", "König Magni Bronzebart"},
    {"Crane Operator Bigglefuzz", "Kranführer Moppelfuzz"},
    {"Apothecary Zamah", "Apothekerin Zamah"},
    {"High Executor Hadrec", "Hochexekutor Hadrec"},
    {"Deathguard Kristof", "Todeswache Kristof"},
    {"Keeper Bel'dugur", "Bewahrer Bel'dugur"},
    {"Argent Guard Thaelrid", "Argentumwache Thaelrid"},
    {"Argent Guard Manados", "Argentumwache Manados"},
    {"Dawnwatcher Shaedlass", "Dämmerungswächter Shaedlass"},
    {"Dawnwatcher Selgorm", "Dämmerungswächter Selgorm"},
    {"Master Apothecary Faranell", "Meisterapotheker Faranell"},
    {"General Marcus Jonathan", "General Marcus Jonathan"},
    {"Orphan Matron Nightingale", "Waisenmatrone Nachtigall"},
    {"Northern Barrens", "Nördliches Brachland"},
    {"The Barrens", "Brachland"},
    {"Cleft of Shadow", "Kluft der Schatten"},
    {"Valley of Wisdom", "Tal der Weisheit"},
    {"Royal Quarter", "Königliches Viertel"},
    {"Elder Rise", "Anhöhe der Ältesten"},
    {"Dwarven District", "Zwergendistrikt"},
    {"Cathedral Square", "Kathedralenplatz"},
    {"Old Town", "Altstadt"},
    {"Sentinel Hill tower", "Turm an der Späherkuppe"},
    {"Sentinel Hill inn", "Gasthaus an der Späherkuppe"},
    {"Sentinel Hill", "Späherkuppe"},
    {"Stormwind City", "Sturmwind"},
    {"Stormwind", "Sturmwind"},
    {"Ironforge", "Eisenschmiede"},
    {"Thunder Bluff", "Donnerfels"},
    {"Undercity", "Unterstadt"},
    {"Silverpine Forest", "Silberwald"},
    {"The Sepulcher", "Das Grabmal"},
    {"Darkshore", "Dunkelküste"},
    {"Ashenvale", "Eschental"},
    {"Stonetalon Mountains", "Steinkrallengebirge"},
    {"Redridge Mountains", "Rotkammgebirge"},
    {"Zoram Strand", "Zoramstrand"},
    {"Zoram'gar Outpost", "Außenposten von Zoram'gar"},
    {"Moonbrook", "Mondbruch"},
    {"Ratchet", "Ratschet"},
    {"The Crossroads", "Das Wegekreuz"},
    {"Craftsmen's Terrace", "Terrasse der Handwerker"},
    {"Forlorn Cavern", "Verlassene Höhle"},
    {"Skull Rock", "Totenkopffelsen"},
    {"Gold Coast Quarry", "Steinbruch an der Goldküste"},
    {"Jangolode Mine", "Jangoschacht"},
    {"Lakeshire", "Seenhain"},
    {"The Park", "Der Park"},
    {"Pyrewood Village", "Lohenscheit"},
    {"inside Blackfathom Deeps", "in der Tiefschwarzen Grotte"},
    {"inside Shadowfang Keep", "in Burg Schattenfang"},
    {"inside Ragefire Chasm", "im Flammenschlund"},
    {"inside Ruins of Lordaeron", "in den Ruinen von Lordaeron"},
    {"inside Hall of Thanes", "in der Halle der Thane"},
    {"inside the Deadmines", "in den Todesminen"},
    {"Wailing Caverns", "Höhlen des Wehklagens"},
    {"Blackfathom Deeps", "Tiefschwarze Grotte"},
    {"Shadowfang Keep", "Burg Schattenfang"},
    {"Ragefire Chasm", "Flammenschlund"},
    {"Ruins of Lordaeron", "Ruinen von Lordaeron"},
    {"Hall of Thanes", "Halle der Thane"},
    {"The Deadmines", "Die Todesminen"},
    {"Deadmines", "Todesminen"},
    {"Item start:", "Queststart-Gegenstand:"},
    {"Use ", "Benutzt "},
    {"Dropped by:", "Fällt bei:"},
    {"Looted from", "Erbeutet von"},
    {"Rare spawn.", "Seltener Spawn."},
    {"Quest Item", "Questgegenstand"},
    {"Trash Drops", "Trashbeute"},
    {"Alliance", "Allianz"},
    {"Horde", "Horde"},
    {"Both", "Beide"},
    {"Warlock", "Hexenmeister"},
    {"Mage", "Magier"},
    {"Priest", "Priester"},
    {"Rogue", "Schurke"},
    {"Warrior", "Krieger"},
    {"Hunter", "Jäger"},
    {"Druid", "Druide"},
    {"Paladin", "Paladin"},
    {"Shaman", "Schamane"},
}
