local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS

-- Traditional Chinese (Taiwan) content, converted from zhCN with zhTW terms.
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.zhTW = FDJ.ContentLocales.zhTW or {}

FDJ.ContentLocales.zhTW.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "領主之廳",
        ["location"] = "鐵爐堡地下，丹莫洛",
        ["description"] = "有人闖入了鐵爐堡地下的矮人王室墓室。",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "怒焰裂谷",
        ["location"] = "暗影裂口，奧格瑪",
        ["description"] = "穴居人和燃刃教徒盤踞在奧格瑪地下熾熱的洞穴中。",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "洛丹倫廢墟",
        ["location"] = "被毀的洛丹倫城",
        ["description"] = "天災軍團仍在這座廢棄的都城中游蕩，而一名死靈法師正在城中積蓄力量。",
    },
    ["The Deadmines"] = {
        ["name"] = "死亡礦坑",
        ["location"] = "月溪鎮，西部荒野",
        ["description"] = "迪菲亞兄弟會正在月溪鎮下方的礦井中建造一艘戰艦。",
    },
    ["Wailing Caverns"] = {
        ["name"] = "哀嚎洞穴",
        ["location"] = "北貧瘠之地",
        ["description"] = "在貧瘠之地深處，尖牙德魯伊守護著沉睡的納拉雷克斯，扭曲的野獸在洞穴中游蕩。",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "影牙城堡",
        ["location"] = "銀松森林",
        ["description"] = "大法師阿魯高和他的狼人追隨者佔據了這座城堡。",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "黑暗深淵",
        ["location"] = "佐拉姆海岸，灰谷",
        ["description"] = "佐拉姆海岸一座被淹沒的暗夜精靈遺蹟，被納迦、魚人和效忠阿庫麥爾的暮光之錘教徒佔據。",
    },
    ["The Stockade"] = {
        ["name"] = "暴風城監獄",
        ["location"] = "暴風城",
        ["description"] = "暴亂的迪菲亞囚犯佔領了暴風城的監獄。",
    },
}

FDJ.ContentLocales.zhTW.slotParts = {
    ["Chest"] = "胸部", ["Leather"] = "皮甲", ["Wrist"] = "手腕", ["Cloth"] = "布甲",
    ["Back"] = "背部", ["Waist"] = "腰部", ["Mail"] = "鎖甲", ["Hands"] = "手",
    ["Feet"] = "腳", ["Legs"] = "腿部", ["Neck"] = "頸部", ["Finger"] = "手指",
    ["Trinket"] = "飾品", ["Bag"] = "揹包", ["One-Hand"] = "單手", ["Main Hand"] = "主手",
    ["Off Hand"] = "副手", ["Two-Hand"] = "雙手", ["Dagger"] = "匕首", ["Sword"] = "劍",
    ["Axe"] = "斧", ["Mace"] = "錘", ["Staff"] = "法杖", ["Shield"] = "盾牌",
    ["Polearm"] = "長柄武器", ["Ranged"] = "遠端", ["Wand"] = "魔杖", ["Thrown"] = "投擲武器",
    ["Engineering"] = "工程學", ["Quest Item"] = "任務物品", ["Head"] = "頭部", ["Shoulder"] = "肩部",
    ["Bow"] = "弓", ["Crossbow"] = "弩", ["Fist Weapon"] = "拳套",
    ["Leatherworking Recipe"] = "制皮配方", ["Held In Off-hand"] = "副手物品",
}

FDJ.ContentLocales.zhTW.bosses = {
    -- Official client names (Wowhead Forever database, 2026-10-03).
    ["Lord Cobrahn"] = "考布萊恩",
    ["Lady Anacondra"] = "安娜科德拉",
    ["Kresh"] = "克雷什",
    ["Lord Pythas"] = "皮薩斯",
    ["Skum"] = "斯卡姆",
    ["Lord Serpentis"] = "瑟芬迪斯",
    ["Verdan the Everliving"] = "永生者沃爾丹",
    ["Mutanus the Devourer"] = "吞噬者穆坦努斯",
    ["Deviate Faerie Dragon"] = "變異精靈龍",
    ["Rhahk'Zor"] = "拉克佐",
    ["Miner Johnson"] = "礦工約翰森",
    ["Sneed's Shredder"] = "斯尼德的伐木機",
    ["Sneed"] = "斯尼德",
    ["Gilnid"] = "基爾尼格",
    ["Mr. Smite"] = "重拳先生",
    ["Captain Greenskin"] = "綠皮隊長",
    ["Edwin VanCleef"] = "艾德溫·范克里夫",
    ["Cookie"] = "曲奇",
    ["Ghamoo-ra"] = "加摩拉",
    ["Lady Sarevess"] = "薩利維絲",
    ["Gelihast"] = "格里哈斯特",
    ["Lorgus Jett"] = "洛古斯·傑特",
    ["Baron Aquanis"] = "阿奎尼斯男爵",
    ["Old Serra'kis"] = "瑟拉吉斯",
    ["Twilight Lord Kelris"] = "夢遊者克爾里斯",
    ["Aku'mai"] = "阿庫麥爾",
    ["Oggleflint"] = "奧格弗林特",
    ["Taragaman the Hungerer"] = "饑餓者塔拉加曼",
    ["Jergosh the Invoker"] = "祈求者耶戈什",
    ["Bazzalan"] = "巴札蘭",
    ["Rethilgore"] = "雷希戈爾",
    ["Fel Steed / Shadow Charger"] = "地獄戰馬 / 暗影戰馬",
    ["Razorclaw the Butcher"] = "屠夫拉佐克勞",
    ["Baron Silverlaine"] = "席瓦萊恩男爵",
    ["Commander Springvale"] = "指揮官斯普林瓦爾",
    ["Odo the Blindwatcher"] = "盲眼守衛奧杜",
    ["Deathsworn Captain"] = "死亡之誓",
    ["Arugal's Voidwalker"] = "阿魯高的虛空行者",
    ["Fenrus the Devourer"] = "吞噬者芬魯斯",
    ["Wolf Master Nandos"] = "狼王南杜斯",
    ["Archmage Arugal"] = "大法師阿魯高",
    ["Targorr the Dread"] = "可怕的塔高爾",
    ["Kam Deepfury"] = "卡姆·深怒",
    ["Hamhock"] = "哈姆霍克",
    ["Dextren Ward"] = "迪克斯特·瓦德",
    ["Bazil Thredd"] = "巴基爾·斯瑞德",
    ["Bruegal Ironknuckle"] = "布魯戈·艾爾克納寇",
    ["Grubbis"] = "格魯比斯",
    ["Viscous Fallout"] = "粘性輻射塵",
    ["Electrocutioner 6000"] = "電刑器6000型",
    ["Crowd Pummeler 9-60"] = "群體打擊者9-60",
    ["Mekgineer Thermaplugg"] = "麥克尼爾·瑟瑪普拉格",
    ["Dark Iron Ambassador"] = "黑鐵大師",
    ["Roogug"] = "魯古格",
    ["Aggem Thorncurse"] = "阿格姆",
    ["Death Speaker Jargba"] = "亡語者賈格巴",
    ["Overlord Ramtusk"] = "主宰拉姆塔斯",
    ["Agathelos the Raging"] = "暴怒的阿迦賽羅斯",
    ["Charlga Razorflank"] = "卡爾加·刺肋",
    ["Blind Hunter"] = "盲眼獵手",
    ["Earthcaller Halmgar"] = "喚地者哈穆加",
    ["Interrogator Vishas"] = "審訊員韋沙斯",
    ["Azshir the Sleepless"] = "永醒的艾希爾",
    ["Fallen Champion"] = "死靈勇士",
    ["Ironspine"] = "鐵脊死靈",
    ["Bloodmage Thalnos"] = "血法師薩爾諾斯",
}
