local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.frFR = FDJ.ContentLocales.frFR or {}

FDJ.ContentLocales.frFR.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "Salle des thanes",
        ["location"] = "Sous Forgefer, Dun Morogh",
        ["description"] = "Quelqu’un s’est introduit dans la crypte royale naine sous Forgefer.",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "Gouffre de Ragefeu",
        ["location"] = "Faille de l’Ombre, Orgrimmar",
        ["description"] = "Des troggs et des cultistes de la Lame ardente infestent les cavernes brûlantes sous Orgrimmar.",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "Ruines de Lordaeron",
        ["location"] = "La cité en ruines de Lordaeron",
        ["description"] = "Les forces du Fléau hantent encore l’ancienne capitale tandis qu’un nécromancien gagne en puissance au cœur des ruines.",
    },
    ["The Deadmines"] = {
        ["name"] = "Les Mortemines",
        ["location"] = "Ruisselune, Marche de l’Ouest",
        ["description"] = "La Confrérie défias construit un navire de guerre dans les mines sous Ruisselune.",
    },
    ["Wailing Caverns"] = {
        ["name"] = "Cavernes des lamentations",
        ["location"] = "Tarides du Nord",
        ["description"] = "Sous les Tarides, des druides et des seigneurs du Croc gardent Naralex endormi tandis que des créatures corrompues rôdent dans les cavernes.",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "Donjon d’Ombrecroc",
        ["location"] = "Forêt des Pins-Argentés",
        ["description"] = "L’archimage Arugal et ses serviteurs worgens occupent le donjon au-dessus de Bois-du-Bûcher.",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "Profondeurs de Brassenoire",
        ["location"] = "Grève de Zoram, Orneval",
        ["description"] = "Une ruine kaldorei inondée sur la grève de Zoram, occupée par des nagas, des murlocs et des sectateurs du Marteau du crépuscule au service d’Aku’mai.",
    },
    ["The Stockade"] = {
        ["name"] = "La Prison",
        ["location"] = "Hurlevent",
        ["description"] = "Les prisonniers défias ont pris le contrôle de la prison de Hurlevent.",
    },
}

FDJ.ContentLocales.frFR.quests = {
    [386] = { ["name"] = "Un prêté pour un rendu...", ["objective"] = "Tuez Targorr le Terrible dans la Prison et rapportez sa tête au garde Berton." },
    [377] = { ["name"] = "Crime et châtiment", ["objective"] = "Tuez Dextren Ward dans la Prison et rapportez sa main au conseiller Millstipe." },
    [387] = { ["name"] = "Mater la révolte", ["objective"] = "Tuez 10 prisonniers défias, 8 condamnés défias et 8 insurgés défias dans la Prison." },
    [388] = { ["name"] = "La couleur du sang", ["objective"] = "Récupérez 10 bandanas de laine rouge sur les Défias dans la Prison." },
    [378] = { ["name"] = "La fureur gronde", ["objective"] = "Tuez Kam Deepfury dans la Prison et rapportez sa tête à Motley Garmason." },
    [391] = { ["name"] = "Les émeutes de la Prison", ["objective"] = "Tuez Bazil Thredd dans la Prison et rapportez sa tête au gardien Thelwater." },
    [96395] = {
        ["name"] = "Une vieille rancune",
        ["objective"] = "Apaisez l’esprit de Faldrim Anvilmar.",
    },
    [96403] = {
        ["name"] = "Héritages importants",
        ["objective"] = "Récupérez 8 héritages nains dans la Salle des thanes.",
    },
    [96394] = {
        ["name"] = "Les morts sans repos",
        ["objective"] = "Tuez 15 apparitions enragées et 10 âmes tourmentées, puis apaisez l’esprit d’Anvilmar.",
    },
    [96393] = {
        ["name"] = "Incursion dans l’ancienne Forgefer",
        ["objective"] = "Entrez dans la Salle des thanes et récupérez la tête de Durgen Dirgehammer.",
        ["note"] = "La suite commence avec la Carte des Sombrefers, obtenue sur les espions Sombrefers de Dun Morogh.",
    },
    [98423] = {
        ["name"] = "Le traité d’entente",
        ["objective"] = "Apportez le traité d’entente à Magni Barbe-de-Bronze à Forgefer.",
        ["note"] = "La tablette de pierre se trouve dans l’un des caveaux du Reliquaire des rois, dans la dernière salle de Durgen Dirgehammer. Ouvrez les caveaux et interagissez avec la tablette avant de quitter le donjon.",
    },
    [1486] = {
        ["name"] = "Peaux de déviant",
        ["objective"] = "Apportez 20 peaux de déviant à Nalpak.",
    },
    [1491] = {
        ["name"] = "Breuvages intelligents",
        ["objective"] = "Apportez 6 essences des lamentations à Mebok Mizzyrix.",
    },
    [959] = {
        ["name"] = "Problèmes sur les quais",
        ["objective"] = "Récupérez le porto de 99 ans de Mad Magglish dans les Cavernes des lamentations.",
    },
    [1487] = {
        ["name"] = "Éradication des déviants",
        ["objective"] = "Tuez 7 ravageurs déviants, 7 vipères déviantes, 7 rampants déviants et 7 crocs-d’effroi déviants.",
    },
    [6981] = {
        ["name"] = "L’éclat luminescent",
        ["objective"] = "Rendez-vous à Cabestan, trouvez quelqu’un capable d’identifier l’éclat luminescent puis apportez-le à la personne indiquée.",
        ["note"] = "Cette quête ne donne pas directement d’objet. La quête suivante, « Dans les cauchemars », propose plus tard :",
    },
    [914] = {
        ["name"] = "Les dirigeants du Croc",
        ["objective"] = "Apportez à Nara Crin-sauvage les gemmes de Kobrahn, Anacondra, Pythas et Serpentis.",
        ["note"] = "Nécessite la suite des oasis dans les Tarides. Terminez « Les bassins oubliés », « L’oasis stagnante » et « Êtres altérés », puis parlez à Hamuul Totem-runique et à Nara Crin-sauvage avant que « Les dirigeants du Croc » soit disponible.",
    },
    [962] = {
        ["name"] = "Fleur de serpent",
        ["objective"] = "Récupérez 10 fleurs de serpent dans les Cavernes des lamentations.",
    },
    [95250] = {
        ["name"] = "Créatures abominables",
        ["objective"] = "Récupérez la tête du Baron dans les Ruines de Lordaeron.",
    },
    [97288] = {
        ["name"] = "Tourment sans fin",
        ["objective"] = "Apportez la tête abominable à Fossoyeuse.",
        ["note"] = "Le choix d’objet est accordé lors de la quête suivante « Tourment sans fin » à Fossoyeuse.",
    },
    [92401] = {
        ["name"] = "Une requête terrifiée",
        ["objective"] = "Enquêtez sur la disparition d’Edward Heartweaver dans les Ruines de Lordaeron.",
    },
    [95195] = {
        ["name"] = "Insigne ensanglanté",
        ["objective"] = "Récupérez 10 insignes ensanglantés.",
    },
    [95189] = {
        ["name"] = "Blason de Lordaeron",
        ["objective"] = "Apportez le blason de Lordaeron à Hurlevent.",
        ["note"] = "Les signalements de joueurs indiquent que le blason peut apparaître à plusieurs endroits du donjon, notamment aux étages supérieurs des tours, dans des salles latérales ou des cryptes près du Baron et dans la zone de Bjork.",
    },
    [95204] = {
        ["name"] = "Blason de Lordaeron",
        ["objective"] = "Apportez le blason de Lordaeron à Fossoyeuse.",
        ["note"] = "Les signalements de joueurs indiquent que le blason peut apparaître à plusieurs endroits du donjon, notamment aux étages supérieurs des tours, dans des salles latérales ou des cryptes près du Baron et dans la zone de Bjork.",
    },
    [92421] = {
        ["name"] = "Justice de la Lumière",
        ["objective"] = "Récupérez 25 membres intacts dans les Ruines de Lordaeron.",
    },
    [92415] = {
        ["name"] = "Souviens-toi que je t’aime",
        ["objective"] = "Apportez la lettre tachée de sang à la gouvernante des orphelins Rossignol.",
        ["note"] = "Cette quête commence avec l’objet « Lettre tachée de sang ».",
    },
    [95216] = {
        ["name"] = "La nouvelle peste",
        ["objective"] = "Récupérez la souche hautement toxique sur Witherfang.",
    },
    [92422] = {
        ["name"] = "Colère de Rath’mael",
        ["objective"] = "Tuez Rath’mael dans les Ruines de Lordaeron.",
    },
    [214] = {
        ["name"] = "Bandeaux de soie rouge",
        ["objective"] = "Récupérez 10 bandeaux de soie rouge sur les Défias dans les Mortemines.",
        ["note"] = "Nécessite l’étape d’escorte de la Confrérie défias.",
    },
    [168] = {
        ["name"] = "Collecte de souvenirs",
        ["objective"] = "Récupérez 4 cartes du syndicat des mineurs sur les mineurs morts-vivants dans les tunnels à l’extérieur de l’instance.",
        ["note"] = "Le tunnel latéral des morts-vivants se trouve avant le portail de l’instance.",
    },
    [92753] = {
        ["name"] = "Destruction dans les Mortemines",
        ["objective"] = "Placez les explosifs près de la forge dans les Mortemines.",
    },
    [167] = {
        ["name"] = "Oh, mon frère…",
        ["objective"] = "Récupérez l’insigne de Thistlenettle sur le contremaître Thistlenettle dans le tunnel latéral des morts-vivants.",
        ["note"] = "Le contremaître se trouve dans les tunnels avant le portail de l’instance.",
    },
    [2040] = {
        ["name"] = "Assaut souterrain",
        ["objective"] = "Récupérez le Gnoam Sprecklesprocket sur le Déchiqueteur de Sneed.",
        ["note"] = "Fait suite à « Parler à Shoni ».",
    },
    [166] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Battez Edwin VanCleef et récupérez sa tête.",
        ["note"] = "Dernière étape en donjon de la suite « La Confrérie défias » ; terminez d’abord les étapes précédentes.",
    },
    [373] = {
        ["name"] = "La lettre non envoyée",
        ["objective"] = "Apportez la lettre à l’architecte de la cité à Hurlevent.",
        ["note"] = "Débute une suite qui se poursuit avec Bazil Thredd.",
    },
    [971] = {
        ["name"] = "Connaissance dans les profondeurs",
        ["objective"] = "Récupérez le manuscrit de Lorgalis dans les Profondeurs de Brassenoire.",
        ["note"] = "Le manuscrit de Lorgalis se trouve dans un coffre en fer endommagé sous l’eau, dans le bassin d’Ask’ar, dans l’alcôve nord juste après la salle des tortues de Ghamoo-ra.",
    },
    [1275] = {
        ["name"] = "Recherches sur la corruption",
        ["objective"] = "Récupérez 8 troncs cérébraux corrompus sur les créatures des Profondeurs de Brassenoire.",
        ["note"] = "Fait suite à « La corruption au loin ».",
    },
    [1198] = {
        ["name"] = "À la recherche de Thaelrid",
        ["objective"] = "Trouvez le garde d’Argent Thaelrid dans les Profondeurs de Brassenoire.",
    },
    [1199] = {
        ["name"] = "Le crépuscule tombe",
        ["objective"] = "Récupérez 10 pendentifs du Marteau du crépuscule sur ses membres dans les Profondeurs de Brassenoire.",
    },
    [1200] = {
        ["name"] = "Vilénie à Brassenoire",
        ["objective"] = "Battez le seigneur du Crépuscule Kelris et récupérez sa tête.",
    },
    [6564] = {
        ["name"] = "Allégeance aux Dieux très anciens",
        ["objective"] = "Apportez la note humide à Je’neu Sancrea en Orneval.",
    },
    [6562] = {
        ["name"] = "Problèmes dans les profondeurs",
        ["objective"] = "Parlez à Je’neu Sancrea en Orneval.",
        ["note"] = "Étape d’introduction menant à « L’essence d’Aku’mai ».",
    },
    [6563] = {
        ["name"] = "L’essence d’Aku’mai",
        ["objective"] = "Récupérez 20 saphirs d’Aku’mai dans les Profondeurs de Brassenoire.",
        ["note"] = "Fait suite à « Problèmes dans les profondeurs ».",
    },
    [6565] = {
        ["name"] = "Allégeance aux Dieux très anciens",
        ["objective"] = "Battez Lorgus Jett dans les Profondeurs de Brassenoire.",
        ["note"] = "Fait suite à la version d’« Allégeance aux Dieux très anciens » qui commence avec la note humide.",
    },
    [6561] = {
        ["name"] = "Vilénie à Brassenoire",
        ["objective"] = "Battez le seigneur du Crépuscule Kelris et récupérez sa tête.",
    },
    [6921] = {
        ["name"] = "Parmi les ruines",
        ["objective"] = "Récupérez le noyau des profondeurs sur la pierre des profondeurs dans les Profondeurs de Brassenoire.",
        ["note"] = "La pierre des profondeurs est également liée à la rencontre optionnelle du Baron Aquanis.",
    },
    [5723] = {
        ["name"] = "Tester la force de l’ennemi",
        ["objective"] = "Tuez 8 troggs de Ragefeu et 8 chamans de Ragefeu dans le Gouffre de Ragefeu.",
    },
    [5722] = {
        ["name"] = "À la recherche de la sacoche perdue",
        ["objective"] = "Trouvez le cadavre de Maur Totem-sinistre dans le Gouffre de Ragefeu et fouillez-le.",
    },
    [5724] = {
        ["name"] = "Rapporter la sacoche perdue",
        ["objective"] = "Apportez la sacoche Totem-sinistre à Rahauro aux Pitons-du-Tonnerre.",
    },
    [5728] = {
        ["name"] = "Ennemis cachés",
        ["objective"] = "Tuez Bazzalan et Jergosh l’Invocateur dans le Gouffre de Ragefeu.",
        ["note"] = "Nécessite les étapes précédentes de la suite « Ennemis cachés » à Orgrimmar. L’étape suivante propose plus tard :",
    },
    [5761] = {
        ["name"] = "Tuer la bête",
        ["objective"] = "Tuez Taragaman l’Affameur et récupérez son cœur.",
    },
    [5725] = {
        ["name"] = "Le pouvoir de détruire…",
        ["objective"] = "Récupérez « Sorts de l’ombre » et « Incantations du Néant » dans le Gouffre de Ragefeu.",
    },
    [1098] = {
        ["name"] = "Traqueurs de la mort à Ombrecroc",
        ["objective"] = "Trouvez le traqueur de la mort Adamant et le traqueur de la mort Vincent dans le Donjon d’Ombrecroc.",
    },
    [1740] = {
        ["name"] = "L’Orbe de Soran’ruk",
        ["objective"] = "Trouvez 3 fragments de Soran’ruk et 1 grand fragment de Soran’ruk, puis rapportez-les à Doan Karhan.",
        ["note"] = "Quête de classe démoniste. Les fragments viennent du Donjon d’Ombrecroc et des Profondeurs de Brassenoire.",
    },
    [1013] = {
        ["name"] = "Le Livre d’Ur",
        ["objective"] = "Apportez le Livre d’Ur du Donjon d’Ombrecroc au gardien Bel’dugur.",
    },
    [1014] = {
        ["name"] = "Arugal doit mourir",
        ["objective"] = "Tuez l’archimage Arugal et apportez sa tête à Dalar Tisselaube.",
        ["note"] = "Les données Forever actuelles indiquent également « Intelligence des Arcanes » comme récompense apprise.",
    },
    [96391] = {
        ["name"] = "Carte souterraine",
        ["objective"] = "Apportez la Carte des Sombrefers à Earthseer Farsen à Dun Morogh.",
        ["description"] = "La Carte des Sombrefers commence cette quête et mène directement à « Incursion dans l’ancienne Forgefer ».",
    },
    [865] = {
        ["name"] = "Cornes de raptor",
        ["objective"] = "Récupérez 5 cornes de raptor intactes sur les Tranchefaux solécaille et apportez-les à Mebok Mizzyrix.",
        ["description"] = "Doit être terminée avant que « Breuvages intelligents » soit disponible.",
    },
    [870] = {
        ["name"] = "Les bassins oubliés",
        ["objective"] = "Examinez l’eau des bassins oubliés au nord-ouest de la Croisée puis faites votre rapport.",
        ["description"] = "Examinez la fissure sous les bassins oubliés.",
    },
    [877] = {
        ["name"] = "L’oasis stagnante",
        ["objective"] = "Apportez les graines séchées à l’oasis stagnante, testez-les à la fissure puis retournez voir Tonga.",
        ["description"] = "Prochaine enquête obligatoire sur les oasis après « Les bassins oubliés ».",
    },
    [880] = {
        ["name"] = "Êtres altérés",
        ["objective"] = "Apportez 8 carapaces de claqueurs altérés à Tonga Totem-runique à la Croisée.",
        ["description"] = "Terminer « Êtres altérés » débloque « Hamuul Totem-runique ».",
    },
    [1489] = {
        ["name"] = "Hamuul Totem-runique",
        ["objective"] = "Parlez à Hamuul Totem-runique à la Cime des Anciens, aux Pitons-du-Tonnerre.",
        ["description"] = "Après « Êtres altérés », Tonga vous envoie auprès de Hamuul.",
    },
    [1490] = {
        ["name"] = "Nara Crin-sauvage",
        ["objective"] = "Parlez à Nara Crin-sauvage aux Pitons-du-Tonnerre.",
        ["description"] = "Nara Crin-sauvage est le dernier prérequis avant « Les dirigeants du Croc ».",
    },
    [153] = {
        ["name"] = "Bandeaux de cuir rouge",
        ["objective"] = "Apportez 15 bandeaux de cuir rouge à l’éclaireur Galiaan à la Colline des sentinelles.",
        ["description"] = "Doit être terminée avant « Bandeaux de soie rouge ».",
    },
    [65] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Parlez à Wiley le Noir à Comté-du-Lac.",
        ["description"] = "Première étape de la suite obligatoire « La Confrérie défias ».",
    },
    [132] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Rapportez la note de Wiley à Gryan Roidemantel dans la Marche de l’Ouest.",
        ["description"] = "Deuxième étape de la suite « La Confrérie défias ».",
    },
    [135] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Apportez la note de Wiley au maître Mathias Shaw à Hurlevent.",
        ["description"] = "Shaw enquête sur le lien entre les Défias et les maçons.",
    },
    [141] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Rapportez le rapport de Shaw à Gryan Roidemantel dans la Marche de l’Ouest.",
        ["description"] = "Rapportez à Gryan les découvertes de Shaw sur Edwin VanCleef.",
    },
    [142] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Trouvez le messager défias dans la Marche de l’Ouest et apportez son message à Gryan Roidemantel.",
        ["description"] = "Le messager patrouille sur les routes entre Ruisselune, la carrière de la Côte de l’Or et la mine de Jangolode.",
        ["note"] = "Le messager défias patrouille sur les routes entre Ruisselune, la carrière de la Côte de l’Or et la mine de Jangolode.",
    },
    [155] = {
        ["name"] = "La Confrérie défias",
        ["objective"] = "Escortez le traître défias jusqu’à ce qu’il révèle la cachette des Défias, puis retournez voir Gryan Roidemantel.",
        ["description"] = "Dernier prérequis avant l’étape en donjon de « La Confrérie défias ».",
    },
    [2041] = {
        ["name"] = "Parler à Shoni",
        ["objective"] = "Parlez à Shoni la Silencieuse à Hurlevent.",
        ["description"] = "Mène directement à « Assaut souterrain ».",
    },
    [92742] = {
        ["name"] = "Tester les puits",
        ["objective"] = "Utilisez le kit d’échantillonnage d’eau aux puits de la ferme Jansen et de la ferme Molsen.",
        ["description"] = "Première quête de la suite « Sol toxique ».",
    },
    [92744] = {
        ["name"] = "Branchies de murloc",
        ["objective"] = "Récupérez 7 branchies de murloc longrivage le long de la côte de la Marche de l’Ouest.",
        ["description"] = "Deuxième quête de la suite « Sol toxique ».",
    },
    [92745] = {
        ["name"] = "L’état des mines",
        ["objective"] = "Tuez 4 creuseurs kobolds dans la mine de Jangolode et 6 mineurs Riverpaw dans la carrière de la Côte de l’Or.",
        ["description"] = "Vérifiez si les mines de la Marche de l’Ouest sont à l’origine de la contamination.",
    },
    [92747] = {
        ["name"] = "Espionnage à Ruisselune",
        ["objective"] = "Récupérez 8 fournitures industrielles suspectes à Ruisselune.",
        ["description"] = "Les fournitures se trouvent dans les grottes menant à l’entrée des Mortemines.",
    },
    [92748] = {
        ["name"] = "Consultation sur les explosifs",
        ["objective"] = "Rendez-vous dans le quartier des Nains à Hurlevent et trouvez un ingénieur pouvant aider avec les explosifs.",
        ["description"] = "Commence la partie explosifs de la suite « Sol toxique ».",
    },
    [92749] = {
        ["name"] = "Un plan à la dynamite",
        ["objective"] = "Récupérez 10 dynamites grossières puis retournez voir Sprite Jumpsprocket à Hurlevent.",
        ["description"] = "La dynamite grossière peut être fabriquée, échangée ou achetée à l’hôtel des ventes.",
        ["note"] = "La dynamite grossière peut être fabriquée, échangée ou achetée à l’hôtel des ventes.",
    },
    [92750] = {
        ["name"] = "Détonation à distance",
        ["objective"] = "Parlez au SI:7 à propos d’un détonateur à distance.",
        ["description"] = "Un détonateur à distance est nécessaire pour l’explosion prévue.",
    },
    [92751] = {
        ["name"] = "Détonation à distance",
        ["objective"] = "Rapportez le kit de détonateur à distance à Sprite Jumpsprocket dans le quartier des Nains.",
        ["description"] = "Rapportez le détonateur à l’ingénieur.",
    },
    [92752] = {
        ["name"] = "Consultation sur les explosifs",
        ["objective"] = "Retournez voir Alba Fairmoon à l’auberge de la Colline des sentinelles avec les explosifs terminés.",
        ["description"] = "Dernière préparation avant « Destruction dans les Mortemines ».",
    },
    [92819] = {
        ["name"] = "Destruction dans les Mortemines",
        ["objective"] = "Utilisez le détonateur.",
        ["description"] = "Dernière étape de la suite « Sol toxique ».",
    },
    [5726] = {
        ["name"] = "Ennemis cachés",
        ["objective"] = "Apportez à Thrall un insigne de lieutenant de la Lame ardente provenant du Rocher du Crâne.",
        ["description"] = "Première étape obligatoire d’« Ennemis cachés » pour la suite du Gouffre de Ragefeu.",
    },
    [5727] = {
        ["name"] = "Ennemis cachés",
        ["objective"] = "Parlez à Neeru Lamefeu dans la Faille de l’Ombre puis retournez voir Thrall.",
        ["description"] = "Neeru se trouve dans la Faille de l’Ombre près de l’entrée du Gouffre de Ragefeu.",
    },
    [3765] = {
        ["name"] = "La corruption au loin",
        ["objective"] = "Rendez-vous auprès de Gershala Murmenuit à Auberdine, sur Sombrivage.",
        ["description"] = "Quête d’introduction de l’Alliance à terminer avant « Recherches sur la corruption ».",
    },
}

FDJ.ContentLocales.frFR.bosses = {
    ["Trash Drops"] = "Butin de trash",
    ["Lordaeron Captain"] = "Capitaine de Lordaeron",
    -- Official client names (Wowhead Forever database, 2026-10-03).
    ["Faldrim Anvilmar"] = "Faldrim Courbenclume",
    ["Plunder"] = "Pilleur",
    ["Durgen Dirgehammer"] = "Durgen Mornemartel",
    ["Lord Cobrahn"] = "Seigneur Cobrahn",
    ["Lady Anacondra"] = "Dame Anacondra",
    ["Lord Pythas"] = "Seigneur Pythas",
    ["Lord Serpentis"] = "Seigneur Serpentis",
    ["Verdan the Everliving"] = "Verdan l'Immortel",
    ["Mutanus the Devourer"] = "Mutanus le Dévoreur",
    ["Deviate Faerie Dragon"] = "Dragon féérique déviant",
    ["The Baron"] = "Le baron",
    ["Witherfang"] = "Croc-Flétri",
    ["The Abandoned"] = "L'Abandonné",
    ["Viktor the Vile"] = "Viktor le Vil",
    ["Miner Johnson"] = "Mineur Johnson",
    ["Sneed's Shredder"] = "Déchiqueteur de Sneed",
    ["Mr. Smite"] = "M. Smite",
    ["Captain Greenskin"] = "Capitaine Vertepeau",
    ["Cookie"] = "Macaron",
    ["Lady Sarevess"] = "Dame Sarevess",
    ["Old Serra'kis"] = "Vieux Serra'kis",
    ["Twilight Lord Kelris"] = "Seigneur du crépuscule Kelris",
    ["Oggleflint"] = "Lorgnesilex",
    ["Taragaman the Hungerer"] = "Taragaman l'Affameur",
    ["Jergosh the Invoker"] = "Jergosh l'Invocateur",
    ["Fel Steed / Shadow Charger"] = "Palefroi corrompu / Destrier des ténèbres",
    ["Razorclaw the Butcher"] = "Tranchegriffe le Boucher",
    ["Baron Silverlaine"] = "Baron d'Argelaine",
    ["Commander Springvale"] = "Commandant Springvale",
    ["Odo the Blindwatcher"] = "Odo l'Aveugle",
    ["Deathsworn Captain"] = "Capitaine Ligemort",
    ["Arugal's Voidwalker"] = "Marcheur du Vide d’Arugal",
    ["Fenrus the Devourer"] = "Fenrus le Dévoreur",
    ["Wolf Master Nandos"] = "Maître-loup Nandos",
    ["Archmage Arugal"] = "Archimage Arugal",
    ["Targorr the Dread"] = "Targorr le Terrifiant",
    ["Lyn the Ignored"] = "Lyn l'Ignoré",
    ["Viscous Fallout"] = "Retombée visqueuse",
    ["Electrocutioner 6000"] = "Electrocuteur 6000",
    ["Crowd Pummeler 9-60"] = "Faucheur de foule 9-60",
    ["Mekgineer Thermaplugg"] = "Mekgénieur Thermaplugg",
    ["Dark Iron Ambassador"] = "Ambassadeur Sombrefer",
    ["Aggem Thorncurse"] = "Aggem Mantépine",
    ["Death Speaker Jargba"] = "Nécrorateur Jargba",
    ["Overlord Ramtusk"] = "Seigneur Brusquebroche",
    ["Agathelos the Raging"] = "Agathelos l'Enragé",
    ["Charlga Razorflank"] = "Charlga Trancheflanc",
    ["Blind Hunter"] = "Chasseur aveugle",
    ["Earthcaller Halmgar"] = "Implorateur de la terre Halmgar",
    ["Interrogator Vishas"] = "Interrogateur Vishas",
    ["Azshir the Sleepless"] = "Azshir le Sans-sommeil",
    ["Fallen Champion"] = "Champion mort",
    ["Ironspine"] = "Echine-de-fer",
    ["Bloodmage Thalnos"] = "Mage de sang Thalnos",
}

FDJ.ContentLocales.frFR.slotParts = {
    ["Chest"] = "Torse",
    ["Leather"] = "Cuir",
    ["Wrist"] = "Poignets",
    ["Cloth"] = "Tissu",
    ["Back"] = "Dos",
    ["Waist"] = "Taille",
    ["Mail"] = "Mailles",
    ["Hands"] = "Mains",
    ["Feet"] = "Pieds",
    ["Legs"] = "Jambes",
    ["Neck"] = "Cou",
    ["Finger"] = "Doigt",
    ["Trinket"] = "Bijou",
    ["Bag"] = "Sac",
    ["One-Hand"] = "À une main",
    ["Main Hand"] = "Main droite",
    ["Off Hand"] = "Main gauche",
    ["Two-Hand"] = "À deux mains",
    ["Dagger"] = "Dague",
    ["Sword"] = "Épée",
    ["Axe"] = "Hache",
    ["Mace"] = "Masse",
    ["Staff"] = "Bâton",
    ["Shield"] = "Bouclier",
    ["Polearm"] = "Arme d’hast",
    ["Ranged"] = "À distance",
    ["Wand"] = "Baguette",
    ["Thrown"] = "Arme de jet",
    ["Engineering"] = "Ingénierie",
    ["Quest Item"] = "Objet de quête",
    ["Head"] = "Tête",
    ["Shoulder"] = "Épaules",
    ["Bow"] = "Arc",
    ["Crossbow"] = "Arbalète",
    ["Fist Weapon"] = "Arme de pugilat",
    ["Leatherworking Recipe"] = "Recette de travail du cuir",
    ["Held In Off-hand"] = "Tenu en main gauche",
}

FDJ.ContentLocales.frFR.replacements = {
    {"Farm Dark Iron Spies here for the Dark Iron Map", "Tuez des espions Sombrefers ici pour obtenir la Carte des Sombrefers"},
    {"Dark Iron Map drops from Dark Iron Spies around Ironband's Compound", "La Carte des Sombrefers s’obtient sur les espions Sombrefers autour du camp d’Ironband"},
    {"Alba Fairmoon is inside the Sentinel Hill inn", "Alba Fairmoon se trouve dans l’auberge de la Colline des sentinelles"},
    {"Argos Nightwhisper is in The Park, beside the moonwell area.", "Argos Murmenuit se trouve dans le Parc, près du puits de lune."},
    {"Serpentbloom starts from Apothecary Zamah in the Pools of Vision beneath Spirit Rise", "Fleur de serpent commence auprès de l’apothicaire Zamah aux Bassins de la Vision, sous la Cime des Esprits"},
    {"Start Hidden Enemies here", "« Ennemis cachés » commence ici"},
    {"Start In Search of Thaelrid here", "« À la recherche de Thaelrid » commence ici"},
    {"Start Raptor Horns here", "« Cornes de raptor » commence ici"},
    {"Start Red Leather Bandanas here", "« Bandeaux de cuir rouge » commence ici"},
    {"Start Speak with Shoni here", "« Parler à Shoni » commence ici"},
    {"Start Testing the Wells here", "« Tester les puits » commence ici"},
    {"Start The Defias Brotherhood here", "« La Confrérie Défias » commence ici"},
    {"Start The Forgotten Pools here", "« Les Bassins oubliés » commence ici"},
    {"southeast of Brill", "au sud-est de Brill"},
    {"Pools of Vision", "Bassins de la Vision"},
    {"Sun Rock Retreat", "Retraite de Roche-Soleil"},
    {"Tinker Town", "Brikabrok"},
    {"Darnassus", "Darnassus"},
    {"Apothecarium", "Apothicarium"},
    {"by the bridge / vault entrance in", "près du pont / de l’entrée du caveau à"},
    {"near the dungeon entrance", "près de l’entrée du donjon"},
    {"after the first room", "après la première salle"},
    {"inside the dungeon", "dans le donjon"},
    {"just inside Ruins of Lordaeron", "juste à l’intérieur des Ruines de Lordaeron"},
    {"graveyard inside Ruins of Lordaeron", "cimetière dans les Ruines de Lordaeron"},
    {"%(%s*after Underground Map%s*%)", "(après « Carte souterraine »)"},
    {"above the entrance to", "au-dessus de l’entrée de"},
    {"left of the entrance", "à gauche de l’entrée"},
    {"Follow the quest directions beginning in", "Suivez les indications de quête en commençant à"},
    {"Stone tablet inside a vault in the Reliquary of Kings", "Tablette de pierre dans un caveau du Reliquaire des rois"},
    {"Durgen Dirgehammer's room", "salle de Durgen Dirgehammer"},
    {"Maur Grimtotem's corpse", "cadavre de Maur Totem-sinistre"},
    {"dropped by Dark Iron Spies", "obtenue sur les espions Sombrefers"},
    {"Blackfathom Tide Priestesses", "Prêtresses des marées de Brassenoire"},
    {"taken from", "pris sur"},
    {"dropped by", "obtenu sur"},
    {"at Ironband's Compound", "au camp d’Ironband"},
    {"Ironband's Compound", "camp d’Ironband"},
    {"Dark Iron Spies", "espions Sombrefers"},
    {"Northern Barrens", "Tarides du Nord"},
    {"The Barrens", "Tarides"},
    {"Cleft of Shadow", "Faille de l’Ombre"},
    {"Valley of Wisdom", "Vallée de la Sagesse"},
    {"Royal Quarter", "Quartier royal"},
    {"Elder Rise", "Cime des Anciens"},
    {"Dwarven District", "Quartier des Nains"},
    {"Cathedral Square", "Place de la Cathédrale"},
    {"Old Town", "Vieille ville"},
    {"Sentinel Hill tower", "tour de la Colline des sentinelles"},
    {"Sentinel Hill inn", "auberge de la Colline des sentinelles"},
    {"Sentinel Hill", "Colline des sentinelles"},
    {"Stormwind City", "Hurlevent"},
    {"Stormwind", "Hurlevent"},
    {"Ironforge", "Forgefer"},
    {"Thunder Bluff", "Pitons-du-Tonnerre"},
    {"Undercity", "Fossoyeuse"},
    {"Silverpine Forest", "Forêt des Pins-Argentés"},
    {"The Sepulcher", "Le Sépulcre"},
    {"Darkshore", "Sombrivage"},
    {"Ashenvale", "Orneval"},
    {"Stonetalon Mountains", "Serres-Rocheuses"},
    {"Redridge Mountains", "Carmines"},
    {"Zoram Strand", "Grève de Zoram"},
    {"Zoram'gar Outpost", "Avant-poste de Zoram’gar"},
    {"Moonbrook", "Ruisselune"},
    {"Ratchet", "Cabestan"},
    {"The Crossroads", "La Croisée"},
    {"Craftsmen's Terrace", "Terrasse des Artisans"},
    {"Forlorn Cavern", "Caverne lugubre"},
    {"Skull Rock", "Rocher du Crâne"},
    {"Gold Coast Quarry", "carrière de la Côte de l’Or"},
    {"Jangolode Mine", "mine de Jangolode"},
    {"Lakeshire", "Comté-du-Lac"},
    {"The Park", "Le Parc"},
    {"Pyrewood Village", "Bois-du-Bûcher"},
    {"inside Blackfathom Deeps", "dans les Profondeurs de Brassenoire"},
    {"inside Shadowfang Keep", "dans le Donjon d’Ombrecroc"},
    {"inside Ragefire Chasm", "dans le Gouffre de Ragefeu"},
    {"inside Ruins of Lordaeron", "dans les Ruines de Lordaeron"},
    {"inside Hall of Thanes", "dans la Salle des thanes"},
    {"inside the Deadmines", "dans les Mortemines"},
    {"Wailing Caverns", "Cavernes des lamentations"},
    {"Blackfathom Deeps", "Profondeurs de Brassenoire"},
    {"Shadowfang Keep", "Donjon d’Ombrecroc"},
    {"Ragefire Chasm", "Gouffre de Ragefeu"},
    {"Ruins of Lordaeron", "Ruines de Lordaeron"},
    {"Hall of Thanes", "Salle des thanes"},
    {"The Deadmines", "Les Mortemines"},
    {"Deadmines", "Mortemines"},
    {"Item start:", "Objet de départ :"},
    {"Use ", "Utilisez "},
    {"Dropped by:", "Obtenu sur :"},
    {"Looted from", "Butin sur"},
    {"Rare spawn.", "Apparition rare."},
    {"Quest Item", "Objet de quête"},
    {"Trash Drops", "Butin de trash"},
    {"Alliance", "Alliance"},
    {"Horde", "Horde"},
    {"Both", "Les deux"},
    {"Warlock", "Démoniste"},
    {"Mage", "Mage"},
    {"Priest", "Prêtre"},
    {"Rogue", "Voleur"},
    {"Warrior", "Guerrier"},
    {"Hunter", "Chasseur"},
    {"Druid", "Druide"},
    {"Paladin", "Paladin"},
    {"Shaman", "Chaman"},
}
