local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS

-- Translations for the dungeons added in 1.3.8+ (Gnomeregan, Razorfen Kraul,
-- Scarlet Monastery: Graveyard, City of Dalaran, Excavation Site) and their
-- quests, plus whole place names used in quest giver / turn-in lines.
-- Merged into each language table without overwriting existing entries.

FDJ.ContentLocales = FDJ.ContentLocales or {}
local DATA = {}
DATA.deDE = {
    dungeons = {
        ["Gnomeregan"] = { name = "Gnomeregan", location = "Dun Morogh", description = "Die verstrahlte unterirdische Stadt der Gnome, überrannt von Troggs und den Truppen von Robogenieur Thermaplugg." },
        ["Razorfen Kraul"] = { name = "Kral der Klingenhauer", location = "Brachland", description = "Ein weitläufiges Dornenlabyrinth, bewohnt von den Stacheleber des Krals der Klingenhauer." },
        ["Scarlet Monastery: Graveyard"] = { name = "Scharlachrotes Kloster: Friedhof", location = "Tirisfal", description = "Der Friedhofsflügel des Scharlachroten Klosters, heimgesucht von ruhelosen Toten und scharlachroten Verteidigern." },
        ["City of Dalaran"] = { name = "Stadt Dalaran", location = "Alteracgebirge", description = "Die wiederhergestellte Magierstadt Dalaran ist in WoW Forever ein neuer Dungeon für fünf Spieler. Betretet sie durch die Kanalisation und die Schattenseite und kämpft euch durch die Straßen bis zur Violetten Zitadelle." },
        ["Excavation Site: Wetlands"] = { name = "Ausgrabungsstätte: Sumpfland", location = "Sumpfland", description = "Eine in der Zeit gefangene Titanen-Ausgrabungsstätte oberhalb von Whelgars Ausgrabungsstätte, deren Titanenkonstrukte niemandem mehr gehorchen. Bereiche: Verlorene Marsch, Pirscherdickicht, Stätte des Wächters und Verlorene Grabungsstätte." },
    },
    quests = {
        [2930001] = { name = "Weiße Lochkarte", objective = "Tötet Gegner im äußeren Bereich von Gnomeregan, bis eine weiße Lochkarte erbeutet wird.", pickup = "Höhlentiefplünderer, Höhlentiefeindringlinge, verstrahlte Eindringlinge und verwirrte Aussätzige außerhalb der Instanz", turnin = "Behaltet die Karte für Matrixlochkartograph 3005-A", description = "Zufälliger Fund; meist erhaltet ihr sie schon beim ersten Säubern des Außenbereichs." },
        [2930002] = { name = "Gelbe Lochkarte (Lochkartograph 3005-A)", objective = "Benutzt Matrixlochkartograph 3005-A mit der weißen Lochkarte, um eine gelbe Lochkarte zu erhalten.", pickup = "Matrixlochkartograph 3005-A, Werkstattbereich des Zugdepots, außerhalb der Instanz", turnin = "Ihr erhaltet eine gelbe Lochkarte", description = "Die einzigen Lochkartographen außerhalb der Instanz: auf der erhöhten Plattform im Zugdepot und am Werkstatteingang (Hintertür)." },
        [2930003] = { name = "Blaue Lochkarte (Lochkartograph 3005-B)", objective = "Benutzt Matrixlochkartograph 3005-B mit der gelben Lochkarte, um eine blaue Lochkarte zu erhalten.", pickup = "Matrixlochkartograph 3005-B, Schlafsaal (direkt hinter der Reinen Zone), in der Instanz", turnin = "Ihr erhaltet eine blaue Lochkarte", description = "In der Instanz, im Schlafsaal." },
        [2930004] = { name = "Rote Lochkarte (Lochkartograph 3005-C)", objective = "Benutzt Matrixlochkartograph 3005-C mit der blauen Lochkarte, um eine rote Lochkarte zu erhalten.", pickup = "Matrixlochkartograph 3005-C, obere Plattform der Startrampe bei Elektrokutor 6000", turnin = "Ihr erhaltet eine rote Lochkarte", description = "Auf der Plattform von Elektrokutor 6000." },
        [2930005] = { name = "Prismatische Lochkarte (Lochkartograph 3005-D)", objective = "Benutzt Matrixlochkartograph 3005-D mit der roten Lochkarte, um die prismatische Lochkarte zu erhalten, und bringt sie zu Meistermechaniker Gussrohr in Eisenschmiede.", pickup = "Matrixlochkartograph 3005-D, Westseite der unteren Ebene der Ingenieurslabore", turnin = "Meistermechaniker Gussrohr, Tüftlerstadt, Eisenschmiede", description = "Fahrt mit dem Aufzug nach unten; das Terminal steht im ersten Gang rechts." },
        [2922] = { name = "Rettet Techbots Gehirn!", objective = "Bringt Techbots Speicherkern zu Tüftlermeister Funkenschmied in Eisenschmiede." },
        [2926] = { name = "Gnogaine", objective = "Benutzt die leere bleierne Sammelphiole an verstrahlten Eindringlingen oder Plünderern und bringt die volle Phiole zu Ozzie Togglevolt zurück." },
        [2962] = { name = "Gegen grünes Leuchten hilft nur mehr grünes Leuchten", objective = "Bringt hochwirksamen radioaktiven Fallout und die schwere bleierne Sammelphiole zu Ozzie. Der Fallout zerfällt schnell." },
        [2928] = { name = "Gyrobohrmatische Exkavatoren", objective = "Bringt 24 robomechanische Innereien zu Shoni in Sturmwind." },
        [2924] = { name = "Essenzielle Artefakte", objective = "Bringt 12 essenzielle Artefakte zu Klockmort Schraubspanner in Eisenschmiede." },
        [2930] = { name = "Datenrettung", objective = "Bringt eine prismatische Lochkarte zu Meistermechaniker Gussrohr in Eisenschmiede." },
        [2929] = { name = "Der große Verrat", objective = "Tötet Robogenieur Thermaplugg und kehrt zu Hochtüftler Mekkadrill zurück." },
        [2843] = { name = "Gnomer-weeeeeg!", objective = "Wartet, bis Scooty den Goblintransponder kalibriert hat." },
        [2841] = { name = "Bohrturmkriege", objective = "Beschafft die Bohrturmpläne und Thermapluggs Safekombination und bringt sie zu Nogg in Orgrimmar." },
        [2904] = { name = "Ein feines Durcheinander", objective = "Eskortiert Kernobee zum Ausgang des Uhrwerkgangs und erstattet dann Scooty in Beutebucht Bericht." },
        [2951] = { name = "Der Glitzermatic 5200!", objective = "Legt einen schmutzverkrusteten Gegenstand in den Glitzermatic 5200 und werft drei Silbermünzen ein, um die Maschine zu starten." },
        [2945] = { name = "Schmutzverkrusteter Ring", objective = "Findet einen Weg, den Schmutz vom schmutzverkrusteten Ring zu entfernen (benutzt den Glitzermatic 5200)." },
        [1221] = { name = "Blaublattknollen", objective = "Ruft mit der Kiste mit Löchern eine Schnüffelnasenratte und lasst sie mit dem Kommandostab 6 Blaublattknollen finden. Bringt sie mit Stab und Kiste zu Mebok Mizzyrix zurück." },
        [1144] = { name = "Willix der Importeur", objective = "Eskortiert Willix den Importeur aus dem Kral der Klingenhauer." },
        [1142] = { name = "Die Sterblichkeit schwindet", objective = "Findet Treshalas Anhänger und bringt ihn zu Treshala Fallowbrook in Darnassus." },
        [1101] = { name = "Die Vettel des Krals", objective = "Bringt Klingenflankes Medaillon zu Falfindel Wegwahrer in Thalanaar." },
        [1102] = { name = "Ein rachsüchtiges Schicksal", objective = "Bringt Klingenflankes Herz zu Auld Steinspitz in Donnerfels." },
        [1109] = { name = "Guano, guano!", objective = "Bringt 1 Haufen Kralguano von den Fledermäusen des Krals zu Großapotheker Faranell." },
        [6522] = { name = "Eine unheilige Allianz", objective = "Bringt die kleine Schriftrolle zu Varimathras in Unterstadt." },
        [1051] = { name = "Vorrels Rache", objective = "Bringt Vorrel Sengutz' Ehering (von Nancy Vishas) zu Monika Sengutz in Tarrens Mühle." },
        [1113] = { name = "Herzen des Eifers", objective = "Bringt 20 Herzen des Eifers aus dem Scharlachroten Kloster zu Großapotheker Faranell." },
    },
    places = {
        ["Ironforge"] = "Eisenschmiede",
        ["Kharanos"] = "Kharanos",
        ["Dun Morogh"] = "Dun Morogh",
        ["Stormwind City"] = "Sturmwind",
        ["Stormwind"] = "Sturmwind",
        ["Booty Bay"] = "Beutebucht",
        ["Stranglethorn Vale"] = "Schlingendorntal",
        ["Orgrimmar"] = "Orgrimmar",
        ["inside Gnomeregan"] = "in Gnomeregan",
        ["Ratchet"] = "Ratschet",
        ["The Barrens"] = "Brachland",
        ["inside Razorfen Kraul"] = "im Kral der Klingenhauer",
        ["Darnassus"] = "Darnassus",
        ["Thalanaar"] = "Thalanaar",
        ["Feralas"] = "Feralas",
        ["Thunder Bluff"] = "Donnerfels",
        ["Undercity"] = "Unterstadt",
        ["Royal Quarter"] = "Königsviertel",
        ["inside the Graveyard"] = "auf dem Friedhof",
        ["Tarren Mill"] = "Tarrens Mühle",
        ["Hillsbrad Foothills"] = "Vorgebirge des Hügellands",
        ["Dwarven District"] = "Zwergendistrikt",
        ["the Dwarven District"] = "Zwergendistrikt",
    },
}
DATA.frFR = {
    dungeons = {
        ["Gnomeregan"] = { name = "Gnomeregan", location = "Dun Morogh", description = "La cité souterraine irradiée des gnomes, envahie par les troggs et les forces du mekgénieur Thermojoncteur." },
        ["Razorfen Kraul"] = { name = "Kraal de Tranchebauge", location = "Les Tarides", description = "Un vaste labyrinthe de ronces occupé par les huran du Kraal de Tranchebauge." },
        ["Scarlet Monastery: Graveyard"] = { name = "Monastère écarlate : Cimetière", location = "Clairières de Tirisfal", description = "L'aile du cimetière du Monastère écarlate, hantée par des morts sans repos et des défenseurs écarlates." },
        ["City of Dalaran"] = { name = "Cité de Dalaran", location = "Montagnes d'Alterac", description = "La cité des mages restaurée de Dalaran est devenue un nouveau donjon à cinq joueurs dans WoW Forever. Entrez par les égouts et les Entrailles, puis frayez-vous un chemin dans les rues jusqu'à la Citadelle pourpre." },
        ["Excavation Site: Wetlands"] = { name = "Site de fouilles : Les Paluns", location = "Les Paluns", description = "Un site de fouilles titan figé dans le temps au-dessus du site de Whelgar, où des assemblages titans n'obéissent plus à personne. Zones : Marais perdu, Fourré des traqueurs, Site du gardien et Site de fouilles perdu." },
    },
    quests = {
        [2930001] = { name = "Carte perforée blanche", objective = "Tuez des monstres dans la zone extérieure de Gnomeregan jusqu'à obtenir une carte perforée blanche.", pickup = "Pillards des Cavernes, envahisseurs des Cavernes, envahisseurs irradiés et lépreux désorientés, hors de l'instance", turnin = "Gardez la carte pour la Matrice de perforation 3005-A", description = "Butin aléatoire ; on l'obtient en général dès le premier nettoyage de la zone extérieure." },
        [2930002] = { name = "Carte perforée jaune (perforatrice 3005-A)", objective = "Utilisez la Matrice de perforation 3005-A avec la carte blanche pour obtenir une carte perforée jaune.", pickup = "Matrice de perforation 3005-A, atelier du dépôt de trains, hors de l'instance", turnin = "Vous obtenez une carte perforée jaune", description = "Les seules perforatrices hors de l'instance : sur la plate-forme surélevée du dépôt et près de l'entrée de l'atelier (porte arrière)." },
        [2930003] = { name = "Carte perforée bleue (perforatrice 3005-B)", objective = "Utilisez la Matrice de perforation 3005-B avec la carte jaune pour obtenir une carte perforée bleue.", pickup = "Matrice de perforation 3005-B, le Dortoir (juste après la Zone propre), dans l'instance", turnin = "Vous obtenez une carte perforée bleue", description = "Dans l'instance, au Dortoir." },
        [2930004] = { name = "Carte perforée rouge (perforatrice 3005-C)", objective = "Utilisez la Matrice de perforation 3005-C avec la carte bleue pour obtenir une carte perforée rouge.", pickup = "Matrice de perforation 3005-C, plate-forme supérieure de la Baie de lancement avec l'Électrocuteur 6000", turnin = "Vous obtenez une carte perforée rouge", description = "Sur la plate-forme de l'Électrocuteur 6000." },
        [2930005] = { name = "Carte perforée prismatique (perforatrice 3005-D)", objective = "Utilisez la Matrice de perforation 3005-D avec la carte rouge pour obtenir la carte perforée prismatique, puis apportez-la au maître mécanicien Tuyautuyère à Forgefer.", pickup = "Matrice de perforation 3005-D, côté ouest du niveau inférieur des Laboratoires d'ingénierie", turnin = "Maître mécanicien Tuyautuyère, Brikabrok, Forgefer", description = "Prenez l'ascenseur vers le bas ; le terminal est dans le premier passage à droite." },
        [2922] = { name = "Sauvez le cerveau de Technobot !", objective = "Apportez le noyau de mémoire de Technobot au maître bricoleur Mégamécanique à Forgefer." },
        [2926] = { name = "Gnogaine", objective = "Utilisez la fiole de collecte plombée vide sur des envahisseurs ou pillards irradiés, puis rapportez la fiole pleine à Ozzie Gueule-de-ressort." },
        [2962] = { name = "Le seul remède, c'est plus de lueur verte", objective = "Rapportez à Ozzie des retombées radioactives très puissantes et la lourde fiole de collecte plombée. Les retombées se dégradent vite." },
        [2928] = { name = "Excavateurs gyroforeurs", objective = "Apportez 24 entrailles robomécaniques à Shoni à Hurlevent." },
        [2924] = { name = "Artificiels essentiels", objective = "Apportez 12 artificiels essentiels à Klockmort Serrécrou à Forgefer." },
        [2930] = { name = "Sauvetage de données", objective = "Apportez une carte perforée prismatique au maître mécanicien Tuyautuyère à Forgefer." },
        [2929] = { name = "La grande trahison", objective = "Tuez le mekgénieur Thermojoncteur et retournez voir le Grand Bricoleur Mekkanivelle." },
        [2843] = { name = "Gnomer-partiiii !", objective = "Attendez que Scooty calibre le transpondeur gobelin." },
        [2841] = { name = "La guerre des derricks", objective = "Récupérez les plans du derrick et la combinaison du coffre de Thermojoncteur et apportez-les à Nogg à Orgrimmar." },
        [2904] = { name = "Un beau gâchis", objective = "Escortez Kernobee jusqu'à la sortie du Couloir mécanique, puis faites votre rapport à Scooty à Baie-du-Butin." },
        [2951] = { name = "L'Étincelomatic 5200 !", objective = "Placez un objet couvert de crasse dans l'Étincelomatic 5200 avec trois pièces d'argent pour lancer la machine." },
        [2945] = { name = "Anneau couvert de crasse", objective = "Trouvez un moyen de nettoyer l'anneau couvert de crasse (utilisez l'Étincelomatic 5200)." },
        [1221] = { name = "Tubercules de bleufeuille", objective = "Utilisez la caisse percée pour invoquer un rat fouisseur et le bâton de commandement pour lui faire trouver 6 tubercules de bleufeuille. Rapportez-les, avec le bâton et la caisse, à Mebok Mizzyrix." },
        [1144] = { name = "Willix l'Importateur", objective = "Escortez Willix l'Importateur hors du Kraal de Tranchebauge." },
        [1142] = { name = "La mortalité décline", objective = "Trouvez le pendentif de Treshala et rapportez-le à Treshala Fallowbrook à Darnassus." },
        [1101] = { name = "La mégère du Kraal", objective = "Apportez le médaillon de Tranchecôte à Falfindel Waywarder à Thalanaar." },
        [1102] = { name = "Une vengeance funeste", objective = "Apportez le cœur de Tranchecôte à Auld Pierre-Haute aux Pitons-du-Tonnerre." },
        [1109] = { name = "Guano, guano !", objective = "Apportez 1 tas de guano du Kraal des chauves-souris du Kraal au grand apothicaire Faranell." },
        [6522] = { name = "Une alliance impie", objective = "Apportez le petit parchemin à Varimathras à Fossoyeuse." },
        [1051] = { name = "La vengeance de Vorrel", objective = "Rapportez l'alliance de Vorrel Sengutz (prise sur Nancy Vishas) à Monika Sengutz à Moulin-de-Tarren." },
        [1113] = { name = "Cœurs de zèle", objective = "Apportez 20 cœurs de zèle du Monastère écarlate au grand apothicaire Faranell." },
    },
    places = {
        ["Ironforge"] = "Forgefer",
        ["Kharanos"] = "Kharanos",
        ["Dun Morogh"] = "Dun Morogh",
        ["Stormwind City"] = "Hurlevent",
        ["Stormwind"] = "Hurlevent",
        ["Booty Bay"] = "Baie-du-Butin",
        ["Stranglethorn Vale"] = "Vallée de Strangleronce",
        ["Orgrimmar"] = "Orgrimmar",
        ["inside Gnomeregan"] = "dans Gnomeregan",
        ["Ratchet"] = "Cabestan",
        ["The Barrens"] = "Les Tarides",
        ["inside Razorfen Kraul"] = "dans le Kraal de Tranchebauge",
        ["Darnassus"] = "Darnassus",
        ["Thalanaar"] = "Thalanaar",
        ["Feralas"] = "Féralas",
        ["Thunder Bluff"] = "Les Pitons-du-Tonnerre",
        ["Undercity"] = "Fossoyeuse",
        ["Royal Quarter"] = "Quartier royal",
        ["inside the Graveyard"] = "dans le Cimetière",
        ["Tarren Mill"] = "Moulin-de-Tarren",
        ["Hillsbrad Foothills"] = "Contreforts de Hautebrande",
        ["Dwarven District"] = "Quartier des Nains",
        ["the Dwarven District"] = "Quartier des Nains",
    },
}
DATA.esES = {
    dungeons = {
        ["Gnomeregan"] = { name = "Gnomeregan", location = "Dun Morogh", description = "La ciudad subterránea irradiada de los gnomos, invadida por troggs y las fuerzas del mekigeniero Termochufe." },
        ["Razorfen Kraul"] = { name = "Horado Rajacieno", location = "Los Baldíos", description = "Un enorme laberinto de espinas ocupado por los jabaespín del Horado Rajacieno." },
        ["Scarlet Monastery: Graveyard"] = { name = "Monasterio Escarlata: Cementerio", location = "Claros de Tirisfal", description = "El ala del cementerio del Monasterio Escarlata, embrujada por muertos inquietos y defensores escarlata." },
        ["City of Dalaran"] = { name = "Ciudad de Dalaran", location = "Montañas de Alterac", description = "La restaurada ciudad de los magos, Dalaran, es una nueva mazmorra para cinco jugadores en WoW Forever. Entra por las cloacas y la Ciénaga, y abre paso por las calles hasta la Ciudadela Violeta." },
        ["Excavation Site: Wetlands"] = { name = "Excavación: Los Humedales", location = "Los Humedales", description = "Una excavación titánica atrapada en el tiempo sobre la Excavación de Whelgar, donde los ensamblajes titánicos ya no obedecen a nadie. Zonas: Marjal Perdido, Espesura del Acechador, Lugar del Guardián y Excavación Perdida." },
    },
    quests = {
        [2930001] = { name = "Tarjeta perforada blanca", objective = "Mata enemigos en la zona exterior de Gnomeregan hasta que caiga una tarjeta perforada blanca.", pickup = "Saqueadores, invasores de las Profundidades, invasores irradiados y leprosos aturdidos, fuera de la instancia", turnin = "Guarda la tarjeta para la Perforadora matricial 3005-A", description = "Botín aleatorio; normalmente la consigues en la primera limpieza de la zona exterior." },
        [2930002] = { name = "Tarjeta perforada amarilla (perforadora 3005-A)", objective = "Usa la Perforadora matricial 3005-A con la tarjeta blanca para obtener una tarjeta perforada amarilla.", pickup = "Perforadora matricial 3005-A, zona del taller de la estación de tren, fuera de la instancia", turnin = "Recibes una tarjeta perforada amarilla", description = "Las únicas perforadoras fuera de la instancia: en la plataforma elevada de la estación y junto a la entrada del taller (puerta trasera)." },
        [2930003] = { name = "Tarjeta perforada azul (perforadora 3005-B)", objective = "Usa la Perforadora matricial 3005-B con la tarjeta amarilla para obtener una tarjeta perforada azul.", pickup = "Perforadora matricial 3005-B, el Dormitorio (justo después de la Zona Limpia), dentro de la instancia", turnin = "Recibes una tarjeta perforada azul", description = "Dentro de la instancia, en el Dormitorio." },
        [2930004] = { name = "Tarjeta perforada roja (perforadora 3005-C)", objective = "Usa la Perforadora matricial 3005-C con la tarjeta azul para obtener una tarjeta perforada roja.", pickup = "Perforadora matricial 3005-C, plataforma superior de la Bahía de Lanzamiento con Electrocutor 6000", turnin = "Recibes una tarjeta perforada roja", description = "En la plataforma de Electrocutor 6000." },
        [2930005] = { name = "Tarjeta perforada prismática (perforadora 3005-D)", objective = "Usa la Perforadora matricial 3005-D con la tarjeta roja para obtener la tarjeta perforada prismática y llévala al maestro mecánico Tubosoldado en Forjaz.", pickup = "Perforadora matricial 3005-D, lado oeste del nivel inferior de los Laboratorios de Ingeniería", turnin = "Maestro mecánico Tubosoldado, Ciudad Manitas, Forjaz", description = "Baja en el ascensor; el terminal está en el primer pasillo a la derecha." },
        [2922] = { name = "¡Salvad el cerebro de Técnibot!", objective = "Lleva el núcleo de memoria de Técnibot al maestro manitas Sobrechispa en Forjaz." },
        [2926] = { name = "Gnogaína", objective = "Usa el vial de recolección emplomado vacío con invasores o saqueadores irradiados y devuelve el vial lleno a Ozzie Togglevolt." },
        [2962] = { name = "La única cura es más brillo verde", objective = "Lleva a Ozzie radiación de alta potencia y el vial de recolección emplomado pesado. La radiación se degrada rápido." },
        [2928] = { name = "Excavadoras girotaladradoras", objective = "Lleva 24 entrañas robomecánicas a Shoni en Ventormenta." },
        [2924] = { name = "Artificiales esenciales", objective = "Lleva 12 artificiales esenciales a Klockmort Llavinglesa en Forjaz." },
        [2930] = { name = "Rescate de datos", objective = "Lleva una tarjeta perforada prismática al maestro mecánico Tubosoldado en Forjaz." },
        [2929] = { name = "La gran traición", objective = "Mata al mekigeniero Termochufe y vuelve con el Manitas Mayor Mekkatorque." },
        [2843] = { name = "¡Gnomer-ahí vaaaa!", objective = "Espera a que Scooty calibre el transpondedor goblin." },
        [2841] = { name = "La guerra de las torres", objective = "Consigue los planos de la torre y la combinación de la caja fuerte de Termochufe y llévalos a Nogg en Orgrimmar." },
        [2904] = { name = "Un buen lío", objective = "Escolta a Kernobee hasta la salida del Pasaje del Engranaje y después informa a Scooty en Bahía del Botín." },
        [2951] = { name = "¡El Destellomático 5200!", objective = "Introduce un objeto mugriento en el Destellomático 5200 junto con tres monedas de plata para poner en marcha la máquina." },
        [2945] = { name = "Anillo mugriento", objective = "Encuentra la forma de limpiar el anillo mugriento (usa el Destellomático 5200)." },
        [1221] = { name = "Tubérculos de hojazul", objective = "Usa la caja agujereada para invocar a una rata hocicona y el bastón de mando para que encuentre 6 tubérculos de hojazul. Llévalos, junto al bastón y la caja, a Mebok Mizzyrix." },
        [1144] = { name = "Willix el Importador", objective = "Escolta a Willix el Importador fuera del Horado Rajacieno." },
        [1142] = { name = "La mortalidad mengua", objective = "Encuentra el colgante de Treshala y devuélveselo a Treshala Fallowbrook en Darnassus." },
        [1101] = { name = "La vieja del Horado", objective = "Lleva el medallón de Flancodecuchillo a Falfindel Waywarder en Thalanaar." },
        [1102] = { name = "Un destino vengativo", objective = "Lleva el corazón de Flancodecuchillo a Auld Piedra Pétrea en Cima del Trueno." },
        [1109] = { name = "¡Guano, guano!", objective = "Lleva 1 montón de guano del Horado de los murciélagos del Horado al maestro boticario Faranell." },
        [6522] = { name = "Una alianza impía", objective = "Lleva el pergamino pequeño a Varimathras en Entrañas." },
        [1051] = { name = "La venganza de Vorrel", objective = "Devuelve el anillo de boda de Vorrel Sengutz (de Nancy Vishas) a Monika Sengutz en Molino Tarren." },
        [1113] = { name = "Corazones de fervor", objective = "Lleva 20 corazones de fervor del Monasterio Escarlata al maestro boticario Faranell." },
    },
    places = {
        ["Ironforge"] = "Forjaz",
        ["Kharanos"] = "Kharanos",
        ["Dun Morogh"] = "Dun Morogh",
        ["Stormwind City"] = "Ventormenta",
        ["Stormwind"] = "Ventormenta",
        ["Booty Bay"] = "Bahía del Botín",
        ["Stranglethorn Vale"] = "Vega de Tuercespina",
        ["Orgrimmar"] = "Orgrimmar",
        ["inside Gnomeregan"] = "dentro de Gnomeregan",
        ["Ratchet"] = "Trinquete",
        ["The Barrens"] = "Los Baldíos",
        ["inside Razorfen Kraul"] = "dentro del Horado Rajacieno",
        ["Darnassus"] = "Darnassus",
        ["Thalanaar"] = "Thalanaar",
        ["Feralas"] = "Feralas",
        ["Thunder Bluff"] = "Cima del Trueno",
        ["Undercity"] = "Entrañas",
        ["Royal Quarter"] = "Barrio Real",
        ["inside the Graveyard"] = "dentro del Cementerio",
        ["Tarren Mill"] = "Molino Tarren",
        ["Hillsbrad Foothills"] = "Laderas de Trabalomas",
        ["Dwarven District"] = "Distrito de los Enanos",
        ["the Dwarven District"] = "Distrito de los Enanos",
    },
}
DATA.itIT = {
    dungeons = {
        ["Gnomeregan"] = { name = "Gnomeregan", location = "Dun Morogh", description = "La città sotterranea irradiata degli gnomi, invasa dai trogg e dalle forze del Meccagegnere Termospina." },
        ["Razorfen Kraul"] = { name = "Kraul di Lamaspina", location = "Savane", description = "Un vasto labirinto di rovi occupato dai cinghialidi del Kraul di Lamaspina." },
        ["Scarlet Monastery: Graveyard"] = { name = "Monastero Scarlatto: Cimitero", location = "Radure di Tirisfal", description = "L'ala del cimitero del Monastero Scarlatto, infestata da morti inquieti e difensori scarlatti." },
        ["City of Dalaran"] = { name = "Città di Dalaran", location = "Montagne d'Alterac", description = "La restaurata città dei maghi di Dalaran è diventata una nuova spedizione per cinque giocatori in WoW Forever. Entra dalle fogne e dal Sottoventre, poi fatti strada per le vie fino alla Cittadella Violacea." },
        ["Excavation Site: Wetlands"] = { name = "Sito di scavo: Paludi", location = "Paludi", description = "Un sito di scavo dei Titani intrappolato nel tempo sopra lo Scavo di Whelgar, dove i costrutti titanici non obbediscono più a nessuno. Aree: Palude Perduta, Boscaglia dei Predatori, Sito del Guardiano e Scavo Perduto." },
    },
    quests = {
        [2930001] = { name = "Scheda perforata bianca", objective = "Uccidi nemici nell'area esterna di Gnomeregan finché non ottieni una scheda perforata bianca.", pickup = "Predoni e invasori delle Caverne, invasori irradiati e lebbrosi confusi, fuori dall'istanza", turnin = "Conserva la scheda per la Perforatrice a Matrice 3005-A", description = "Bottino casuale; di solito la ottieni già alla prima pulizia dell'area esterna." },
        [2930002] = { name = "Scheda perforata gialla (perforatrice 3005-A)", objective = "Usa la Perforatrice a Matrice 3005-A con la scheda bianca per ottenere una scheda perforata gialla.", pickup = "Perforatrice a Matrice 3005-A, area dell'officina del deposito treni, fuori dall'istanza", turnin = "Ricevi una scheda perforata gialla", description = "Le uniche perforatrici fuori dall'istanza: sulla piattaforma rialzata del deposito e vicino all'ingresso dell'officina (porta sul retro)." },
        [2930003] = { name = "Scheda perforata blu (perforatrice 3005-B)", objective = "Usa la Perforatrice a Matrice 3005-B con la scheda gialla per ottenere una scheda perforata blu.", pickup = "Perforatrice a Matrice 3005-B, il Dormitorio (subito dopo la Zona Pulita), dentro l'istanza", turnin = "Ricevi una scheda perforata blu", description = "Dentro l'istanza, nel Dormitorio." },
        [2930004] = { name = "Scheda perforata rossa (perforatrice 3005-C)", objective = "Usa la Perforatrice a Matrice 3005-C con la scheda blu per ottenere una scheda perforata rossa.", pickup = "Perforatrice a Matrice 3005-C, piattaforma superiore della Baia di Lancio con Elettrocutore 6000", turnin = "Ricevi una scheda perforata rossa", description = "Sulla piattaforma di Elettrocutore 6000." },
        [2930005] = { name = "Scheda perforata prismatica (perforatrice 3005-D)", objective = "Usa la Perforatrice a Matrice 3005-D con la scheda rossa per ottenere la scheda perforata prismatica, poi portala al Maestro Meccanico Tubofuso a Forgiardente.", pickup = "Perforatrice a Matrice 3005-D, lato ovest del livello inferiore dei Laboratori d'Ingegneria", turnin = "Maestro Meccanico Tubofuso, Città dei Gingilli, Forgiardente", description = "Scendi con l'ascensore; il terminale è nel primo passaggio a destra." },
        [2922] = { name = "Salvate il cervello di Techbot!", objective = "Porta il nucleo di memoria di Techbot al Maestro Inventore Scintillatutto a Forgiardente." },
        [2926] = { name = "Gnogaina", objective = "Usa la fiala di raccolta piombata vuota su invasori o predoni irradiati e riporta la fiala piena a Ozzie Togglevolt." },
        [2962] = { name = "L'unica cura è più bagliore verde", objective = "Porta a Ozzie ricaduta radioattiva ad alta potenza e la fiala di raccolta piombata pesante. La ricaduta si degrada in fretta." },
        [2928] = { name = "Escavatori girotrapananti", objective = "Porta 24 interiora robomeccaniche a Shoni a Roccavento." },
        [2924] = { name = "Artificiali essenziali", objective = "Porta 12 artificiali essenziali a Klockmort Chiavinglese a Forgiardente." },
        [2930] = { name = "Recupero dati", objective = "Porta una scheda perforata prismatica al Maestro Meccanico Tubofuso a Forgiardente." },
        [2929] = { name = "Il grande tradimento", objective = "Uccidi il Meccagegnere Termospina e torna dall'Alto Inventore Mekkatorque." },
        [2843] = { name = "Gnomer-andaaaato!", objective = "Aspetta che Scooty calibri il trasponditore goblin." },
        [2841] = { name = "Guerre di trivelle", objective = "Recupera i progetti della trivella e la combinazione della cassaforte di Termospina e portali a Nogg a Orgrimmar." },
        [2904] = { name = "Un bel pasticcio", objective = "Scorta Kernobee fino all'uscita del Passaggio a Orologeria, poi fai rapporto a Scooty a Baia del Bottino." },
        [2951] = { name = "Lo Scintillomatic 5200!", objective = "Inserisci un oggetto incrostato di sporcizia nello Scintillomatic 5200 con tre monete d'argento per avviare la macchina." },
        [2945] = { name = "Anello incrostato di sporcizia", objective = "Trova un modo per pulire l'anello incrostato di sporcizia (usa lo Scintillomatic 5200)." },
        [1221] = { name = "Tuberi di Foglia Azzurra", objective = "Usa la cassa bucherellata per evocare un ratto fiutatore e il bastone di comando per fargli trovare 6 tuberi di Foglia Azzurra. Riportali, con bastone e cassa, a Mebok Mizzyrix." },
        [1144] = { name = "Willix l'Importatore", objective = "Scorta Willix l'Importatore fuori dal Kraul di Lamaspina." },
        [1142] = { name = "La mortalità svanisce", objective = "Trova il ciondolo di Treshala e riportalo a Treshala Fallowbrook a Darnassus." },
        [1101] = { name = "La megera del Kraul", objective = "Porta il medaglione di Lamafianco a Falfindel Waywarder a Thalanaar." },
        [1102] = { name = "Un destino vendicativo", objective = "Porta il cuore di Lamafianco ad Auld Pietralta a Picco del Tuono." },
        [1109] = { name = "Guano, guano!", objective = "Porta 1 mucchio di guano del Kraul dei pipistrelli del Kraul al Gran Speziale Faranell." },
        [6522] = { name = "Un'alleanza empia", objective = "Porta la piccola pergamena a Varimathras a Sepulcra." },
        [1051] = { name = "La vendetta di Vorrel", objective = "Riporta la fede nuziale di Vorrel Sengutz (da Nancy Vishas) a Monika Sengutz a Mulino di Tarren." },
        [1113] = { name = "Cuori dello zelo", objective = "Porta 20 cuori dello zelo dal Monastero Scarlatto al Gran Speziale Faranell." },
    },
    places = {
        ["Ironforge"] = "Forgiardente",
        ["Kharanos"] = "Kharanos",
        ["Dun Morogh"] = "Dun Morogh",
        ["Stormwind City"] = "Roccavento",
        ["Stormwind"] = "Roccavento",
        ["Booty Bay"] = "Baia del Bottino",
        ["Stranglethorn Vale"] = "Valle di Rovotorto",
        ["Orgrimmar"] = "Orgrimmar",
        ["inside Gnomeregan"] = "dentro Gnomeregan",
        ["Ratchet"] = "Porto Paranco",
        ["The Barrens"] = "Savane",
        ["inside Razorfen Kraul"] = "dentro il Kraul di Lamaspina",
        ["Darnassus"] = "Darnassus",
        ["Thalanaar"] = "Thalanaar",
        ["Feralas"] = "Feralas",
        ["Thunder Bluff"] = "Picco del Tuono",
        ["Undercity"] = "Sepulcra",
        ["Royal Quarter"] = "Quartiere Reale",
        ["inside the Graveyard"] = "dentro il Cimitero",
        ["Tarren Mill"] = "Mulino di Tarren",
        ["Hillsbrad Foothills"] = "Colli di Monteverde",
        ["Dwarven District"] = "Distretto dei Nani",
        ["the Dwarven District"] = "Distretto dei Nani",
    },
}
DATA.ptBR = {
    dungeons = {
        ["Gnomeregan"] = { name = "Gnomeregan", location = "Dun Morogh", description = "A cidade subterrânea irradiada dos gnomos, tomada por troggs e pelas forças do Mekgenheiro Termaplugue." },
        ["Razorfen Kraul"] = { name = "Urzal dos Mortos", location = "Sertões", description = "Um enorme labirinto de espinhos ocupado pelos javali do Urzal dos Mortos." },
        ["Scarlet Monastery: Graveyard"] = { name = "Monastério Escarlate: Cemitério", location = "Clareiras de Tirisfal", description = "A ala do cemitério do Monastério Escarlate, assombrada por mortos inquietos e defensores escarlates." },
        ["City of Dalaran"] = { name = "Cidade de Dalaran", location = "Montanhas de Alterac", description = "A restaurada cidade dos magos, Dalaran, tornou-se uma nova masmorra para cinco jogadores no WoW Forever. Entre pelos esgotos e pelo Ventre, depois abra caminho pelas ruas até a Cidadela Violeta." },
        ["Excavation Site: Wetlands"] = { name = "Sítio de Escavação: Pantanal", location = "Pantanal", description = "Um sítio de escavação titânico preso no tempo acima da Escavação de Whelgar, onde os constructos titânicos não obedecem mais a ninguém. Áreas: Pântano Perdido, Mata dos Espreitadores, Local do Guardião e Escavação Perdida." },
    },
    quests = {
        [2930001] = { name = "Cartão Perfurado Branco", objective = "Mate inimigos na área externa de Gnomeregan até cair um cartão perfurado branco.", pickup = "Saqueadores e invasores das Cavernas, invasores irradiados e leprosos atordoados, fora da instância", turnin = "Guarde o cartão para a Perfuradora Matricial 3005-A", description = "Saque aleatório; normalmente você o consegue na primeira limpeza da área externa." },
        [2930002] = { name = "Cartão Perfurado Amarelo (perfuradora 3005-A)", objective = "Use a Perfuradora Matricial 3005-A com o cartão branco para obter um cartão perfurado amarelo.", pickup = "Perfuradora Matricial 3005-A, área da oficina do depósito de trens, fora da instância", turnin = "Você recebe um cartão perfurado amarelo", description = "As únicas perfuradoras fora da instância: na plataforma elevada do depósito e junto à entrada da oficina (porta dos fundos)." },
        [2930003] = { name = "Cartão Perfurado Azul (perfuradora 3005-B)", objective = "Use a Perfuradora Matricial 3005-B com o cartão amarelo para obter um cartão perfurado azul.", pickup = "Perfuradora Matricial 3005-B, o Dormitório (logo após a Zona Limpa), dentro da instância", turnin = "Você recebe um cartão perfurado azul", description = "Dentro da instância, no Dormitório." },
        [2930004] = { name = "Cartão Perfurado Vermelho (perfuradora 3005-C)", objective = "Use a Perfuradora Matricial 3005-C com o cartão azul para obter um cartão perfurado vermelho.", pickup = "Perfuradora Matricial 3005-C, plataforma superior da Baía de Lançamento com o Eletrocutor 6000", turnin = "Você recebe um cartão perfurado vermelho", description = "Na plataforma do Eletrocutor 6000." },
        [2930005] = { name = "Cartão Perfurado Prismático (perfuradora 3005-D)", objective = "Use a Perfuradora Matricial 3005-D com o cartão vermelho para obter o cartão perfurado prismático e leve-o ao Mestre Mecânico Canocasta em Altaforja.", pickup = "Perfuradora Matricial 3005-D, lado oeste do nível inferior dos Laboratórios de Engenharia", turnin = "Mestre Mecânico Canocasta, Beco da Gambiarra, Altaforja", description = "Desça de elevador; o terminal fica na primeira passagem à direita." },
        [2922] = { name = "Salve o Cérebro do Tecbô!", objective = "Leve o núcleo de memória do Tecbô ao Mestre Engenhoqueiro Faiscador em Altaforja." },
        [2926] = { name = "Gnogaína", objective = "Use o frasco de coleta plumbífero vazio em invasores ou saqueadores irradiados e leve o frasco cheio de volta a Ozzie Togglevolt." },
        [2962] = { name = "A única cura é mais brilho verde", objective = "Leve a Ozzie precipitação radioativa de alta potência e o frasco de coleta plumbífero pesado. A precipitação se desfaz rápido." },
        [2928] = { name = "Escavadeiras Girofurantes", objective = "Leve 24 entranhas robomecânicas a Shoni em Ventobravo." },
        [2924] = { name = "Artificiais Essenciais", objective = "Leve 12 artificiais essenciais a Klockmort Chaveinglesa em Altaforja." },
        [2930] = { name = "Resgate de Dados", objective = "Leve um cartão perfurado prismático ao Mestre Mecânico Canocasta em Altaforja." },
        [2929] = { name = "A Grande Traição", objective = "Mate o Mekgenheiro Termaplugue e volte ao Grão-Engenhoqueiro Mekkatorque." },
        [2843] = { name = "Gnomer-fooooi!", objective = "Espere Scooty calibrar o transponder goblin." },
        [2841] = { name = "Guerra das Plataformas", objective = "Recupere as plantas da plataforma e a combinação do cofre de Termaplugue e leve-as a Nogg em Orgrimmar." },
        [2904] = { name = "Uma Bela Bagunça", objective = "Escolte Kernobee até a saída da Passagem das Engrenagens e depois relate a Scooty na Angra do Butim." },
        [2951] = { name = "A Brilhomática 5200!", objective = "Coloque um objeto encardido na Brilhomática 5200 com três moedas de prata para ligar a máquina." },
        [2945] = { name = "Anel Encardido", objective = "Descubra um jeito de limpar o anel encardido (use a Brilhomática 5200)." },
        [1221] = { name = "Tubérculos de Folha-azul", objective = "Use o caixote furado para invocar um rato fuçador e o bastão de comando para fazê-lo achar 6 tubérculos de folha-azul. Leve-os, com o bastão e o caixote, a Mebok Mizzyrix." },
        [1144] = { name = "Willix, o Importador", objective = "Escolte Willix, o Importador, para fora do Urzal dos Mortos." },
        [1142] = { name = "A Mortalidade Míngua", objective = "Encontre o pingente de Treshala e devolva-o a Treshala Fallowbrook em Darnassus." },
        [1101] = { name = "A Bruxa do Urzal", objective = "Leve o medalhão de Navalhaflanco a Falfindel Waywarder em Thalanaar." },
        [1102] = { name = "Um Destino Vingativo", objective = "Leve o coração de Navalhaflanco a Auld Pedralta em Penhasco do Trovão." },
        [1109] = { name = "Guano, Guano!", objective = "Leve 1 monte de guano do Urzal dos morcegos do Urzal ao Boticário-mor Faranell." },
        [6522] = { name = "Uma Aliança Profana", objective = "Leve o pergaminho pequeno a Varimathras em Cidade Baixa." },
        [1051] = { name = "A Vingança de Vorrel", objective = "Devolva a aliança de casamento de Vorrel Sengutz (de Nancy Vishas) a Monika Sengutz em Serraria Tarren." },
        [1113] = { name = "Corações do Zelo", objective = "Leve 20 corações do zelo do Monastério Escarlate ao Boticário-mor Faranell." },
    },
    places = {
        ["Ironforge"] = "Altaforja",
        ["Kharanos"] = "Kharanos",
        ["Dun Morogh"] = "Dun Morogh",
        ["Stormwind City"] = "Ventobravo",
        ["Stormwind"] = "Ventobravo",
        ["Booty Bay"] = "Angra do Butim",
        ["Stranglethorn Vale"] = "Selva do Espinhaço",
        ["Orgrimmar"] = "Orgrimmar",
        ["inside Gnomeregan"] = "dentro de Gnomeregan",
        ["Ratchet"] = "Vila Catraca",
        ["The Barrens"] = "Sertões",
        ["inside Razorfen Kraul"] = "dentro do Urzal dos Mortos",
        ["Darnassus"] = "Darnassus",
        ["Thalanaar"] = "Thalanaar",
        ["Feralas"] = "Feralas",
        ["Thunder Bluff"] = "Penhasco do Trovão",
        ["Undercity"] = "Cidade Baixa",
        ["Royal Quarter"] = "Bairro Real",
        ["inside the Graveyard"] = "dentro do Cemitério",
        ["Tarren Mill"] = "Serraria Tarren",
        ["Hillsbrad Foothills"] = "Contraforte de Eira dos Montes",
        ["Dwarven District"] = "Distrito dos Anões",
        ["the Dwarven District"] = "Distrito dos Anões",
    },
}
DATA.ruRU = {
    dungeons = {
        ["Gnomeregan"] = { name = "Гномреган", location = "Дун Морог", description = "Облучённый подземный город гномов, захваченный троггами и войсками анжинера Термоштепселя." },
        ["Razorfen Kraul"] = { name = "Лабиринты Иглошкурых", location = "Степи", description = "Огромный терновый лабиринт, занятый свинобразами Лабиринтов Иглошкурых." },
        ["Scarlet Monastery: Graveyard"] = { name = "Монастырь Алого ордена: Кладбище", location = "Тирисфальские леса", description = "Кладбище Монастыря Алого ордена, где бродят неупокоенные мертвецы и защитники Алого ордена." },
        ["City of Dalaran"] = { name = "Город Даларан", location = "Альтеракские горы", description = "Восстановленный город магов Даларан стал новым подземельем для пяти игроков в WoW Forever. Войдите через канализацию и Клоаку, затем пробейтесь по улицам к Аметистовой цитадели." },
        ["Excavation Site: Wetlands"] = { name = "Раскопки: Болотина", location = "Болотина", description = "Застывшие во времени раскопки титанов над раскопками Вельгара, где конструкты титанов больше никому не подчиняются. Области: Затерянная топь, Чаща охотников, Место стража и Затерянные раскопки." },
    },
    quests = {
        [2930001] = { name = "Белая перфокарта", objective = "Убивайте противников во внешней части Гномрегана, пока не выпадет белая перфокарта.", pickup = "Грабители и захватчики глубин, облучённые захватчики и одурманенные прокажённые снаружи подземелья", turnin = "Сохраните карту для матричного перфоратора 3005-A", description = "Случайная добыча; обычно выпадает при первой зачистке внешней зоны." },
        [2930002] = { name = "Жёлтая перфокарта (перфоратор 3005-A)", objective = "Используйте матричный перфоратор 3005-A с белой перфокартой, чтобы получить жёлтую.", pickup = "Матричный перфоратор 3005-A, мастерская железнодорожного депо, снаружи подземелья", turnin = "Вы получаете жёлтую перфокарту", description = "Единственные перфораторы снаружи подземелья: на возвышенной платформе депо и у входа в мастерскую (чёрный ход)." },
        [2930003] = { name = "Синяя перфокарта (перфоратор 3005-B)", objective = "Используйте матричный перфоратор 3005-B с жёлтой перфокартой, чтобы получить синюю.", pickup = "Матричный перфоратор 3005-B, Спальный корпус (сразу за Чистой зоной), в подземелье", turnin = "Вы получаете синюю перфокарту", description = "В подземелье, в Спальном корпусе." },
        [2930004] = { name = "Красная перфокарта (перфоратор 3005-C)", objective = "Используйте матричный перфоратор 3005-C с синей перфокартой, чтобы получить красную.", pickup = "Матричный перфоратор 3005-C, верхняя платформа Пусковой площадки с Электрошокером 6000", turnin = "Вы получаете красную перфокарту", description = "На платформе Электрошокера 6000." },
        [2930005] = { name = "Призматическая перфокарта (перфоратор 3005-D)", objective = "Используйте матричный перфоратор 3005-D с красной перфокартой, чтобы получить призматическую, и отнесите её старшему механику Литотрубу в Стальгорн.", pickup = "Матричный перфоратор 3005-D, западная часть нижнего уровня Инженерных лабораторий", turnin = "Старший механик Литотруб, Город Механиков, Стальгорн", description = "Спуститесь на лифте; терминал в первом проходе справа." },
        [2922] = { name = "Спасите мозг Техбота!", objective = "Принесите ядро памяти Техбота мастеру-механику Искросвёрлу в Стальгорн." },
        [2926] = { name = "Гноген", objective = "Используйте пустой свинцовый флакон на облучённых захватчиках или грабителях и отнесите полный флакон Оззи Шестерёнкину." },
        [2962] = { name = "Зелёное свечение лечат зелёным свечением", objective = "Принесите Оззи мощные радиоактивные осадки и тяжёлый свинцовый флакон. Осадки быстро распадаются." },
        [2928] = { name = "Гиробуровые экскаваторы", objective = "Принесите 24 робомеханические потроха Шони в Штормград." },
        [2924] = { name = "Необходимые артефакты", objective = "Принесите 12 необходимых артефактов Клокморту Гаечнику в Стальгорн." },
        [2930] = { name = "Спасение данных", objective = "Принесите призматическую перфокарту старшему механику Литотрубу в Стальгорн." },
        [2929] = { name = "Великое предательство", objective = "Убейте анжинера Термоштепселя и вернитесь к Главному Механику Меккаторку." },
        [2843] = { name = "Гномре-уходиииим!", objective = "Подождите, пока Скути настроит гоблинский транспондер." },
        [2841] = { name = "Буровые войны", objective = "Добудьте чертежи буровой установки и комбинацию сейфа Термоштепселя и отнесите их Ноггу в Оргриммар." },
        [2904] = { name = "Ну и бардак", objective = "Сопроводите Керноби до выхода из Часового прохода, затем доложите Скути в Пиратской Бухте." },
        [2951] = { name = "Искромат 5200!", objective = "Поместите покрытый грязью предмет в Искромат 5200 и бросьте три серебряные монеты, чтобы запустить машину." },
        [2945] = { name = "Покрытое грязью кольцо", objective = "Найдите способ очистить покрытое грязью кольцо (используйте Искромат 5200)." },
        [1221] = { name = "Клубни синелиста", objective = "С помощью ящика с отверстиями призовите крысу-нюхача, а жезлом управления заставьте её найти 6 клубней синелиста. Принесите их вместе с жезлом и ящиком Мебоку Миззириксу." },
        [1144] = { name = "Импортёр Уилликс", objective = "Выведите импортёра Уилликса из Лабиринтов Иглошкурых." },
        [1142] = { name = "Угасание смертности", objective = "Найдите кулон Трешалы и верните его Трешале Фаллоубрук в Дарнас." },
        [1101] = { name = "Старуха из Лабиринтов", objective = "Принесите медальон Бритвобокой Фалфинделу Путнику в Таланаар." },
        [1102] = { name = "Мстительная судьба", objective = "Принесите сердце Бритвобокой Ольду Камневерху в Громовой Утёс." },
        [1109] = { name = "Гуано, гуано!", objective = "Принесите 1 кучку гуано из Лабиринтов от летучих мышей главному аптекарю Фаранеллу." },
        [6522] = { name = "Нечестивый союз", objective = "Отнесите маленький свиток Каримтрасу в Подгород." },
        [1051] = { name = "Месть Воррела", objective = "Верните обручальное кольцо Воррела Сенгуца (от Нэнси Вишас) Монике Сенгуц в Мельницу Таррен." },
        [1113] = { name = "Сердца рвения", objective = "Принесите 20 сердец рвения из Монастыря Алого ордена главному аптекарю Фаранеллу." },
    },
    places = {
        ["Ironforge"] = "Стальгорн",
        ["Kharanos"] = "Каранос",
        ["Dun Morogh"] = "Дун Морог",
        ["Stormwind City"] = "Штормград",
        ["Stormwind"] = "Штормград",
        ["Booty Bay"] = "Пиратская Бухта",
        ["Stranglethorn Vale"] = "Тернистая долина",
        ["Orgrimmar"] = "Оргриммар",
        ["inside Gnomeregan"] = "в Гномрегане",
        ["Ratchet"] = "Кабестан",
        ["The Barrens"] = "Степи",
        ["inside Razorfen Kraul"] = "в Лабиринтах Иглошкурых",
        ["Darnassus"] = "Дарнас",
        ["Thalanaar"] = "Таланаар",
        ["Feralas"] = "Фералас",
        ["Thunder Bluff"] = "Громовой Утёс",
        ["Undercity"] = "Подгород",
        ["Royal Quarter"] = "Королевский квартал",
        ["inside the Graveyard"] = "на Кладбище",
        ["Tarren Mill"] = "Мельница Таррен",
        ["Hillsbrad Foothills"] = "Предгорья Хилсбрада",
        ["Dwarven District"] = "Квартал дворфов",
        ["the Dwarven District"] = "Квартал дворфов",
    },
}
DATA.koKR = {
    dungeons = {
        ["Gnomeregan"] = { name = "놈리건", location = "던 모로", description = "방사능에 오염된 노움의 지하 도시로, 트로그와 텔마플러그의 병력에 점령당했습니다." },
        ["Razorfen Kraul"] = { name = "가시덩굴 우리", location = "불모의 땅", description = "가시덩굴 우리의 멧돼지인간이 차지한 거대한 가시 미로입니다." },
        ["Scarlet Monastery: Graveyard"] = { name = "붉은십자군 수도원: 묘지", location = "티리스팔 숲", description = "안식을 얻지 못한 망자와 붉은십자군 수호병이 출몰하는 붉은십자군 수도원의 묘지 구역입니다." },
        ["City of Dalaran"] = { name = "달라란 도시", location = "알터랙 산맥", description = "복원된 마법사의 도시 달라란이 WoW Forever의 새로운 5인 던전이 되었습니다. 하수도와 마법의 지하실을 통해 들어가 거리를 뚫고 보랏빛 성채까지 가세요." },
        ["Excavation Site: Wetlands"] = { name = "발굴지: 저습지", location = "저습지", description = "웰가르 발굴지 위에 시간 속에 갇힌 티탄 발굴지로, 티탄 피조물이 더 이상 누구에게도 복종하지 않습니다. 구역: 잃어버린 늪, 추적자의 덤불, 수호자의 터, 잃어버린 발굴지." },
    },
    quests = {
        [2930001] = { name = "흰색 천공 카드", objective = "놈리건 외곽 지역의 적을 처치해 흰색 천공 카드를 얻으세요.", pickup = "인스턴스 밖의 동굴 약탈자, 동굴 침략자, 방사능 오염 침략자, 정신 나간 나병 노움", turnin = "카드를 매트릭스 천공기 3005-A용으로 보관하세요", description = "무작위 전리품입니다. 보통 외곽 지역을 처음 정리할 때 얻습니다." },
        [2930002] = { name = "노란색 천공 카드 (천공기 3005-A)", objective = "흰색 천공 카드로 매트릭스 천공기 3005-A를 사용해 노란색 천공 카드를 얻으세요.", pickup = "매트릭스 천공기 3005-A, 기차 정거장의 작업장 구역, 인스턴스 밖", turnin = "노란색 천공 카드를 받습니다", description = "인스턴스 밖에 있는 유일한 천공기입니다. 정거장의 높은 단상과 작업장(뒷문) 입구 옆에 있습니다." },
        [2930003] = { name = "파란색 천공 카드 (천공기 3005-B)", objective = "노란색 천공 카드로 매트릭스 천공기 3005-B를 사용해 파란색 천공 카드를 얻으세요.", pickup = "매트릭스 천공기 3005-B, 숙소 (청정 구역 바로 다음), 인스턴스 안", turnin = "파란색 천공 카드를 받습니다", description = "인스턴스 안, 숙소에 있습니다." },
        [2930004] = { name = "빨간색 천공 카드 (천공기 3005-C)", objective = "파란색 천공 카드로 매트릭스 천공기 3005-C를 사용해 빨간색 천공 카드를 얻으세요.", pickup = "매트릭스 천공기 3005-C, 발사 기지 위쪽 단상 (일렉트로커셔너 6000)", turnin = "빨간색 천공 카드를 받습니다", description = "일렉트로커셔너 6000의 단상에 있습니다." },
        [2930005] = { name = "프리즘 천공 카드 (천공기 3005-D)", objective = "빨간색 천공 카드로 매트릭스 천공기 3005-D를 사용해 프리즘 천공 카드를 얻은 뒤, 아이언포지의 기계공 대가 캐스트파이프에게 가져가세요.", pickup = "매트릭스 천공기 3005-D, 기계공학 연구실 아래층 서쪽", turnin = "기계공 대가 캐스트파이프, 땜장이 마을, 아이언포지", description = "승강기로 내려가면 오른쪽 첫 번째 통로에 단말기가 있습니다." },
        [2922] = { name = "테크봇의 두뇌를 구하라!", objective = "테크봇의 기억 핵을 아이언포지의 땜장이 대가 오버스파크에게 가져가세요." },
        [2926] = { name = "노가인", objective = "빈 납 채집 약병을 방사능에 오염된 침략자나 약탈자에게 사용한 뒤, 가득 찬 약병을 오지 토글볼트에게 가져가세요." },
        [2962] = { name = "녹색 광채엔 녹색 광채뿐", objective = "고농도 방사능 낙진과 무거운 납 채집 약병을 오지에게 가져가세요. 낙진은 금방 붕괴합니다." },
        [2928] = { name = "자이로드릴 굴착기", objective = "로봇 기계 내장 24개를 스톰윈드의 쇼니에게 가져가세요." },
        [2924] = { name = "필수 인공물", objective = "필수 인공물 12개를 아이언포지의 클락모트 스패너스팬에게 가져가세요." },
        [2930] = { name = "데이터 구출", objective = "프리즘 천공 카드를 아이언포지의 기계공 대가 캐스트파이프에게 가져가세요." },
        [2929] = { name = "크나큰 배신", objective = "텔마플러그를 처치하고 고위 땜장이 멕카토크에게 돌아가세요." },
        [2843] = { name = "놈리건 탈출!", objective = "스쿠티가 고블린 전송기를 조정할 때까지 기다리세요." },
        [2841] = { name = "시추기 전쟁", objective = "시추기 설계도와 텔마플러그의 금고 비밀번호를 찾아 오그리마의 노그에게 가져가세요." },
        [2904] = { name = "엉망진창", objective = "커노비를 시계태엽 통로 출구까지 호위한 뒤 무법항의 스쿠티에게 보고하세요." },
        [2951] = { name = "반짝반짝 5200!", objective = "때 묻은 물건을 반짝반짝 5200에 넣고 은화 세 개를 넣어 기계를 작동하세요." },
        [2945] = { name = "때 묻은 반지", objective = "때 묻은 반지의 때를 벗길 방법을 찾으세요 (반짝반짝 5200을 사용하세요)." },
        [1221] = { name = "푸른잎 덩이줄기", objective = "구멍 난 상자로 킁킁코 쥐를 소환하고 명령 지팡이로 푸른잎 덩이줄기 6개를 찾게 하세요. 덩이줄기와 지팡이, 상자를 메보크 미지릭스에게 가져가세요." },
        [1144] = { name = "수입업자 윌릭스", objective = "수입업자 윌릭스를 가시덩굴 우리 밖으로 호위하세요." },
        [1142] = { name = "사라지는 죽음", objective = "트레샬라의 목걸이를 찾아 다르나서스의 트레샬라 팰로우브룩에게 돌려주세요." },
        [1101] = { name = "우리의 마녀", objective = "칼날갈기의 메달을 탈라나르의 팔핀델 웨이워더에게 가져가세요." },
        [1102] = { name = "복수의 운명", objective = "칼날갈기의 심장을 썬더 블러프의 아울드 스톤스파이어에게 가져가세요." },
        [1109] = { name = "박쥐 배설물!", objective = "가시덩굴 박쥐에게서 얻은 배설물 1개를 연금술사장 파라넬에게 가져가세요." },
        [6522] = { name = "불경한 동맹", objective = "작은 두루마리를 언더시티의 바리마트라스에게 가져가세요." },
        [1051] = { name = "보렐의 복수", objective = "보렐 센구츠의 결혼반지(낸시 비샤스에게서)를 타렌 밀의 모니카 센구츠에게 돌려주세요." },
        [1113] = { name = "열정의 심장", objective = "붉은십자군 수도원에서 열정의 심장 20개를 모아 연금술사장 파라넬에게 가져가세요." },
    },
    places = {
        ["Ironforge"] = "아이언포지",
        ["Kharanos"] = "카라노스",
        ["Dun Morogh"] = "던 모로",
        ["Stormwind City"] = "스톰윈드",
        ["Stormwind"] = "스톰윈드",
        ["Booty Bay"] = "무법항",
        ["Stranglethorn Vale"] = "가시덤불 골짜기",
        ["Orgrimmar"] = "오그리마",
        ["inside Gnomeregan"] = "놈리건 내부",
        ["Ratchet"] = "톱니항",
        ["The Barrens"] = "불모의 땅",
        ["inside Razorfen Kraul"] = "가시덩굴 우리 내부",
        ["Darnassus"] = "다르나서스",
        ["Thalanaar"] = "탈라나르",
        ["Feralas"] = "페랄라스",
        ["Thunder Bluff"] = "썬더 블러프",
        ["Undercity"] = "언더시티",
        ["Royal Quarter"] = "왕실 지구",
        ["inside the Graveyard"] = "묘지 내부",
        ["Tarren Mill"] = "타렌 밀",
        ["Hillsbrad Foothills"] = "힐스브래드 구릉지",
        ["Dwarven District"] = "드워프 지구",
        ["the Dwarven District"] = "드워프 지구",
    },
}
DATA.zhCN = {
    dungeons = {
        ["Gnomeregan"] = { name = "诺莫瑞根", location = "丹莫罗", description = "被辐射污染的侏儒地下城市，被穴居人和麦克尼尔·瑟玛普拉格的部队占领。" },
        ["Razorfen Kraul"] = { name = "剃刀沼泽", location = "贫瘠之地", description = "剃刀沼泽的野猪人盘踞的一座巨大荆棘迷宫。" },
        ["Scarlet Monastery: Graveyard"] = { name = "血色修道院：墓地", location = "提瑞斯法林地", description = "血色修道院的墓地区，游荡着不得安息的亡者和血色十字军的守卫。" },
        ["City of Dalaran"] = { name = "达拉然城", location = "奥特兰克山脉", description = "重建的法师之城达拉然成为了 WoW Forever 中新的五人地下城。从下水道和达拉然下水道进入，然后沿街道一路杀到紫罗兰城堡。" },
        ["Excavation Site: Wetlands"] = { name = "挖掘场：湿地", location = "湿地", description = "惠尔格挖掘场上方一处被困在时间中的泰坦挖掘场，那里的泰坦造物已不再服从任何人。区域：失落沼泽、潜伏者灌木林、守护者之地和失落挖掘场。" },
    },
    quests = {
        [2930001] = { name = "白色打孔卡", objective = "在诺莫瑞根外围区域击杀敌人，直到获得一张白色打孔卡。", pickup = "副本外的深洞掠夺者、深洞入侵者、受辐射的入侵者和昏乱的麻风侏儒", turnin = "保留这张卡，用于矩阵式打孔计算机3005-A", description = "随机掉落；通常第一次清理外围区域时就能拿到。" },
        [2930002] = { name = "黄色打孔卡（打孔机3005-A）", objective = "带着白色打孔卡使用矩阵式打孔计算机3005-A，获得黄色打孔卡。", pickup = "矩阵式打孔计算机3005-A，列车车站的车间区域，副本外", turnin = "你获得一张黄色打孔卡", description = "副本外仅有的打孔机：在车站的高台上，以及车间（后门）入口旁。" },
        [2930003] = { name = "蓝色打孔卡（打孔机3005-B）", objective = "带着黄色打孔卡使用矩阵式打孔计算机3005-B，获得蓝色打孔卡。", pickup = "矩阵式打孔计算机3005-B，宿舍（紧挨着洁净区），副本内", turnin = "你获得一张蓝色打孔卡", description = "在副本内的宿舍。" },
        [2930004] = { name = "红色打孔卡（打孔机3005-C）", objective = "带着蓝色打孔卡使用矩阵式打孔计算机3005-C，获得红色打孔卡。", pickup = "矩阵式打孔计算机3005-C，发射台上层平台（电刑器6000所在处）", turnin = "你获得一张红色打孔卡", description = "在电刑器6000的平台上。" },
        [2930005] = { name = "棱彩打孔卡（打孔机3005-D）", objective = "带着红色打孔卡使用矩阵式打孔计算机3005-D，获得棱彩打孔卡，然后交给铁炉堡的机械大师卡斯派普。", pickup = "矩阵式打孔计算机3005-D，工程实验室下层西侧", turnin = "机械大师卡斯派普，侏儒区，铁炉堡", description = "乘电梯下去，终端在右侧第一条通道里。" },
        [2922] = { name = "拯救尖端机器人的大脑！", objective = "把尖端机器人的记忆核心交给铁炉堡的工匠大师欧沃斯巴克。" },
        [2926] = { name = "诺恩", objective = "对受辐射的侵略者或掠夺者使用空的铅瓶，然后把装满的铅瓶交给奥齐·托格维尔。" },
        [2962] = { name = "以毒攻毒", objective = "把高能放射性尘埃和沉重的铅瓶交给奥齐。放射性尘埃会很快衰变。" },
        [2928] = { name = "陀螺挖掘机", objective = "把24个机械内脏交给暴风城的舒尼。" },
        [2924] = { name = "基础模组", objective = "把12个基础模组交给铁炉堡的克劳克莫特·斯班纳斯潘。" },
        [2930] = { name = "数据救援", objective = "把一张棱彩打孔卡交给铁炉堡的机械大师卡斯派普。" },
        [2929] = { name = "大叛徒", objective = "杀死麦克尼尔·瑟玛普拉格，然后回到大工匠梅卡托克那里。" },
        [2843] = { name = "诺莫瑞根撤离！", objective = "等待斯库提校准地精传送器。" },
        [2841] = { name = "钻塔之战", objective = "取回钻塔设计图和瑟玛普拉格的保险箱密码，交给奥格瑞玛的诺格。" },
        [2904] = { name = "一团糟", objective = "护送克努比到发条小径的出口，然后向藏宝海湾的斯库提报告。" },
        [2951] = { name = "闪光机5200！", objective = "把一件满是污垢的物品放进闪光机5200，并投入三枚银币启动机器。" },
        [2945] = { name = "满是污垢的戒指", objective = "想办法清除满是污垢的戒指上的污垢（使用闪光机5200）。" },
        [1221] = { name = "蓝叶薯", objective = "用带孔的箱子召唤一只嗅嗅鼠，用指挥棒让它找到6个蓝叶薯。把它们和指挥棒、箱子一起交给麦伯克·米希瑞克斯。" },
        [1144] = { name = "进口商威利克斯", objective = "护送进口商威利克斯离开剃刀沼泽。" },
        [1142] = { name = "消逝的凡人", objective = "找到特蕾莎拉的坠饰，交给达纳苏斯的特蕾莎拉·弗伦布鲁克。" },
        [1101] = { name = "沼泽的老巫婆", objective = "把卡尔加·刺肋的徽章交给萨兰纳尔的法芬德尔·维沃德。" },
        [1102] = { name = "复仇的命运", objective = "把卡尔加·刺肋的心脏交给雷霆崖的奥尔德·石塔。" },
        [1109] = { name = "鸟粪！", objective = "从沼泽蝙蝠身上取得1堆蝙蝠粪，交给首席药剂师法拉尼尔。" },
        [6522] = { name = "邪恶的联盟", objective = "把小卷轴交给幽暗城的瓦里玛萨斯。" },
        [1051] = { name = "沃瑞尔的复仇", objective = "把沃瑞尔·森古兹的结婚戒指（从南希·维沙斯处取得）交给塔伦米尔的莫妮卡·森古兹。" },
        [1113] = { name = "狂热之心", objective = "从血色修道院收集20颗狂热之心，交给首席药剂师法拉尼尔。" },
    },
    places = {
        ["Ironforge"] = "铁炉堡",
        ["Kharanos"] = "卡拉诺斯",
        ["Dun Morogh"] = "丹莫罗",
        ["Stormwind City"] = "暴风城",
        ["Stormwind"] = "暴风城",
        ["Booty Bay"] = "藏宝海湾",
        ["Stranglethorn Vale"] = "荆棘谷",
        ["Orgrimmar"] = "奥格瑞玛",
        ["inside Gnomeregan"] = "诺莫瑞根内",
        ["Ratchet"] = "棘齿城",
        ["The Barrens"] = "贫瘠之地",
        ["inside Razorfen Kraul"] = "剃刀沼泽内",
        ["Darnassus"] = "达纳苏斯",
        ["Thalanaar"] = "萨兰纳尔",
        ["Feralas"] = "菲拉斯",
        ["Thunder Bluff"] = "雷霆崖",
        ["Undercity"] = "幽暗城",
        ["Royal Quarter"] = "皇家区",
        ["inside the Graveyard"] = "墓地内",
        ["Tarren Mill"] = "塔伦米尔",
        ["Hillsbrad Foothills"] = "希尔斯布莱德丘陵",
        ["Dwarven District"] = "矮人区",
        ["the Dwarven District"] = "矮人区",
    },
}
DATA.zhTW = {
    dungeons = {
        ["Gnomeregan"] = { name = "諾姆瑞根", location = "丹莫洛", description = "被輻射汙染的侏儒地城市，被穴居人和麥克尼爾·瑟瑪普拉格的部隊佔領。" },
        ["Razorfen Kraul"] = { name = "剃刀沼澤", location = "貧瘠之地", description = "剃刀沼澤的野豬人盤踞的一座巨大荊棘迷宮。" },
        ["Scarlet Monastery: Graveyard"] = { name = "血色修道院：墓地", location = "提里斯法林地", description = "血色修道院的墓地區，遊蕩著不得安息的亡者和血色十字軍的守衛。" },
        ["City of Dalaran"] = { name = "達拉然城", location = "奧特蘭克山脈", description = "重建的法師之城達拉然成為了 WoW Forever 中新的五人地城。從下水道和達拉然下水道進入，然後沿街道一路殺到紫羅蘭城堡。" },
        ["Excavation Site: Wetlands"] = { name = "挖掘場：濕地", location = "濕地", description = "惠爾格挖掘場上方一處被困在時間中的泰坦挖掘場，那裡的泰坦造物已不再服從任何人。區域：失落沼澤、潛伏者灌木林、守護者之地和失落挖掘場。" },
    },
    quests = {
        [2930001] = { name = "白色打孔卡", objective = "在諾姆瑞根外圍區域擊殺敵人，直到獲得一張白色打孔卡。", pickup = "副本外的深洞掠奪者、深洞入侵者、受輻射的入侵者和昏亂的麻風侏儒", turnin = "保留這張卡，用於矩陣式打孔計算機3005-A", description = "隨機掉落；通常第一次清理外圍區域時就能拿到。" },
        [2930002] = { name = "黃色打孔卡（打孔機3005-A）", objective = "帶著白色打孔卡使用矩陣式打孔計算機3005-A，獲得黃色打孔卡。", pickup = "矩陣式打孔計算機3005-A，列車車站的車間區域，副本外", turnin = "你獲得一張黃色打孔卡", description = "副本外僅有的打孔機：在車站的高臺上，以及車間（後門）入口旁。" },
        [2930003] = { name = "藍色打孔卡（打孔機3005-B）", objective = "帶著黃色打孔卡使用矩陣式打孔計算機3005-B，獲得藍色打孔卡。", pickup = "矩陣式打孔計算機3005-B，宿舍（緊挨著潔淨區），副本內", turnin = "你獲得一張藍色打孔卡", description = "在副本內的宿舍。" },
        [2930004] = { name = "紅色打孔卡（打孔機3005-C）", objective = "帶著藍色打孔卡使用矩陣式打孔計算機3005-C，獲得紅色打孔卡。", pickup = "矩陣式打孔計算機3005-C，發射臺上層平臺（電刑器6000所在處）", turnin = "你獲得一張紅色打孔卡", description = "在電刑器6000的平臺上。" },
        [2930005] = { name = "稜彩打孔卡（打孔機3005-D）", objective = "帶著紅色打孔卡使用矩陣式打孔計算機3005-D，獲得稜彩打孔卡，然後交給鐵爐堡的機械大師卡斯派普。", pickup = "矩陣式打孔計算機3005-D，工程實驗室下層西側", turnin = "機械大師卡斯派普，侏儒區，鐵爐堡", description = "乘電梯下去，終端在右側第一條通道里。" },
        [2922] = { name = "拯救尖端機器人的大腦！", objective = "把尖端機器人的記憶核心交給鐵爐堡的工匠大師歐沃斯巴克。" },
        [2926] = { name = "諾恩", objective = "對受輻射的侵略者或掠奪者使用空的鉛瓶，然後把裝滿的鉛瓶交給奧齊·託格維爾。" },
        [2962] = { name = "以毒攻毒", objective = "把高能放射性塵埃和沉重的鉛瓶交給奧齊。放射性塵埃會很快衰變。" },
        [2928] = { name = "陀螺挖掘機", objective = "把24個機械內臟交給暴風城的舒尼。" },
        [2924] = { name = "基礎模組", objective = "把12個基礎模組交給鐵爐堡的克勞克莫特·斯班納斯潘。" },
        [2930] = { name = "資料救援", objective = "把一張稜彩打孔卡交給鐵爐堡的機械大師卡斯派普。" },
        [2929] = { name = "大叛徒", objective = "殺死麥克尼爾·瑟瑪普拉格，然後回到大工匠梅卡托克那裡。" },
        [2843] = { name = "諾姆瑞根撤離！", objective = "等待斯庫提校準地精傳送器。" },
        [2841] = { name = "鑽塔之戰", objective = "取回鑽塔設計圖和瑟瑪普拉格的保險箱密碼，交給奧格瑪的諾格。" },
        [2904] = { name = "一團糟", objective = "護送克努比到發條小徑的出口，然後向藏寶海灣的斯庫提報告。" },
        [2951] = { name = "閃光機5200！", objective = "把一件滿是汙垢的物品放進閃光機5200，並投入三枚銀幣啟動機器。" },
        [2945] = { name = "滿是汙垢的戒指", objective = "想辦法清除滿是汙垢的戒指上的汙垢（使用閃光機5200）。" },
        [1221] = { name = "藍葉薯", objective = "用帶孔的箱子召喚一隻嗅嗅鼠，用指揮棒讓它找到6個藍葉薯。把它們和指揮棒、箱子一起交給麥伯克·米希瑞克斯。" },
        [1144] = { name = "進口商威利克斯", objective = "護送進口商威利克斯離開剃刀沼澤。" },
        [1142] = { name = "消逝的凡人", objective = "找到特蕾莎拉的墜飾，交給達納蘇斯的特蕾莎拉·弗倫布魯克。" },
        [1101] = { name = "沼澤的老巫婆", objective = "把卡爾加·刺肋的徽章交給薩蘭納爾的法芬德爾·維沃德。" },
        [1102] = { name = "復仇的命運", objective = "把卡爾加·刺肋的心臟交給雷霆崖的奧爾德·石塔。" },
        [1109] = { name = "鳥糞！", objective = "從沼澤蝙蝠身上取得1堆蝙蝠糞，交給首席藥劑師法拉尼爾。" },
        [6522] = { name = "邪惡的聯盟", objective = "把小卷軸交給幽暗城的瓦里瑪薩斯。" },
        [1051] = { name = "沃瑞爾的復仇", objective = "把沃瑞爾·森古茲的結婚戒指（從南希·維沙斯處取得）交給塔倫米爾的莫妮卡·森古茲。" },
        [1113] = { name = "狂熱之心", objective = "從血色修道院收集20顆狂熱之心，交給首席藥劑師法拉尼爾。" },
    },
    places = {
        ["Ironforge"] = "鐵爐堡",
        ["Kharanos"] = "卡拉諾斯",
        ["Dun Morogh"] = "丹莫洛",
        ["Stormwind City"] = "暴風城",
        ["Stormwind"] = "暴風城",
        ["Booty Bay"] = "藏寶海灣",
        ["Stranglethorn Vale"] = "荊棘谷",
        ["Orgrimmar"] = "奧格瑪",
        ["inside Gnomeregan"] = "諾姆瑞根內",
        ["Ratchet"] = "棘齒城",
        ["The Barrens"] = "貧瘠之地",
        ["inside Razorfen Kraul"] = "剃刀沼澤內",
        ["Darnassus"] = "達納蘇斯",
        ["Thalanaar"] = "薩蘭納爾",
        ["Feralas"] = "菲拉斯",
        ["Thunder Bluff"] = "雷霆崖",
        ["Undercity"] = "幽暗城",
        ["Royal Quarter"] = "皇家區",
        ["inside the Graveyard"] = "墓地內",
        ["Tarren Mill"] = "塔倫米爾",
        ["Hillsbrad Foothills"] = "希爾斯布萊德丘陵",
        ["Dwarven District"] = "矮人區",
        ["the Dwarven District"] = "矮人區",
    },
}

for lang, data in pairs(DATA) do
    local target = FDJ.ContentLocales[lang] or {}
    FDJ.ContentLocales[lang] = target
    for _, field in ipairs({ "dungeons", "quests", "places" }) do
        target[field] = target[field] or {}
        for key, value in pairs(data[field]) do
            if target[field][key] == nil then target[field][key] = value end
        end
    end
end

-- Excavation Site: Wetlands quests: whole-string translations (names,
-- objectives, notes, NPC/place lines). Merged without overwriting.
local EXC = {}
EXC.deDE = {
    ["Open the Maw"] = "Das Maul öffnen",
    ["Changing Tastes"] = "Geschmackswandel",
    ["Elder Knowledge"] = "Uraltes Wissen",
    ["Highland Hides"] = "Hochlandhäute",
    ["Songblade Search"] = "Songblades Suche",
    ["Horrors in the Highland"] = "Schrecken im Hochland",
    ["Heartwoven"] = "Herzgeflecht",
    ["Lost Relic Carry"] = "Verlorener Relikttransport",
    ["Lost in the Thicket Things"] = "Verloren im Dickicht",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "Bringt die Dragonmaw Dispatch zum Deathstalker Agent direkt vor der Ausgrabungsstätte: Sumpfland.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Der Deathstalker Agent wartet im neuen Grabungslager direkt vor dem Portal. Er nimmt euch die Dragonmaw Dispatch ab; wo sie zu finden ist, wurde noch nicht bestätigt.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "Betretet die Ausgrabungsstätten im Sumpfland und bringt 4 Thicket Raptor Meat zurück.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat stammt von den Dickichtraptoren (Thicket Lurker, Thicket Hunter, Thicket Matriarch) im Pirscherdickicht, dem Gebiet von Shadetooth.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (gedroppt von Relic Guardian)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Bringt das Titan Relic zur Ältestenhöhe in Donnerfels und sucht jemanden, der euch mehr darüber erzählen kann.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "Jemand auf der Ältestenhöhe, Donnerfels",
    ["Objective not confirmed yet."] = "Ziel noch nicht bestätigt.",
    ["Not confirmed yet"] = "Noch nicht bestätigt",
    ["Complete Daily Delivery first."] = "Schließt zuerst Daily Delivery ab.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "Sucht Dorin Songblades Bruder Daewyn in Whelgars Ausgrabungsstätte.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "Tötet einen Highland Horror in den Ausgrabungsstätten und bringt seinen Wurzelkern zu Rethiel the Greenwarden im Sumpfland.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "Kehrt zu Caitlin Grassman in Menethil zurück.",
    ["Follow-up of Lost in the Thicket Things."] = "Folgequest von Verloren im Dickicht.",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "Findet Ardin Grassman in den Ausgrabungsstätten. Erfahrt, was mit Ardin Grassman geschehen ist.",
    ["Required before Heartwoven."] = "Voraussetzung für Herzgeflecht.",
    ["Start Lost in the Thicket Things here"] = "Hier beginnt Verloren im Dickicht",
    ["Menethil Harbor"] = "Menethil",
    ["Redridge Mountains"] = "Rotkammgebirge",
    ["Wetlands"] = "Sumpfland",
    ["inside Excavation Site: Wetlands"] = "in der Ausgrabungsstätte: Sumpfland",
    ["just outside Excavation Site: Wetlands"] = "direkt vor der Ausgrabungsstätte: Sumpfland",
    ["outside Excavation Site: Wetlands"] = "vor der Ausgrabungsstätte: Sumpfland",
}
EXC.frFR = {
    ["Open the Maw"] = "Ouvrir la Gueule",
    ["Changing Tastes"] = "Changement de goûts",
    ["Elder Knowledge"] = "Savoir ancestral",
    ["Highland Hides"] = "Peaux des hautes terres",
    ["Songblade Search"] = "Recherche de Songblade",
    ["Horrors in the Highland"] = "Horreurs des hautes terres",
    ["Heartwoven"] = "Cœur tressé",
    ["Lost Relic Carry"] = "Transport de relique perdue",
    ["Lost in the Thicket Things"] = "Perdu dans les fourrés",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "Apportez la Dragonmaw Dispatch au Deathstalker Agent, juste à l'extérieur du site de fouilles : Les Paluns.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Le Deathstalker Agent attend au nouveau camp de fouilles, juste devant le portail. Il récupère la Dragonmaw Dispatch ; l'endroit où l'obtenir n'est pas encore confirmé.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "Entrez dans les sites de fouilles des Paluns et rapportez 4 Thicket Raptor Meat.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat provient des raptors du fourré (Thicket Lurker, Thicket Hunter, Thicket Matriarch) dans le Fourré des traqueurs, la zone de Shadetooth.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (obtenue sur Relic Guardian)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Apportez la Titan Relic à l'Éminence des Anciens aux Pitons-du-Tonnerre et trouvez quelqu'un qui pourra vous en dire plus.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "Quelqu'un à l'Éminence des Anciens, Les Pitons-du-Tonnerre",
    ["Objective not confirmed yet."] = "Objectif pas encore confirmé.",
    ["Not confirmed yet"] = "Pas encore confirmé",
    ["Complete Daily Delivery first."] = "Terminez d'abord Daily Delivery.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "Cherchez Daewyn, le frère de Dorin Songblade, au site de fouilles de Whelgar.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "Tuez un Highland Horror dans les sites de fouilles et rapportez son noyau racine à Rethiel the Greenwarden aux Paluns.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "Retournez voir Caitlin Grassman à Havre-de-Menethil.",
    ["Follow-up of Lost in the Thicket Things."] = "Suite de Perdu dans les fourrés.",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "Trouvez Ardin Grassman dans les sites de fouilles. Apprenez ce qui lui est arrivé.",
    ["Required before Heartwoven."] = "Prérequis de Cœur tressé.",
    ["Start Lost in the Thicket Things here"] = "C'est ici que commence Perdu dans les fourrés",
    ["Menethil Harbor"] = "Havre-de-Menethil",
    ["Redridge Mountains"] = "Les Carmines",
    ["Wetlands"] = "Les Paluns",
    ["inside Excavation Site: Wetlands"] = "dans le site de fouilles : Les Paluns",
    ["just outside Excavation Site: Wetlands"] = "juste à l'extérieur du site de fouilles : Les Paluns",
    ["outside Excavation Site: Wetlands"] = "à l'extérieur du site de fouilles : Les Paluns",
}
EXC.esES = {
    ["Open the Maw"] = "Abrir las Fauces",
    ["Changing Tastes"] = "Cambio de gustos",
    ["Elder Knowledge"] = "Conocimiento ancestral",
    ["Highland Hides"] = "Pieles de las Tierras Altas",
    ["Songblade Search"] = "Búsqueda de Songblade",
    ["Horrors in the Highland"] = "Horrores de las Tierras Altas",
    ["Heartwoven"] = "Corazón entretejido",
    ["Lost Relic Carry"] = "Transporte de reliquia perdida",
    ["Lost in the Thicket Things"] = "Perdido en la espesura",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "Lleva el Dragonmaw Dispatch al Deathstalker Agent, justo a las afueras de la Excavación: Los Humedales.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "El Deathstalker Agent espera en el nuevo campamento de excavación, justo a la entrada del portal. Él se encarga del Dragonmaw Dispatch; aún no está confirmado dónde se consigue.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "Entra en las excavaciones de Los Humedales y trae 4 Thicket Raptor Meat.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat se consigue de los raptores del matorral (Thicket Lurker, Thicket Hunter, Thicket Matriarch) en la Espesura del Acechador, la zona de Shadetooth.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (la suelta Relic Guardian)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Lleva la Titan Relic al Alto de los Ancianos en Cima del Trueno y busca a alguien que pueda contarte más sobre ella.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "Alguien en el Alto de los Ancianos, Cima del Trueno",
    ["Objective not confirmed yet."] = "Objetivo aún sin confirmar.",
    ["Not confirmed yet"] = "Aún sin confirmar",
    ["Complete Daily Delivery first."] = "Completa primero Daily Delivery.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "Busca a Daewyn, el hermano de Dorin Songblade, en la Excavación de Whelgar.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "Mata a un Highland Horror en las excavaciones y lleva su núcleo de raíz a Rethiel the Greenwarden en Los Humedales.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "Regresa con Caitlin Grassman en el Puerto de Menethil.",
    ["Follow-up of Lost in the Thicket Things."] = "Continuación de Perdido en la espesura.",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "Encuentra a Ardin Grassman en las excavaciones. Averigua qué le ha pasado.",
    ["Required before Heartwoven."] = "Requisito previo de Corazón entretejido.",
    ["Start Lost in the Thicket Things here"] = "Aquí empieza Perdido en la espesura",
    ["Menethil Harbor"] = "Puerto de Menethil",
    ["Redridge Mountains"] = "Montañas Crestagrana",
    ["Wetlands"] = "Los Humedales",
    ["inside Excavation Site: Wetlands"] = "dentro de la Excavación: Los Humedales",
    ["just outside Excavation Site: Wetlands"] = "justo a las afueras de la Excavación: Los Humedales",
    ["outside Excavation Site: Wetlands"] = "a las afueras de la Excavación: Los Humedales",
}
EXC.itIT = {
    ["Open the Maw"] = "Aprire le Fauci",
    ["Changing Tastes"] = "Cambio di gusti",
    ["Elder Knowledge"] = "Conoscenza antica",
    ["Highland Hides"] = "Pelli degli Altipiani",
    ["Songblade Search"] = "Ricerca di Songblade",
    ["Horrors in the Highland"] = "Orrori degli Altipiani",
    ["Heartwoven"] = "Cuore intrecciato",
    ["Lost Relic Carry"] = "Trasporto di reliquia perduta",
    ["Lost in the Thicket Things"] = "Perso nel Boschetto",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "Porta il Dragonmaw Dispatch al Deathstalker Agent, appena fuori dal Sito di scavo: Paludi.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Il Deathstalker Agent aspetta nel nuovo accampamento di scavo, proprio fuori dal portale. Prende il Dragonmaw Dispatch; dove si ottiene non è ancora confermato.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "Entra nei siti di scavo delle Paludi e riporta 4 Thicket Raptor Meat.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat proviene dai raptor del boschetto (Thicket Lurker, Thicket Hunter, Thicket Matriarch) nel Boschetto dei Predatori, l'area di Shadetooth.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (rilasciata da Relic Guardian)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Porta la Titan Relic all'Altura degli Anziani a Picco del Tuono e cerca qualcuno che possa dirti di più.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "Qualcuno all'Altura degli Anziani, Picco del Tuono",
    ["Objective not confirmed yet."] = "Obiettivo non ancora confermato.",
    ["Not confirmed yet"] = "Non ancora confermato",
    ["Complete Daily Delivery first."] = "Completa prima Daily Delivery.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "Cerca Daewyn, il fratello di Dorin Songblade, nello Scavo di Whelgar.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "Uccidi un Highland Horror nei siti di scavo e porta il suo nucleo di radici a Rethiel the Greenwarden nelle Paludi.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "Torna da Caitlin Grassman a Porto di Menethil.",
    ["Follow-up of Lost in the Thicket Things."] = "Seguito di Perso nel Boschetto.",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "Trova Ardin Grassman nei siti di scavo. Scopri che cosa gli è successo.",
    ["Required before Heartwoven."] = "Da completare prima di Cuore intrecciato.",
    ["Start Lost in the Thicket Things here"] = "Qui inizia Perso nel Boschetto",
    ["Menethil Harbor"] = "Porto di Menethil",
    ["Redridge Mountains"] = "Redridge Mountains",
    ["Wetlands"] = "Paludi",
    ["inside Excavation Site: Wetlands"] = "dentro il Sito di scavo: Paludi",
    ["just outside Excavation Site: Wetlands"] = "appena fuori dal Sito di scavo: Paludi",
    ["outside Excavation Site: Wetlands"] = "fuori dal Sito di scavo: Paludi",
}
EXC.ptBR = {
    ["Open the Maw"] = "Abrir as Fauces",
    ["Changing Tastes"] = "Mudança de Gosto",
    ["Elder Knowledge"] = "Conhecimento Ancestral",
    ["Highland Hides"] = "Couros das Terras Altas",
    ["Songblade Search"] = "Busca por Songblade",
    ["Horrors in the Highland"] = "Horrores das Terras Altas",
    ["Heartwoven"] = "Coração Trançado",
    ["Lost Relic Carry"] = "Transporte de Relíquia Perdida",
    ["Lost in the Thicket Things"] = "Perdido no Matagal",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "Leve o Dragonmaw Dispatch ao Deathstalker Agent, logo fora do Sítio de Escavação: Pantanal.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "O Deathstalker Agent espera no novo acampamento de escavação, logo na saída do portal. Ele recebe o Dragonmaw Dispatch; onde conseguir o item ainda não foi confirmado.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "Entre nos sítios de escavação do Pantanal e traga 4 Thicket Raptor Meat.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat vem dos raptores do matagal (Thicket Lurker, Thicket Hunter, Thicket Matriarch) no Matagal dos Espreitadores, a área de Shadetooth.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (dropada por Relic Guardian)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Leve a Titan Relic ao Alto dos Anciões em Penhasco do Trovão e procure alguém que possa lhe contar mais sobre ela.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "Alguém no Alto dos Anciões, Penhasco do Trovão",
    ["Objective not confirmed yet."] = "Objetivo ainda não confirmado.",
    ["Not confirmed yet"] = "Ainda não confirmado",
    ["Complete Daily Delivery first."] = "Conclua Daily Delivery primeiro.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "Procure Daewyn, irmão de Dorin Songblade, na Escavação de Whelgar.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "Mate um Highland Horror nos sítios de escavação e leve o núcleo de raiz dele a Rethiel the Greenwarden no Pantanal.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "Volte para Caitlin Grassman em Porto Menethil.",
    ["Follow-up of Lost in the Thicket Things."] = "Continuação de Perdido no Matagal.",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "Encontre Ardin Grassman nos sítios de escavação. Descubra o que aconteceu com ele.",
    ["Required before Heartwoven."] = "Requisito antes de Coração Trançado.",
    ["Start Lost in the Thicket Things here"] = "Comece Perdido no Matagal aqui",
    ["Menethil Harbor"] = "Porto Menethil",
    ["Redridge Mountains"] = "Redridge Mountains",
    ["Wetlands"] = "Pantanal",
    ["inside Excavation Site: Wetlands"] = "dentro do Sítio de Escavação: Pantanal",
    ["just outside Excavation Site: Wetlands"] = "logo fora do Sítio de Escavação: Pantanal",
    ["outside Excavation Site: Wetlands"] = "fora do Sítio de Escavação: Pantanal",
}
EXC.ruRU = {
    ["Open the Maw"] = "Раскрыть Пасть",
    ["Changing Tastes"] = "Перемена вкусов",
    ["Elder Knowledge"] = "Древнее знание",
    ["Highland Hides"] = "Шкуры нагорья",
    ["Songblade Search"] = "Поиски Songblade",
    ["Horrors in the Highland"] = "Ужасы нагорья",
    ["Heartwoven"] = "Сплетённое сердце",
    ["Lost Relic Carry"] = "Перевозка утерянной реликвии",
    ["Lost in the Thicket Things"] = "Затерянные в зарослях",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "Отнесите Dragonmaw Dispatch к Deathstalker Agent прямо у входа в раскопки: Болотина.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Deathstalker Agent ждёт в новом лагере раскопок прямо у портала. Он заберёт у вас Dragonmaw Dispatch; где его добыть, пока не подтверждено.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "Войдите в раскопки в Болотине и принесите 4 Thicket Raptor Meat.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat выпадает из рапторов зарослей (Thicket Lurker, Thicket Hunter, Thicket Matriarch) в Чаще охотников — области Shadetooth.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (выпадает из Relic Guardian)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Отнесите Titan Relic на Возвышенность старейшин в Громовом Утёсе и найдите того, кто расскажет о ней больше.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "Кто-то на Возвышенности старейшин, Громовой Утёс",
    ["Objective not confirmed yet."] = "Задача пока не подтверждена.",
    ["Not confirmed yet"] = "Пока не подтверждено",
    ["Complete Daily Delivery first."] = "Сначала выполните Daily Delivery.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "Найдите Daewyn, брата Dorin Songblade, на раскопках Вельгара.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "Убейте Highland Horror на раскопках и принесите его корневое ядро Rethiel the Greenwarden в Болотину.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "Вернитесь к Caitlin Grassman в Гавань Менетил.",
    ["Follow-up of Lost in the Thicket Things."] = "Продолжение задания «Затерянные в зарослях».",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "Найдите Ardin Grassman на раскопках. Узнайте, что с ним случилось.",
    ["Required before Heartwoven."] = "Необходимо выполнить перед «Сплетённое сердце».",
    ["Start Lost in the Thicket Things here"] = "Здесь начинается «Затерянные в зарослях»",
    ["Menethil Harbor"] = "Гавань Менетил",
    ["Redridge Mountains"] = "Красногорье",
    ["Wetlands"] = "Болотина",
    ["inside Excavation Site: Wetlands"] = "внутри раскопок: Болотина",
    ["just outside Excavation Site: Wetlands"] = "прямо у входа в раскопки: Болотина",
    ["outside Excavation Site: Wetlands"] = "у входа в раскопки: Болотина",
}
EXC.koKR = {
    ["Open the Maw"] = "아가리 열기",
    ["Changing Tastes"] = "바뀌는 입맛",
    ["Elder Knowledge"] = "원로의 지식",
    ["Highland Hides"] = "고지대 가죽",
    ["Songblade Search"] = "송블레이드 수색",
    ["Horrors in the Highland"] = "고지대의 공포",
    ["Heartwoven"] = "마음으로 엮다",
    ["Lost Relic Carry"] = "분실된 유물 운반",
    ["Lost in the Thicket Things"] = "덤불 속에서 길을 잃다",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "발굴지: 저습지 바로 바깥에 있는 Deathstalker Agent에게 Dragonmaw Dispatch를 가져가세요.",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Deathstalker Agent는 포털 바로 바깥의 새 발굴 야영지에 있습니다. Dragonmaw Dispatch를 받아 가며, 입수처는 아직 확인되지 않았습니다.",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "저습지의 발굴지에 들어가 Thicket Raptor Meat 4개를 가져오세요.",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat는 추적자의 덤불에 있는 덤불 랩터(Thicket Lurker, Thicket Hunter, Thicket Matriarch)에게서 얻습니다. Shadetooth가 있는 구역입니다.",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic (Relic Guardian이 떨어뜨림)",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "Titan Relic을 썬더 블러프의 원로의 언덕으로 가져가 이에 대해 더 알려줄 사람을 찾으세요.",
    ["Someone on the Elder Rise, Thunder Bluff"] = "썬더 블러프 원로의 언덕에 있는 누군가",
    ["Objective not confirmed yet."] = "목표가 아직 확인되지 않았습니다.",
    ["Not confirmed yet"] = "아직 확인되지 않음",
    ["Complete Daily Delivery first."] = "먼저 Daily Delivery를 완료하세요.",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "웰가르 발굴지에서 Dorin Songblade의 동생 Daewyn을 찾으세요.",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "발굴지에서 Highland Horror를 처치하고 그 뿌리 핵을 저습지의 Rethiel the Greenwarden에게 가져가세요.",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "메네실 항구의 Caitlin Grassman에게 돌아가세요.",
    ["Follow-up of Lost in the Thicket Things."] = "'덤불 속에서 길을 잃다'의 후속 퀘스트입니다.",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "발굴지에서 Ardin Grassman을 찾으세요. Ardin Grassman에게 무슨 일이 있었는지 알아보세요.",
    ["Required before Heartwoven."] = "'마음으로 엮다' 전에 완료해야 합니다.",
    ["Start Lost in the Thicket Things here"] = "여기서 '덤불 속에서 길을 잃다'를 시작합니다",
    ["Menethil Harbor"] = "메네실 항구",
    ["Redridge Mountains"] = "붉은마루 산맥",
    ["Wetlands"] = "저습지",
    ["inside Excavation Site: Wetlands"] = "발굴지: 저습지 내부",
    ["just outside Excavation Site: Wetlands"] = "발굴지: 저습지 바로 바깥",
    ["outside Excavation Site: Wetlands"] = "발굴지: 저습지 바깥",
}
EXC.zhCN = {
    ["Open the Maw"] = "打开巨口",
    ["Changing Tastes"] = "口味之变",
    ["Elder Knowledge"] = "长者的知识",
    ["Highland Hides"] = "高地兽皮",
    ["Songblade Search"] = "寻找Songblade",
    ["Horrors in the Highland"] = "高地惊魂",
    ["Heartwoven"] = "心编",
    ["Lost Relic Carry"] = "遗失遗物运送",
    ["Lost in the Thicket Things"] = "迷失于灌丛",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "把Dragonmaw Dispatch交给挖掘场：湿地外面的Deathstalker Agent。",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Deathstalker Agent在传送门外的新挖掘营地等候。他会接收Dragonmaw Dispatch；获取方式尚未确认。",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "进入湿地的挖掘场，带回4个Thicket Raptor Meat。",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat来自潜伏者灌木林（Shadetooth所在区域）的灌丛迅猛龙（Thicket Lurker、Thicket Hunter、Thicket Matriarch）。",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic（由Relic Guardian掉落）",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "把Titan Relic带到雷霆崖的长者高地，找一个能告诉你更多相关信息的人。",
    ["Someone on the Elder Rise, Thunder Bluff"] = "雷霆崖长者高地上的某人",
    ["Objective not confirmed yet."] = "目标尚未确认。",
    ["Not confirmed yet"] = "尚未确认",
    ["Complete Daily Delivery first."] = "请先完成Daily Delivery。",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "在惠尔格挖掘场寻找Dorin Songblade的兄弟Daewyn。",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "在挖掘场击杀一只Highland Horror，把它的根核交给湿地的Rethiel the Greenwarden。",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "回到米奈希尔港的Caitlin Grassman那里。",
    ["Follow-up of Lost in the Thicket Things."] = "“迷失于灌丛”的后续任务。",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "在挖掘场找到Ardin Grassman，查明Ardin Grassman出了什么事。",
    ["Required before Heartwoven."] = "是“心编”的前置任务。",
    ["Start Lost in the Thicket Things here"] = "在此开始“迷失于灌丛”",
    ["Menethil Harbor"] = "米奈希尔港",
    ["Redridge Mountains"] = "赤脊山",
    ["Wetlands"] = "湿地",
    ["inside Excavation Site: Wetlands"] = "挖掘场：湿地内部",
    ["just outside Excavation Site: Wetlands"] = "挖掘场：湿地正外方",
    ["outside Excavation Site: Wetlands"] = "挖掘场：湿地外面",
}
EXC.zhTW = {
    ["Open the Maw"] = "開啟巨口",
    ["Changing Tastes"] = "口味之變",
    ["Elder Knowledge"] = "長者的知識",
    ["Highland Hides"] = "高地獸皮",
    ["Songblade Search"] = "尋找Songblade",
    ["Horrors in the Highland"] = "高地驚魂",
    ["Heartwoven"] = "心編",
    ["Lost Relic Carry"] = "遺失遺物運送",
    ["Lost in the Thicket Things"] = "迷失於灌叢",
    ["Bring the Dragonmaw Dispatch to the Deathstalker Agent just outside Excavation Site: Wetlands."] = "把Dragonmaw Dispatch交給挖掘場：濕地外面的Deathstalker Agent。",
    ["The Deathstalker Agent waits at the new dig camp right outside the portal. He takes the Dragonmaw Dispatch off your hands; where the Dispatch drops has not been confirmed yet."] = "Deathstalker Agent在傳送門外的新挖掘營地等候。他會接收Dragonmaw Dispatch；獲取方式尚未確認。",
    ["Enter the Excavation Sites in the Wetlands and bring back 4 Thicket Raptor Meat."] = "進入濕地的挖掘場，帶回4個Thicket Raptor Meat。",
    ["Thicket Raptor Meat comes from the Thicket raptors (Thicket Lurker, Thicket Hunter, Thicket Matriarch) in Stalker's Thicket, the area of Shadetooth."] = "Thicket Raptor Meat來自潛伏者灌木林（Shadetooth所在區域）的灌叢迅猛龍（Thicket Lurker、Thicket Hunter、Thicket Matriarch）。",
    ["Titan Relic (dropped by Relic Guardian)"] = "Titan Relic（由Relic Guardian掉落）",
    ["Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it."] = "把Titan Relic帶到雷霆崖的長者高地，找一個能告訴你更多相關資訊的人。",
    ["Someone on the Elder Rise, Thunder Bluff"] = "雷霆崖長者高地上的某人",
    ["Objective not confirmed yet."] = "目標尚未確認。",
    ["Not confirmed yet"] = "尚未確認",
    ["Complete Daily Delivery first."] = "請先完成Daily Delivery。",
    ["Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site."] = "在惠爾格挖掘場尋找Dorin Songblade的兄弟Daewyn。",
    ["Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands."] = "在挖掘場擊殺一隻Highland Horror，把它的根核交給濕地的Rethiel the Greenwarden。",
    ["Return to Caitlin Grassman in Menethil Harbor."] = "回到米奈希爾港的Caitlin Grassman那裡。",
    ["Follow-up of Lost in the Thicket Things."] = "“迷失於灌叢”的後續任務。",
    ["Find Ardin Grassman in the Excavation Sites. Learn what happened to Ardin Grassman."] = "在挖掘場找到Ardin Grassman，查明Ardin Grassman出了什麼事。",
    ["Required before Heartwoven."] = "是“心編”的前置任務。",
    ["Start Lost in the Thicket Things here"] = "在此開始“迷失於灌叢”",
    ["Menethil Harbor"] = "米奈希爾港",
    ["Redridge Mountains"] = "赤脊山",
    ["Wetlands"] = "濕地",
    ["inside Excavation Site: Wetlands"] = "挖掘場：濕地內部",
    ["just outside Excavation Site: Wetlands"] = "挖掘場：濕地正外方",
    ["outside Excavation Site: Wetlands"] = "挖掘場：濕地外面",
}
for lang, strings in pairs(EXC) do
    local target = FDJ.ContentLocales[lang] or {}
    FDJ.ContentLocales[lang] = target
    target.places = target.places or {}
    for key, value in pairs(strings) do
        if target.places[key] == nil then target.places[key] = value end
    end
end
