local ADDON_NAME, FDJ = ...
FDJ = FDJ or _G.ForeverDungeonJournal_NS
FDJ.ContentLocales = FDJ.ContentLocales or {}
FDJ.ContentLocales.esES = FDJ.ContentLocales.esES or {}

FDJ.ContentLocales.esES.dungeons = {
    ["Hall of Thanes"] = {
        ["name"] = "Salón de los Thanes",
        ["location"] = "Bajo Forjaz, Dun Morogh",
        ["description"] = "Alguien ha irrumpido en la cripta real enana bajo Forjaz.",
    },
    ["Ragefire Chasm"] = {
        ["name"] = "Sima Ígnea",
        ["location"] = "Círculo de las Sombras, Orgrimmar",
        ["description"] = "Troggs y cultistas del Filo Ardiente infestan las cavernas abrasadoras bajo Orgrimmar.",
    },
    ["Ruins of Lordaeron"] = {
        ["name"] = "Ruinas de Lordaeron",
        ["location"] = "La ciudad en ruinas de Lordaeron",
        ["description"] = "Las fuerzas de la Plaga siguen acechando la antigua capital mientras un nigromante gana poder entre las ruinas.",
    },
    ["The Deadmines"] = {
        ["name"] = "Las Minas de la Muerte",
        ["location"] = "Arroyo de la Luna, Páramos de Poniente",
        ["description"] = "La Hermandad de los Defias construye un buque de guerra en las minas bajo Arroyo de la Luna.",
    },
    ["Wailing Caverns"] = {
        ["name"] = "Cuevas de los Lamentos",
        ["location"] = "Los Baldíos del Norte",
        ["description"] = "Bajo Los Baldíos, druidas y Señores del Colmillo vigilan al Naralex durmiente mientras criaturas retorcidas recorren las cuevas.",
    },
    ["Shadowfang Keep"] = {
        ["name"] = "Castillo de Colmillo Oscuro",
        ["location"] = "Bosque de Argénteos",
        ["description"] = "El archimago Arugal y sus seguidores huargen ocupan el castillo sobre Aldea Piroleña.",
    },
    ["Blackfathom Deeps"] = {
        ["name"] = "Cavernas de Brazanegra",
        ["location"] = "Playa de Zoram, Vallefresno",
        ["description"] = "Una ruina elfa de la noche inundada en la Playa de Zoram, ocupada por nagas, múrlocs y cultores del Martillo Crepuscular al servicio de Aku’mai.",
    },
    ["The Stockade"] = {
        ["name"] = "Las Mazmorras de Ventormenta",
        ["location"] = "Ventormenta",
        ["description"] = "Los prisioneros Defias se han apoderado de la prisión de Ventormenta.",
    },
}

FDJ.ContentLocales.esES.quests = {
    [386] = { ["name"] = "Lo que va, vuelve...", ["objective"] = "Mata a Targorr el Temible en Las Mazmorras y lleva su cabeza al guardia Berton." },
    [377] = { ["name"] = "Crimen y castigo", ["objective"] = "Mata a Dextren Ward en Las Mazmorras y lleva su mano al consejero Millstipe." },
    [387] = { ["name"] = "Sofoca el levantamiento", ["objective"] = "Mata a 10 prisioneros Defias, 8 convictos Defias y 8 insurgentes Defias en Las Mazmorras." },
    [388] = { ["name"] = "El color de la sangre", ["objective"] = "Recoge 10 pañuelos de lana roja de los Defias en Las Mazmorras." },
    [378] = { ["name"] = "La furia interior", ["objective"] = "Mata a Kam Deepfury en Las Mazmorras y lleva su cabeza a Motley Garmason." },
    [391] = { ["name"] = "Los disturbios de Las Mazmorras", ["objective"] = "Mata a Bazil Thredd en Las Mazmorras y lleva su cabeza al alcaide Thelwater." },
    [96395] = {
        ["name"] = "Un viejo rencor",
        ["objective"] = "Da descanso al espíritu de Faldrim Anvilmar.",
    },
    [96403] = {
        ["name"] = "Reliquias importantes",
        ["objective"] = "Recoge 8 reliquias enanas en el Salón de los Thanes.",
    },
    [96394] = {
        ["name"] = "Los muertos inquietos",
        ["objective"] = "Mata a 15 apariciones enfurecidas y 10 almas atormentadas, y después da descanso al espíritu de Anvilmar.",
    },
    [96393] = {
        ["name"] = "Incursión en la antigua Forjaz",
        ["objective"] = "Entra en el Salón de los Thanes y consigue la cabeza de Durgen Dirgehammer.",
        ["note"] = "La cadena empieza con el Mapa Hierro Negro, que dejan caer los espías Hierro Negro de Dun Morogh.",
    },
    [98423] = {
        ["name"] = "El tratado de entendimiento",
        ["objective"] = "Lleva el tratado de entendimiento a Magni Barbabronce en Forjaz.",
        ["note"] = "La tablilla de piedra está en una de las cámaras del Relicario de los Reyes, en la sala final de Durgen Dirgehammer. Abre las cámaras e interactúa con la tablilla antes de abandonar la mazmorra.",
    },
    [1486] = {
        ["name"] = "Pieles descarriadas",
        ["objective"] = "Lleva 20 pieles descarriadas a Nalpak.",
    },
    [1491] = {
        ["name"] = "Bebidas inteligentes",
        ["objective"] = "Lleva 6 esencias de los Lamentos a Mebok Mizzyrix.",
    },
    [959] = {
        ["name"] = "Problemas en los muelles",
        ["objective"] = "Consigue el oporto de 99 años de Mad Magglish en las Cuevas de los Lamentos.",
    },
    [1487] = {
        ["name"] = "Erradicación de descarriados",
        ["objective"] = "Mata a 7 devastadores descarriados, 7 víboras descarriadas, 7 reptadores descarriados y 7 colmillos de terror descarriados.",
    },
    [6981] = {
        ["name"] = "El fragmento resplandeciente",
        ["objective"] = "Viaja a Trinquete, encuentra a alguien que pueda identificar el fragmento resplandeciente y llévalo después adonde te indiquen.",
        ["note"] = "Esta misión no da un objeto directamente. La misión posterior «En pesadillas» ofrece más adelante:",
    },
    [914] = {
        ["name"] = "Líderes del Colmillo",
        ["objective"] = "Lleva a Nara Crin Salvaje las gemas de Kobrahn, Anacondra, Pythas y Serpentis.",
        ["note"] = "Requiere la cadena de los oasis de Los Baldíos. Completa «Las pozas olvidadas», «El oasis estancado» y «Seres alterados», y habla después con Hamuul Runatótem y Nara Crin Salvaje antes de que «Líderes del Colmillo» esté disponible.",
    },
    [962] = {
        ["name"] = "Flor de serpiente",
        ["objective"] = "Recoge 10 flores de serpiente en las Cuevas de los Lamentos.",
    },
    [95250] = {
        ["name"] = "Criaturas abominables",
        ["objective"] = "Consigue la cabeza del Barón en las Ruinas de Lordaeron.",
    },
    [97288] = {
        ["name"] = "Tormento interminable",
        ["objective"] = "Lleva la cabeza abominable a Entrañas.",
        ["note"] = "La elección de objeto se entrega en la misión posterior «Tormento interminable» en Entrañas.",
    },
    [92401] = {
        ["name"] = "Una petición aterrada",
        ["objective"] = "Investiga la desaparición de Edward Heartweaver en las Ruinas de Lordaeron.",
    },
    [95195] = {
        ["name"] = "Insignia ensangrentada",
        ["objective"] = "Recoge 10 insignias ensangrentadas.",
    },
    [95189] = {
        ["name"] = "Blasón de Lordaeron",
        ["objective"] = "Lleva el blasón de Lordaeron a Ventormenta.",
        ["note"] = "Los informes de la comunidad indican que el blasón puede aparecer en varios puntos de la mazmorra, incluidos pisos superiores de torres, cámaras laterales o criptas cerca del Barón y la zona de Bjork.",
    },
    [95204] = {
        ["name"] = "Blasón de Lordaeron",
        ["objective"] = "Lleva el blasón de Lordaeron a Entrañas.",
        ["note"] = "Los informes de la comunidad indican que el blasón puede aparecer en varios puntos de la mazmorra, incluidos pisos superiores de torres, cámaras laterales o criptas cerca del Barón y la zona de Bjork.",
    },
    [92421] = {
        ["name"] = "Justicia de la Luz",
        ["objective"] = "Recoge 25 extremidades intactas en las Ruinas de Lordaeron.",
    },
    [92415] = {
        ["name"] = "Recuerda que te quiero",
        ["objective"] = "Lleva la carta manchada de sangre a la matrona de huérfanos Nightingale.",
        ["note"] = "Esta misión comienza con el objeto «Carta manchada de sangre».",
    },
    [95216] = {
        ["name"] = "La nueva peste",
        ["objective"] = "Consigue la cepa altamente tóxica de Witherfang.",
    },
    [92422] = {
        ["name"] = "Ira de Rath’mael",
        ["objective"] = "Mata a Rath’mael en las Ruinas de Lordaeron.",
    },
    [214] = {
        ["name"] = "Pañuelos de seda roja",
        ["objective"] = "Recoge 10 pañuelos de seda roja de Defias en las Minas de la Muerte.",
        ["note"] = "Requiere el paso de escolta de la Hermandad de los Defias.",
    },
    [168] = {
        ["name"] = "Recogiendo recuerdos",
        ["objective"] = "Recoge 4 tarjetas del sindicato de mineros de los mineros no-muertos en los túneles fuera de la instancia.",
        ["note"] = "El túnel lateral de no-muertos está antes del portal de la instancia.",
    },
    [92753] = {
        ["name"] = "Destrucción en las Minas de la Muerte",
        ["objective"] = "Coloca los explosivos junto a la forja en las Minas de la Muerte.",
    },
    [167] = {
        ["name"] = "Oh, hermano…",
        ["objective"] = "Consigue la insignia de Thistlenettle del capataz Thistlenettle en el túnel lateral de no-muertos.",
        ["note"] = "El capataz está en los túneles antes del portal de la instancia.",
    },
    [2040] = {
        ["name"] = "Asalto subterráneo",
        ["objective"] = "Consigue el Gnoam Sprecklesprocket del Desgarrador de Sneed.",
        ["note"] = "Continúa tras «Habla con Shoni».",
    },
    [166] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Derrota a Edwin VanCleef y consigue su cabeza.",
        ["note"] = "Último paso de mazmorra de la cadena «La Hermandad de los Defias»; completa primero los pasos anteriores.",
    },
    [373] = {
        ["name"] = "La carta sin enviar",
        ["objective"] = "Lleva la carta al arquitecto de la ciudad en Ventormenta.",
        ["note"] = "Inicia una cadena posterior que continúa con Bazil Thredd.",
    },
    [971] = {
        ["name"] = "Conocimiento en las profundidades",
        ["objective"] = "Consigue el Manuscrito de Lorgalis en las Cavernas de Brazanegra.",
        ["note"] = "El Manuscrito de Lorgalis está en un cofre de hierro dañado bajo el agua en el estanque de Ask’ar, en el nicho norte justo después de la sala de tortugas de Ghamoo-ra.",
    },
    [1275] = {
        ["name"] = "Investigando la corrupción",
        ["objective"] = "Recoge 8 tallos cerebrales corruptos de criaturas en las Cavernas de Brazanegra.",
        ["note"] = "Continúa tras «La corrupción lejana».",
    },
    [1198] = {
        ["name"] = "En busca de Thaelrid",
        ["objective"] = "Encuentra al Guardia Argenta Thaelrid en las Cavernas de Brazanegra.",
    },
    [1199] = {
        ["name"] = "Cae el Crepúsculo",
        ["objective"] = "Recoge 10 colgantes del Martillo Crepuscular de sus miembros en las Cavernas de Brazanegra.",
    },
    [1200] = {
        ["name"] = "Villanía en Brazanegra",
        ["objective"] = "Derrota al Señor Crepuscular Kelris y consigue su cabeza.",
    },
    [6564] = {
        ["name"] = "Lealtad a los Dioses Antiguos",
        ["objective"] = "Lleva la Nota Húmeda a Je’neu Sancrea en Vallefresno.",
    },
    [6562] = {
        ["name"] = "Problemas en las profundidades",
        ["objective"] = "Habla con Je’neu Sancrea en Vallefresno.",
        ["note"] = "Paso introductorio que lleva a «La esencia de Aku’mai».",
    },
    [6563] = {
        ["name"] = "La esencia de Aku’mai",
        ["objective"] = "Recoge 20 zafiros de Aku’mai en las Cavernas de Brazanegra.",
        ["note"] = "Continúa tras «Problemas en las profundidades».",
    },
    [6565] = {
        ["name"] = "Lealtad a los Dioses Antiguos",
        ["objective"] = "Derrota a Lorgus Jett en las Cavernas de Brazanegra.",
        ["note"] = "Continúa tras la versión de «Lealtad a los Dioses Antiguos» que comienza con la Nota Húmeda.",
    },
    [6561] = {
        ["name"] = "Villanía en Brazanegra",
        ["objective"] = "Derrota al Señor Crepuscular Kelris y consigue su cabeza.",
    },
    [6921] = {
        ["name"] = "Entre las ruinas",
        ["objective"] = "Consigue el núcleo profundo de la piedra profunda en las Cavernas de Brazanegra.",
        ["note"] = "La piedra profunda también está vinculada al encuentro opcional con el Barón Aquanis.",
    },
    [5723] = {
        ["name"] = "Probando la fuerza del enemigo",
        ["objective"] = "Mata a 8 troggs de Sima Ígnea y 8 chamanes de Sima Ígnea dentro de Sima Ígnea.",
    },
    [5722] = {
        ["name"] = "Buscando la bolsa perdida",
        ["objective"] = "Encuentra el cadáver de Maur Tótem Siniestro dentro de Sima Ígnea y regístralo.",
    },
    [5724] = {
        ["name"] = "Devolviendo la bolsa perdida",
        ["objective"] = "Lleva la bolsa Tótem Siniestro a Rahauro en Cima del Trueno.",
    },
    [5728] = {
        ["name"] = "Enemigos ocultos",
        ["objective"] = "Mata a Bazzalan y Jergosh el Convocador dentro de Sima Ígnea.",
        ["note"] = "Requiere los pasos anteriores de la cadena «Enemigos ocultos» en Orgrimmar. El siguiente paso ofrece más adelante:",
    },
    [5761] = {
        ["name"] = "Matando a la bestia",
        ["objective"] = "Mata a Taragaman el Hambriento y consigue su corazón.",
    },
    [5725] = {
        ["name"] = "El poder de destruir…",
        ["objective"] = "Recoge «Hechizos de las Sombras» e «Invocaciones del Vacío Abisal» en Sima Ígnea.",
    },
    [1098] = {
        ["name"] = "Acechadores de la muerte en Colmillo Oscuro",
        ["objective"] = "Encuentra al Acechador de la muerte Adamant y al Acechador de la muerte Vincent en el Castillo de Colmillo Oscuro.",
    },
    [1740] = {
        ["name"] = "El orbe de Soran’ruk",
        ["objective"] = "Encuentra 3 fragmentos de Soran’ruk y 1 fragmento grande de Soran’ruk y llévaselos a Doan Karhan.",
        ["note"] = "Misión de clase de brujo. Los fragmentos proceden del Castillo de Colmillo Oscuro y las Cavernas de Brazanegra.",
    },
    [1013] = {
        ["name"] = "El libro de Ur",
        ["objective"] = "Lleva el Libro de Ur del Castillo de Colmillo Oscuro al guardián Bel’dugur.",
    },
    [1014] = {
        ["name"] = "Arugal debe morir",
        ["objective"] = "Mata al archimago Arugal y lleva su cabeza a Dalar Tejealba.",
        ["note"] = "Los datos actuales de Forever también indican «Intelecto Arcano» como recompensa aprendida.",
    },
    [96391] = {
        ["name"] = "Mapa subterráneo",
        ["objective"] = "Lleva el Mapa Hierro Negro a Earthseer Farsen en Dun Morogh.",
        ["description"] = "El Mapa Hierro Negro inicia esta misión y lleva directamente a «Incursión en la antigua Forjaz».",
    },
    [865] = {
        ["name"] = "Cuernos de raptor",
        ["objective"] = "Recoge 5 cuernos de raptor intactos de los guadañeros Solescama y llévaselos a Mebok Mizzyrix.",
        ["description"] = "Debe completarse antes de que «Bebidas inteligentes» esté disponible.",
    },
    [870] = {
        ["name"] = "Las pozas olvidadas",
        ["objective"] = "Investiga el agua de las pozas olvidadas al noroeste de El Cruce y después informa.",
        ["description"] = "Investiga la fisura bajo las pozas olvidadas.",
    },
    [877] = {
        ["name"] = "El oasis estancado",
        ["objective"] = "Lleva las semillas secas al oasis estancado, pruébalas en la fisura y vuelve con Tonga.",
        ["description"] = "Siguiente investigación de oasis requerida después de «Las pozas olvidadas».",
    },
    [880] = {
        ["name"] = "Seres alterados",
        ["objective"] = "Lleva 8 caparazones de mordedor alterado a Tonga Runatótem en El Cruce.",
        ["description"] = "Completar «Seres alterados» desbloquea «Hamuul Runatótem».",
    },
    [1489] = {
        ["name"] = "Hamuul Runatótem",
        ["objective"] = "Habla con Hamuul Runatótem en Alto de los Ancestros, Cima del Trueno.",
        ["description"] = "Después de «Seres alterados», Tonga te envía con Hamuul.",
    },
    [1490] = {
        ["name"] = "Nara Crin Salvaje",
        ["objective"] = "Habla con Nara Crin Salvaje en Cima del Trueno.",
        ["description"] = "Nara Crin Salvaje es el último requisito antes de «Líderes del Colmillo».",
    },
    [153] = {
        ["name"] = "Pañuelos de cuero rojo",
        ["objective"] = "Lleva 15 pañuelos de cuero rojo al explorador Galiaan en Colina del Centinela.",
        ["description"] = "Debe completarse antes de «Pañuelos de seda roja».",
    },
    [65] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Habla con Wiley el Negro en Villa del Lago.",
        ["description"] = "Primer paso de la cadena requerida «La Hermandad de los Defias».",
    },
    [132] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Devuelve la nota de Wiley a Gryan Manto Pétreo en Páramos de Poniente.",
        ["description"] = "Segundo paso de la cadena «La Hermandad de los Defias».",
    },
    [135] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Lleva la nota de Wiley al maestro Mathias Shaw en Ventormenta.",
        ["description"] = "Shaw investiga la conexión entre los Defias y los Canteros.",
    },
    [141] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Devuelve el informe de Shaw a Gryan Manto Pétreo en Páramos de Poniente.",
        ["description"] = "Lleva a Gryan los hallazgos de Shaw sobre Edwin VanCleef.",
    },
    [142] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Localiza al mensajero Defias en Páramos de Poniente y lleva su mensaje a Gryan Manto Pétreo.",
        ["description"] = "El mensajero patrulla las carreteras entre Arroyo de la Luna, Cantera de la Costa del Oro y Mina de Jango.",
        ["note"] = "El mensajero Defias patrulla las carreteras entre Arroyo de la Luna, Cantera de la Costa del Oro y Mina de Jango.",
    },
    [155] = {
        ["name"] = "La Hermandad de los Defias",
        ["objective"] = "Escolta al Traidor Defias hasta que revele el escondite de los Defias y vuelve después con Gryan Manto Pétreo.",
        ["description"] = "Último requisito antes del paso de mazmorra de «La Hermandad de los Defias».",
    },
    [2041] = {
        ["name"] = "Habla con Shoni",
        ["objective"] = "Habla con Shoni la Silenciosa en Ventormenta.",
        ["description"] = "Lleva directamente a «Asalto subterráneo».",
    },
    [92742] = {
        ["name"] = "Probando los pozos",
        ["objective"] = "Usa el kit de muestra de agua de pozo en los pozos de Granja de Jansen y Granja de Molsen.",
        ["description"] = "Primera misión de la cadena «Suelo tóxico».",
    },
    [92744] = {
        ["name"] = "Branquias de múrloc",
        ["objective"] = "Recoge 7 branquias de múrloc costero a lo largo de la costa de Páramos de Poniente.",
        ["description"] = "Segunda misión de la cadena «Suelo tóxico».",
    },
    [92745] = {
        ["name"] = "El estado de las minas",
        ["objective"] = "Mata a 4 excavadores kóbold en Mina de Jango y 6 mineros Zarpa de Río en Cantera de la Costa del Oro.",
        ["description"] = "Investiga si las minas de Páramos de Poniente están causando la contaminación.",
    },
    [92747] = {
        ["name"] = "Espionaje en Arroyo de la Luna",
        ["objective"] = "Recoge 8 suministros industriales sospechosos en Arroyo de la Luna.",
        ["description"] = "Los suministros están en las cuevas que conducen hacia la entrada de las Minas de la Muerte.",
    },
    [92748] = {
        ["name"] = "Consulta sobre explosivos",
        ["objective"] = "Viaja al Distrito de los Enanos de Ventormenta y encuentra a un ingeniero que pueda ayudar con los explosivos.",
        ["description"] = "Comienza la parte de explosivos de la cadena «Suelo tóxico».",
    },
    [92749] = {
        ["name"] = "Un plan con dinamita",
        ["objective"] = "Consigue 10 dinamitas burdas y vuelve con Sprite Jumpsprocket en Ventormenta.",
        ["description"] = "La dinamita burda puede fabricarse, comerciarse o comprarse en la casa de subastas.",
        ["note"] = "La dinamita burda puede fabricarse, comerciarse o comprarse en la casa de subastas.",
    },
    [92750] = {
        ["name"] = "Detonación a distancia",
        ["objective"] = "Habla con la Inteligencia de Ventormenta sobre un detonador remoto.",
        ["description"] = "Necesitas un detonador remoto para la explosión planeada.",
    },
    [92751] = {
        ["name"] = "Detonación a distancia",
        ["objective"] = "Lleva el kit de detonador remoto de vuelta a Sprite Jumpsprocket en el Distrito de los Enanos.",
        ["description"] = "Devuelve el detonador al ingeniero.",
    },
    [92752] = {
        ["name"] = "Consulta sobre explosivos",
        ["objective"] = "Vuelve con Alba Fairmoon en la posada de Colina del Centinela con los explosivos terminados.",
        ["description"] = "Preparación final antes de «Destrucción en las Minas de la Muerte».",
    },
    [92819] = {
        ["name"] = "Destrucción en las Minas de la Muerte",
        ["objective"] = "Usa el detonador.",
        ["description"] = "Último paso de la cadena «Suelo tóxico».",
    },
    [5726] = {
        ["name"] = "Enemigos ocultos",
        ["objective"] = "Lleva a Thrall una insignia de teniente del Filo Ardiente de Roca del Cráneo.",
        ["description"] = "Primer paso requerido de «Enemigos ocultos» para la cadena de Sima Ígnea.",
    },
    [5727] = {
        ["name"] = "Enemigos ocultos",
        ["objective"] = "Habla con Neeru Hojafuego en el Círculo de las Sombras y vuelve después con Thrall.",
        ["description"] = "Neeru está en el Círculo de las Sombras cerca de la entrada de Sima Ígnea.",
    },
    [3765] = {
        ["name"] = "La corrupción lejana",
        ["objective"] = "Viaja hasta Gershala Susurranoche en Auberdine, Costa Oscura.",
        ["description"] = "Misión introductoria de la Alianza que debe completarse antes de «Investigando la corrupción».",
    },
}

FDJ.ContentLocales.esES.bosses = {
    ["Trash Drops"] = "Botín trash",
    ["The Baron"] = "El Barón",
    ["The Abandoned"] = "El Abandonado",
    ["Lordaeron Captain"] = "Capitán de Lordaeron",
}

FDJ.ContentLocales.esES.slotParts = {
    ["Chest"] = "Pecho",
    ["Leather"] = "Cuero",
    ["Wrist"] = "Muñecas",
    ["Cloth"] = "Tela",
    ["Back"] = "Espalda",
    ["Waist"] = "Cintura",
    ["Mail"] = "Malla",
    ["Hands"] = "Manos",
    ["Feet"] = "Pies",
    ["Legs"] = "Piernas",
    ["Neck"] = "Cuello",
    ["Finger"] = "Dedo",
    ["Trinket"] = "Abalorio",
    ["Bag"] = "Bolsa",
    ["One-Hand"] = "Una mano",
    ["Main Hand"] = "Mano derecha",
    ["Off Hand"] = "Mano izquierda",
    ["Two-Hand"] = "Dos manos",
    ["Dagger"] = "Daga",
    ["Sword"] = "Espada",
    ["Axe"] = "Hacha",
    ["Mace"] = "Maza",
    ["Staff"] = "Bastón",
    ["Shield"] = "Escudo",
    ["Polearm"] = "Arma de asta",
    ["Ranged"] = "A distancia",
    ["Wand"] = "Varita",
    ["Thrown"] = "Arrojadiza",
    ["Engineering"] = "Ingeniería",
    ["Quest Item"] = "Objeto de misión",
    ["Head"] = "Cabeza",
    ["Shoulder"] = "Hombros",
    ["Bow"] = "Arco",
    ["Crossbow"] = "Ballesta",
    ["Fist Weapon"] = "Arma de puño",
    ["Leatherworking Recipe"] = "Patrón de peletería",
    ["Held In Off-hand"] = "Sostener con la mano izquierda",
}

FDJ.ContentLocales.esES.replacements = {
    {"Farm Dark Iron Spies here for the Dark Iron Map", "Mata espías Hierro Negro aquí para conseguir el Mapa Hierro Negro"},
    {"Dark Iron Map drops from Dark Iron Spies around Ironband's Compound", "El Mapa Hierro Negro lo sueltan los espías Hierro Negro alrededor del Campamento de Vetaferro"},
    {"Alba Fairmoon is inside the Sentinel Hill inn", "Alba Fairmoon está dentro de la posada de Colina del Centinela"},
    {"Argos Nightwhisper is in The Park, beside the moonwell area.", "Argos Susurranoche está en El Parque, junto a la zona del pozo de la Luna."},
    {"Serpentbloom starts from Apothecary Zamah in the Pools of Vision beneath Spirit Rise", "Flor de serpiente comienza con la boticaria Zamah en las Pozas de las Visiones, bajo Alto de los Espíritus"},
    {"Start Hidden Enemies here", "« Enemigos ocultos » comienza aquí"},
    {"Start In Search of Thaelrid here", "« En busca de Thaelrid » comienza aquí"},
    {"Start Raptor Horns here", "« Cuernos de raptor » comienza aquí"},
    {"Start Red Leather Bandanas here", "« Pañuelos de cuero rojo » comienza aquí"},
    {"Start Speak with Shoni here", "« Habla con Shoni » comienza aquí"},
    {"Start Testing the Wells here", "« Probando los pozos » comienza aquí"},
    {"Start The Defias Brotherhood here", "« La Hermandad de los Defias » comienza aquí"},
    {"Start The Forgotten Pools here", "« Las pozas olvidadas » comienza aquí"},
    {"southeast of Brill", "al sureste de Rémol"},
    {"Pools of Vision", "Pozas de las Visiones"},
    {"Sun Rock Retreat", "Refugio Roca del Sol"},
    {"Tinker Town", "Ciudad Manitas"},
    {"Darnassus", "Darnassus"},
    {"Apothecarium", "El Apothecarium"},
    {"by the bridge / vault entrance in", "junto al puente / entrada de la cámara en"},
    {"near the dungeon entrance", "cerca de la entrada de la mazmorra"},
    {"after the first room", "después de la primera sala"},
    {"inside the dungeon", "dentro de la mazmorra"},
    {"just inside Ruins of Lordaeron", "justo dentro de las Ruinas de Lordaeron"},
    {"graveyard inside Ruins of Lordaeron", "cementerio dentro de las Ruinas de Lordaeron"},
    {"%(%s*after Underground Map%s*%)", "(después de «Mapa subterráneo»)"},
    {"above the entrance to", "sobre la entrada de"},
    {"left of the entrance", "a la izquierda de la entrada"},
    {"Follow the quest directions beginning in", "Sigue las indicaciones de la misión comenzando en"},
    {"Stone tablet inside a vault in the Reliquary of Kings", "Tablilla de piedra dentro de una cámara del Relicario de los Reyes"},
    {"Durgen Dirgehammer's room", "sala de Durgen Dirgehammer"},
    {"Maur Grimtotem's corpse", "cadáver de Maur Tótem Siniestro"},
    {"dropped by Dark Iron Spies", "soltado por espías Hierro Negro"},
    {"Blackfathom Tide Priestesses", "Sacerdotisas de las Mareas de Brazanegra"},
    {"taken from", "tomado de"},
    {"dropped by", "soltado por"},
    {"at Ironband's Compound", "en el Campamento de Vetaferro"},
    {"Ironband's Compound", "Campamento de Vetaferro"},
    {"Dark Iron Spies", "espías Hierro Negro"},
    {"Northern Barrens", "Los Baldíos del Norte"},
    {"The Barrens", "Los Baldíos"},
    {"Cleft of Shadow", "Círculo de las Sombras"},
    {"Valley of Wisdom", "Valle de la Sabiduría"},
    {"Royal Quarter", "Barrio Real"},
    {"Elder Rise", "Alto de los Ancestros"},
    {"Dwarven District", "Distrito de los Enanos"},
    {"Cathedral Square", "Plaza de la Catedral"},
    {"Old Town", "Casco Antiguo"},
    {"Sentinel Hill tower", "torre de Colina del Centinela"},
    {"Sentinel Hill inn", "posada de Colina del Centinela"},
    {"Sentinel Hill", "Colina del Centinela"},
    {"Stormwind City", "Ventormenta"},
    {"Stormwind", "Ventormenta"},
    {"Ironforge", "Forjaz"},
    {"Thunder Bluff", "Cima del Trueno"},
    {"Undercity", "Entrañas"},
    {"Silverpine Forest", "Bosque de Argénteos"},
    {"The Sepulcher", "El Sepulcro"},
    {"Darkshore", "Costa Oscura"},
    {"Ashenvale", "Vallefresno"},
    {"Stonetalon Mountains", "Sierra Espolón"},
    {"Redridge Mountains", "Montañas Crestagrana"},
    {"Zoram Strand", "Playa de Zoram"},
    {"Zoram'gar Outpost", "Avanzada de Zoram’gar"},
    {"Moonbrook", "Arroyo de la Luna"},
    {"Ratchet", "Trinquete"},
    {"The Crossroads", "El Cruce"},
    {"Craftsmen's Terrace", "Bancal del Artesano"},
    {"Forlorn Cavern", "Caverna Abandonada"},
    {"Skull Rock", "Roca del Cráneo"},
    {"Gold Coast Quarry", "Cantera de la Costa del Oro"},
    {"Jangolode Mine", "Mina de Jango"},
    {"Lakeshire", "Villa del Lago"},
    {"The Park", "El Parque"},
    {"Pyrewood Village", "Aldea Piroleña"},
    {"inside Blackfathom Deeps", "dentro de las Cavernas de Brazanegra"},
    {"inside Shadowfang Keep", "dentro del Castillo de Colmillo Oscuro"},
    {"inside Ragefire Chasm", "dentro de Sima Ígnea"},
    {"inside Ruins of Lordaeron", "dentro de las Ruinas de Lordaeron"},
    {"inside Hall of Thanes", "dentro del Salón de los Thanes"},
    {"inside the Deadmines", "dentro de las Minas de la Muerte"},
    {"Wailing Caverns", "Cuevas de los Lamentos"},
    {"Blackfathom Deeps", "Cavernas de Brazanegra"},
    {"Shadowfang Keep", "Castillo de Colmillo Oscuro"},
    {"Ragefire Chasm", "Sima Ígnea"},
    {"Ruins of Lordaeron", "Ruinas de Lordaeron"},
    {"Hall of Thanes", "Salón de los Thanes"},
    {"The Deadmines", "Las Minas de la Muerte"},
    {"Deadmines", "Minas de la Muerte"},
    {"Item start:", "Objeto que inicia la misión:"},
    {"Use ", "Usa "},
    {"Dropped by:", "Lo suelta:"},
    {"Looted from", "Saqueado de"},
    {"Rare spawn.", "Aparición rara."},
    {"Quest Item", "Objeto de misión"},
    {"Trash Drops", "Botín trash"},
    {"Alliance", "Alianza"},
    {"Horde", "Horda"},
    {"Both", "Ambas"},
    {"Warlock", "Brujo"},
    {"Mage", "Mago"},
    {"Priest", "Sacerdote"},
    {"Rogue", "Pícaro"},
    {"Warrior", "Guerrero"},
    {"Hunter", "Cazador"},
    {"Druid", "Druida"},
    {"Paladin", "Paladín"},
    {"Shaman", "Chamán"},
}
FDJ.ContentLocales.esMX = FDJ.ContentLocales.esES
